autowarefoundation/autoware_launch

- autoware_launch/launch/autoware.launch.xml
- autoware_launch/launch/logging_simulator.launch.xml
- autoware_launch/launch/planning_simulator.launch.xml
In order to prevent unnecessary propagation of LaunchConfigurations, I added the `group` tag to each section.
> fix: add group to each section

- .pre-commit-config.yaml
- autoware_launch/launch/autoware.launch.xml
- autoware_launch/launch/logging_simulator.launch.xml
See https://github.com/tier4/pre-commit-hooks-ros/pull/50 and https://github.com/tier4/pre-commit-hooks-ros/releases/tag/v0.6.0.
Related: https://github.com/autowarefoundation/autoware/pull/143
> ci(pre-commit): update pre-commit-hooks-ros

- autoware_launch/rviz/autoware.rviz
disable covariance and twist of PredictedObjects for perception because visualization is busy.
> feat: cosmetic change autoware.rviz for perception

- autoware_launch/rviz/autoware.rviz
Add wall marker visualization in obstacle_avoidance_planner.
> feat(obstacle_avoidance_planner): add obstacle_avoidance_planner wall marker in autoware.rviz

- autoware_launch/launch/autoware.launch.xml
- autoware_launch/launch/logging_simulator.launch.xml
- autoware_launch/launch/planning_simulator.launch.xml
Signed-off-by: mitsudome-r <ryohsuke.mitsudome@tier4.jp>
This PR modifies the following launch files to launch api related packages to have integration with TIER IV's scenario simulator.
* autoware.launch.xml
* logging_simulator.launch.xml
* planning_simulator.launch.xml
* Issue: https://github.com/autowarefoundation/autoware.universe/issues/656
Dependent PR:
* https://github.com/autowarefoundation/autoware/pull/156
* https://github.com/autowarefoundation/autoware.universe/pull/658
Here's the test procedure: 
* Download and unzip the [sample data](https://drive.google.com/file/d/1vWMLbmwJJE5tYO40ypCMxqtmgQPQxhiw/view?usp=sharing) that includes the map and a sample scenario file
* modify the map file path in the scenario file (`t4v2.yaml`) to the path of the Downloaded map
* If dependent …
> feat: add autoware_api.launch.xml to launch files in autoware_launch package

- autoware_launch/rviz/autoware.rviz
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/945
When launched.
Planning directory structure.
> refactor: update rviz config for virtual wall marker separation

- autoware_launch/rviz/autoware.rviz
- sync to universe rviz setting https://github.com/tier4/autoware_launch/pull/196
- replace  ros time panel to date time panel which is used in rviz config
- sync : https://github.com/tier4/autoware_launch/pull/353/files
- sync :  https://github.com/tier4/autoware_launch/pull/281
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guideli …
> chore: update to universe config

- autoware_launch/rviz/autoware.rviz
Signed-off-by: tomoya.kimura <tomoya.kimura@tier4.jp>
https://github.com/autowarefoundation/autoware.universe/pull/1206
https://github.com/tier4/autoware_launch/pull/378
Add a line with property to object display
> feat: add line_width property to object display

- autoware_launch/rviz/autoware.rviz
Update rviz config for pull_over module https://github.com/autowarefoundation/autoware.universe/pull/873.
https://github.com/autowarefoundation/autoware.universe/pull/873
> chore(rviz): update rviz config for pull_over

- autoware_launch/launch/autoware.launch.xml
- autoware_launch/launch/logging_simulator.launch.xml
- autoware_launch/launch/planning_simulator.launch.xml
use autoware.launch.xml in planning_simulator.launch.xml and logging_simulator.launch.xml
logging simulator (by changing map, system, sensing, ..., arguments true or false) and planning simulator works well with this PR
https://github.com/autowarefoundation/autoware_launch/issues/60 …
> refactor(autoware_launch): use autoware.launch.xml in planning/logging_simulator.launch.xml

- autoware_launch/rviz/autoware.rviz
Signed-off-by: Hasanzfdn <hsnzfdn@gmail.com>
closes https://github.com/autowarefoundation/autoware_launch/issues/80 
> feat(autoware_launch): add vehicle footprint to autoware.rviz

- autoware_launch/rviz/autoware.rviz
Signed-off-by: Yukihiro Saito <yukky.saito@gmail.com>
disable the visualization of object pose covariance.
> feat: disable visualization of object pose covariance

- autoware_launch/launch/autoware.launch.xml
Launch nodes for this PR.
https://github.com/autowarefoundation/autoware.universe/pull/1494
> feat(autoware_launch): add rviz helper for ad api

- autoware_launch/launch/autoware.launch.xml
- autoware_launch/launch/logging_simulator.launch.xml
- autoware_launch/launch/planning_simulator.launch.xml
Launch nodes for this PR.
https://github.com/autowarefoundation/autoware.universe/pull/1500
> feat(autoware_launch): apply the change of pose initializer

- autoware_launch/package.xml
> fix: add adapi dependency

- autoware_launch/launch/autoware.launch.xml
- autoware_launch/launch/e2e_simulator.launch.xml
Signed-off-by: Shumpei Wakabayashi <shumpei.wakabayashi@tier4.jp>
Add the [degital twin simulation](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/digital-twin-simulation/awsim-tutorial/) launcher.
This launcher is temporal one. In the future, the simulator can be launched with `autoware.launch.xml`.
- [TIERIV INTERNAL LINK](https://tier4.atlassian.net/browse/AJD-484)
- https://github.com/autowarefoundation/autoware.universe/pull/1991
I tested this launcher with TIERIV INTERNAL DEGITAL TWIN SIMULATOR and it works as we expected.
What I want reviewers to check is
- the launcher name
- `e2e_simulator.launch`, `degital_twin_simulator.launch` and etc..
- `enable_fine_detection` off 
- The current trained model of fine detection is finetuned with …
> feat(autoware_launch): add e2e_simulator.launch.xml

- autoware_launch/rviz/autoware.rviz
Signed-off-by: kminoda <koji.minoda@tier4.jp>
Set larger size for NDT result pointclouds.
> fix(rviz): enlarge pointcloud size for NDT results

- autoware_launch/rviz/autoware.rviz
Signed-off-by: Mehmet Dogru <42mehmetdogru42@gmail.com>
This PR updates the name of obstacle_avoidance_planner virtual_wall marker
> fix(rviz): update obstacle_avoidance_planner virtual_wall topic name

- autoware_launch/launch/autoware.launch.xml
- autoware_launch/launch/planning_simulator.launch.xml
- autoware_launch/package.xml
Due to autowarefoundation/autoware.universe#2405, currently the build of autoware_launch failed.
> fix(autoware_launch): remove web_controller

- autoware_launch/rviz/autoware.rviz
Signed-off-by: Fumiya Watanabe <rej55.g@gmail.com>
To apply this change, I change the `autoware.rviz` to visualize multiple candidate paths.
https://github.com/autowarefoundation/autoware.universe/pull/2486
See https://github.com/autowarefoundation/autoware.universe/pull/2486 …
> feat(autoware_launch): visualize multiple candidate paths

- autoware_launch/launch/autoware.launch.xml
- autoware_launch/launch/planning_simulator.launch.xml
Update galactic branch which is needed to work AWSIM.
I cherry picked
- https://github.com/autowarefoundation/autoware_launch/pull/120
- https://github.com/autowarefoundation/autoware_launch/pull/119
> chore(release): update galactic branch

- autoware_launch/rviz/autoware.rviz
Signed-off-by: yutaka <purewater0901@gmail.com>
Add bound visualization
> feat(autoware_launch): add bound visualization

- autoware_launch/CMakeLists.txt
- autoware_launch/config/system/component_state_monitor/topics.yaml
- autoware_launch/config/system/emergency_handler/emergency_handler.param.yaml
- autoware_launch/config/system/mrm_comfortable_stop_operator/mrm_comfortable_stop_operator.param.yaml
- autoware_launch/config/system/mrm_emergency_stop_operator/mrm_emergency_stop_operator.param.yaml
- autoware_launch/config/system/system_error_monitor/diagnostic_aggregator/vehicle.param.yaml
- autoware_launch/config/system/system_error_monitor/system_error_monitor.param.yaml
- autoware_launch/config/system/system_error_monitor/system_error_monitor.planning_simulation.param.yaml
- autoware_launch/config/system/system_monitor/cpu_monitor.param.yaml
- autoware_launch/config/system/system_monitor/gpu_monitor.param.yaml
- autoware_launch/config/system/system_monitor/hdd_monitor.param.yaml
- autoware_launch/config/system/system_monitor/mem_monitor.param.yaml
- autoware_launch/config/system/system_monitor/net_monitor.param.yaml
- autoware_launch/config/system/system_monitor/ntp_monitor.param.yaml
- autoware_launch/config/system/system_monitor/process_monitor.param.yaml
- autoware_launch/config/system/system_monitor/voltage_monitor.param.yaml
- autoware_launch/launch/autoware.launch.xml
- autoware_launch/launch/components/tier4_system_component.launch.xml
Move config to autoware_launch.
Two PRs should be merged at the same time.
- https://github.com/autowarefoundation/autoware.universe/pull/2540
- https://github.com/autowarefoundation/autoware_launch/pull/130
https://github.com/autowarefoundation/autoware_launch/issues/66
Please refer to the PR in autoware.universe
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/mai …
> feat(autoware_launch): move config from autoware.universe for system

- autoware_launch/CMakeLists.txt
- autoware_launch/config/localization/crop_box_filter_measurement_range.param.yaml
- autoware_launch/config/localization/localization_error_monitor.param.yaml
- autoware_launch/config/localization/ndt_scan_matcher.param.yaml
- autoware_launch/config/localization/random_downsample_filter.param.yaml
- autoware_launch/config/localization/voxel_grid_filter.param.yaml
- autoware_launch/launch/autoware.launch.xml
- autoware_launch/launch/components/tier4_localization_component.launch.xml
Signed-off-by: kminoda <koji.minoda@tier4.jp>
Move config to autoware_launch.
Two PRs should be merged at the same time.
- https://github.com/autowarefoundation/autoware.universe/pull/2537
- https://github.com/autowarefoundation/autoware_launch/pull/129
https://github.com/autowarefoundation/autoware_launch/issues/66
Please refer to the PR in autoware.universe …
> feat(autoware_launch): move config from autoware.universe for localization

- autoware_launch/CMakeLists.txt
Signed-off-by: kminoda <koji.minoda@tier4.jp>
> fix(autoware_launch): remove unnecessary `config` declaration

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
Signed-off-by: Yukihiro Saito <yukky.saito@gmail.com>
fix for https://github.com/autowarefoundation/autoware.universe/pull/2534
https://github.com/autowarefoundation/autoware.universe/pull/2534#issuecomment-1364616464
> fix: avoidance parameter file

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
Signed-off-by: satoshi-ota <satoshi.ota928@gmail.com>
Please see [here](https://github.com/autowarefoundation/autoware.universe/pull/2612).
> fix(planning_launch): ignore unavoidable objects around the goal

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/blind_spot.param.yaml
Signed-off-by: 1222-takeshi <m.takeshi1995@gmail.com>
Please see https://github.com/autowarefoundation/autoware.universe/pull/2570
> fix(behavior_velocity_planner): fix blind spot over-detection

- autoware_launch/rviz/autoware.rviz
Signed-off-by: Mehmet Dogru <42mehmetdogru42@gmail.com>
Related issue: https://github.com/autowarefoundation/autoware_launch/issues/62
Related PRs:
https://github.com/autowarefoundation/autoware.universe/pull/647
https://github.com/autowarefoundation/autoware_common/pull/120
This PR should be merged after related PRs are merged:
https://github.com/autowarefoundation/autoware.universe/pull/647
https://github.com/autowarefoundation/autoware_common/pull/120 …
> feat: add speed bump debug markers to autoware.rviz

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop_planner.param.yaml
please review with https://github.com/autowarefoundation/autoware.universe/pull/2624
> feat(obstacle_stop_planner): add parameter for voxel_grid

- autoware_launch/config/control/trajectory_follower/lateral/pure_pursuit.param.yaml
Signed-off-by: Berkay Karaman <brkay54@gmail.com>
Currently, `pure_pursuit.param.yaml` file includes old pure_pursuit params. Since some changes in pure_pursuit were made, we need to update param file.
> feat(autoware_launch): update pure_pursuit parameters

- autoware_launch/rviz/autoware.rviz
fix topic name for obstacle_stop_planner debug marker
> fix(rviz): fix topic name for obstacle_stop_planner debug marker

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_over/pull_over.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/2667
> feat(behavior_path_planner): ignore pull over goal near lane start

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_out/pull_out.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/2669
> feat(behavior_path_planner): add option for combining arc pull out paths

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner_tree.xml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner_tree_lane_change_only.xml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner_tree_pull_out.xml
- autoware_launch/launch/autoware.launch.xml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/2666
> refactor(autoware_launch): organize arguments for planning

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
Signed-off-by: Muhammad Zulfaqar Azmi <zulfaqar.azmi@tier4.jp>
This PR is to fix lane change parameters that is in `behavior_path_planner.param.yaml` and `lane_change.param.yaml`. It reflects the latest values.
> fix(lane_change): behavior planning common and lane change param

- autoware_launch/launch/autoware.launch.xml
- autoware_launch/launch/components/tier4_autoware_api_component.launch.xml
Add launch component of autoware api to set the parameters.
> feat(autoware_launch): add tier4 autoware api component

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop_planner.param.yaml
Signed-off-by: satoshi-ota <satoshi.ota928@gmail.com>
rename hunting_* -> chattering_*
https://github.com/autowarefoundation/autoware.universe/pull/2647
> fix(obstacle_stop_planner): rename param for obstacle stop planner

- autoware_launch/rviz/autoware.rviz
In https://github.com/autowarefoundation/autoware.universe/pull/2602 publish modified_goal as PoseWithUuidStamped, so change rviz config.
> feat(autoware_launch): visualize modified_goal as PoseWithUuidStamped

- autoware_launch/config/control/lane_departure_checker/lane_departure_checker.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/2712
> feat(control_launch): add min_braking_distance to lane_departure_checker

- .pre-commit-config.yaml
Signed-off-by: Tomohito Ando <tomohito.ando@tier4.jp>
See https://github.com/autowarefoundation/autoware.universe/pull/2777
> ci(pre-commit-config): upgrade isort version

- autoware_launch/launch/autoware.launch.xml
- autoware_launch/launch/components/tier4_control_component.launch.xml
- autoware_launch/launch/e2e_simulator.launch.xml
- autoware_launch/launch/logging_simulator.launch.xml
- autoware_launch/launch/planning_simulator.launch.xml
clean up autoware.launch.xml regarding tier4_control_component
> fix(autoware_launch): minor change with tier4_control_component

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/occlusion_spot.param.yaml
- lower deceleration limit
- weaker unknown threshold
- smaller detection area
> fix(autoware_launch): change behavior_velocity parameters

- autoware_launch/config/control/trajectory_follower/lateral/mpc.param.yaml
- autoware_launch/config/control/trajectory_follower/longitudinal/pid.param.yaml
Removed unnecessary parameters which are not used.
> chore(autoware_launch): minor fix with trajectory_follower param

- autoware_launch/config/control/trajectory_follower/lateral/mpc.param.yaml
- autoware_launch/config/control/trajectory_follower/longitudinal/pid.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
- Removed unnecessary parameters
- Applied tier4's parameter which is well-tested.
> chore(autoware_launch): minor parameter change for planning and control

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
for https://github.com/autowarefoundation/autoware.universe/pull/2831
> feat(autoware_launch): add option to disable path update during avoidance

- autoware_launch/config/map/lanelet2_map_loader.param.yaml
- autoware_launch/launch/components/tier4_map_component.launch.xml
This PR aims to provide the ability to change lanelet2 map configurations from within autoware_launch.
At the same time, the following PR has been created in order to make changes to the config file in autoware.universe. Before this PR is merged, the PR in autoware.universe must be merged for the changes here to take effect.
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/2670 …
> chore: add lanelet2 map config

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/drivable_area_expansion.param.yaml
Add parameters for the feature added by https://github.com/autowarefoundation/autoware.universe/pull/2609
> feat(behavior_path_planner): expand the drivable area based on the vehicle footprint

- autoware_launch/launch/autoware.launch.xml
- autoware_launch/launch/components/tier4_localization_component.launch.xml
- autoware_launch/launch/components/tier4_map_component.launch.xml
- autoware_launch/launch/components/tier4_perception_component.launch.xml
- autoware_launch/launch/components/tier4_sensing_component.launch.xml
- autoware_launch/launch/components/tier4_system_component.launch.xml
clean up autoware.launch.xml regarding component launch call.
- planning: https://github.com/autowarefoundation/autoware_launch/pull/185
- control: https://github.com/autowarefoundation/autoware_launch/pull/186
> refactor(autoware_launch): clean up component launch

- autoware_launch/config/localization/ndt_scan_matcher.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner_tree_with_external_request_LC.xml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
- autoware_launch/launch/autoware.launch.xml
- autoware_launch/launch/components/tier4_perception_component.launch.xml
- autoware_launch/launch/components/tier4_system_component.launch.xml
- autoware_launch/package.xml
picked some changes from https://github.com/tier4/autoware_launch
> fix(autoware_launch): unify with tier4 launch

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/rtc_auto_mode_manager/rtc_auto_mode_manager.param.yaml
- autoware_launch/rviz/autoware.rviz
Updated rviz and rtc config for planning (mainly regarding lane_change)
> feat(autoware_launch): update rviz and rtc config for planning

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/run_out.param.yaml
Signed-off-by: Tomohito Ando <tomohito.ando@tier4.jp>
Update parameter for this PR
- https://github.com/autowarefoundation/autoware.universe/pull/2864
> chore(run_out): update parameter for mandatory detection area

- autoware_launch/config/control/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml
Parameter changes for https://github.com/autowarefoundation/autoware.universe/pull/2717
> feat(vehicle_cmd_gate): enable filter with actual steer in manual mode

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop_planner.param.yaml
Parameter changes for [#2558](https://github.com/autowarefoundation/autoware.universe/pull/2558)
> feat(osbtacle_stop_planner): add new trajectory checker parameter

- autoware_launch/config/planning/mission_planning/mission_planner/mission_planner.param.yaml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
This PR adds config parameter file to mission_planner package
Releated Link: https://github.com/autowarefoundation/autoware.universe/pull/2603
> feat(mission_planner): add config param file for mission_planner package

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop_planner.param.yaml
config update for https://github.com/autowarefoundation/autoware.universe/pull/2953
> feat(obstacle_stop_planner): add margin behind goal

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
add new param for avoidance logic
- https://github.com/autowarefoundation/autoware.universe/pull/2938
> feat(avoidance): add new param for avoidance target object filtering logic

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/2796
> feat(autoware_launch): update obstacle avoidance planner parameter

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_over/pull_over.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/2879
https://github.com/autowarefoundation/autoware.universe/pull/2879
> feat(behavior_path_planner): pull over freespace parking

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/3003
> feat(pull_out): add config for new framework

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
support new framework
https://github.com/autowarefoundation/autoware.universe/pull/2997
> feat(side_shift): add config for new framework

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/3016
> feat(lane_change): add config for new framework

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/3005
> feat(pull_over): support new framework

- autoware_launch/launch/components/tier4_simulator_component.launch.xml
- autoware_launch/launch/planning_simulator.launch.xml
merge with this [PR](https://github.com/autowarefoundation/autoware.universe/pull/2514)
delete `launch_planning_evaluator` arg.
launch `planning_evaluator` always from `planning.launch`
> feat(planning_evaluator): delete_launch_planning_evaluator_arg

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_over/pull_over.param.yaml
> fix(pull_over): add params

- autoware_launch/launch/autoware.launch.xml
Autoware doesn't work following tutorial because the following PR changes the default mode of perception .
https://github.com/autowarefoundation/autoware_launch/commit/0244031843d9128ac55e0a8c82b9509ce9a6d8df#diff-50750b08f3020bc2dd51ea26edb44963eac70e078996276ec18859efa308a18bR37
https://github.com/autowarefoundation/autoware_launch/commit/0244031843d9128ac55e0a8c82b9509ce9a6d8df#diff-3616b502976fd74ee4740e4136178f8a75a1142fd5a290438cc9e7fa7053e04fL4 …
> fix(autoware_launch): perception mode

- autoware_launch/rviz/autoware.rviz
> fix(rviz): fix lane change topic name

- autoware_launch/config/perception/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml
This update parameter for https://github.com/autowarefoundation/autoware.universe/pull/3106#
> chore(ground_segmentation): add optional param

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/stop_line.param.yaml
add missiong stop line parameter
> feat(autoware_launch): add missing stop line parameter

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/3086
> feat(autoware_launch): consider behavior's drivable area violation

- autoware_launch/config/perception/object_recognition/detection/pointcloud_map_filter.param.yaml
This PR to add parameters for dynamic map loading options in updated voxel_based_compare_map_filter at [PR#3087](https://github.com/autowarefoundation/autoware.universe/pull/3087) 
> feat(compare_map_segmentation): add param for dynamic map loading

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
This PR contains following two config update.
1. enable avoidance path safety check & yield maneuver. ([details](https://autowarefoundation.github.io/autoware.universe/main/planning/behavior_path_planner/behavior_path_planner_avoidance_design/))
2. increase safety lateral margin that affects the module judge whether the vehicle should avoid. ([details](https://github.com/autowarefoundation/autoware.universe/pull/3055))
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/ma …
> feat(avoidance): update avoidance param

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/scene_module_manager.param.yaml
- autoware_launch/rviz/autoware.rviz
fix the name of external lane change.
> fix(autoware_launch): fix external lane change name

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/side_shift/side_shift.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/behavior_velocity_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/stop_line.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/virtual_traffic_light.param.yaml
When the default parameters were removed, the missing parts were added.
> refactor(behavior): add default values

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/scene_module_manager.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/3147
> feat(behavior_path_planner): multiple candidate modules can run simultaneously

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/2835
> feat: add option of enable_cog_on_centerline

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
Add a new lateral acceleration when the lane changing velocity is lower than a certain threshold.
> feat(behavior_path_planner): add new lateral acceleration

- autoware_launch/rviz/autoware.rviz
Update debug topic names.
Debug markers are shown in Psim.
> fix(rviz): fix debug marker topic name

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_over/pull_over.param.yaml
launcher update for
https://github.com/autowarefoundation/autoware.universe/pull/3234
https://github.com/autowarefoundation/autoware.universe/pull/3234
> fix(behavior_path_planner): pull over deceleration

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
margin can be set independently for each class
https://github.com/autowarefoundation/autoware.universe/pull/3002
```yaml
pedestrian:
enable: true
envelope_buffer_margin: 0.8
safety_buffer_lateral: 1.0
safety_buffer_longitudinal: 1.0
```
```yaml
bus:
enable: true
envelope_buffer_margin: 0.3
safety_buffer_lateral: 0.7
safety_buffer_longitudinal: 0.0
``` …
> feat(avoidance): margin can be set independently for each class

- autoware_launch/rviz/autoware.rviz
Add `2D Rough Goal Pose` button
The goal modification can be done by [`goal_planner`](https://github.com/autowarefoundation/autoware.universe/issues/3223) which is **under development.**
So if setting rough goal now, the goal will **not** be modified.
https://user-images.githubusercontent.com/39142679/231822100-a9f5f019-5d65-427a-92d4-d34be2c01ac1.mp4
https://github.com/autowarefoundation/autoware.universe/pull/3370
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/ …
> feat(rviz): add rough goal

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/3339
See https://github.com/autowarefoundation/autoware.universe/pull/3339
> feat(obstacle_cruise_planner): implement slow down planner

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_over/pull_over.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/3419
https://github.com/autowarefoundation/autoware.universe/pull/3419
psim
> feat(behavior_path_planner): pull over support road_lane and right_hand_traffic

- autoware_launch/config/perception/object_recognition/detection/pointcloud_map_filter.param.yaml
This update param for [#3277](https://github.com/autowarefoundation/autoware.universe/pull/3277)
> fix: compare map filter param

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/drivable_area_expansion.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_following/lane_following.param.yaml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/3445
https://github.com/autowarefoundation/autoware.universe/pull/3445
> feat(behavior_path_planner): move lane_following_params to behavior path params

- autoware_launch/rviz/autoware.rviz
Visualization of slow down
No behavior change
No behavior change
> feat(autoware_launch): visualization for slow down

- autoware_launch/config/planning/mission_planning/mission_planner/mission_planner.param.yaml
Add a parameter for reroute safety check
> feat(planning_launch): add reroute safety check parameter

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml
launcher for https://github.com/autowarefoundation/autoware.universe/pull/3497
The same as https://github.com/autowarefoundation/autoware.universe/pull/3497
The same as https://github.com/autowarefoundation/autoware.universe/pull/3497
> feat(obstacle_avoidance_planner): replan when forward path shape changes

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/3525
See feature PR
Not applicable
Not applicable
Not applicable
> feat(behavior_velocity_planner::intersection): add parameter for occlusion peeking offset

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
> refactor(planning_launch): remove minimum prepare length

- autoware_launch/config/perception/occupancy_grid_map/laserscan_based_occupancy_grid_map.param.yaml
- autoware_launch/config/perception/occupancy_grid_map/pointcloud_based_occupancy_grid_map.param.yaml
Expand occupancy grid map(OGM) size from 100m to 150m to get better visibility in intersection.
we tested in Lsim with sample_rosbag.
The following table shows the processing times in each module:
| size | OGM creation node | OGM based point cloud filtering node |
|--|--|--|
|100m x 100m | 24.8 ms | 9.38 ms |
|150m x 150m | 25.62 ms | 9.92 ms |
According to this result, this size change will not affect badly in perception module.
- [detailed discussion in TIER IV internal link](https://tier4.atlassian.net/browse/RT1-2246)
- OGM become 1.5 times larger (2.25 times in term of area)
- Computation time will be increased in OGM user node
occlusion detection in intersection is a bit delayed
https://user-images.githubusercontent.com/28677420/234444641-adef527e-3ad5-4776-92e6-a5cbce07e06b.mp4
it …
> feat(autoware_launch): expand ogm size from 100m to 150m

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner_tree.xml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner_tree_lane_change_only.xml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner_tree_pull_out.xml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner_tree_with_external_request_LC.xml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/scene_module_manager.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/rtc_auto_mode_manager/rtc_auto_mode_manager.param.yaml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
- autoware_launch/rviz/autoware.rviz
https://github.com/autowarefoundation/autoware.universe/pull/3501
psim
> refactor(behavior_path_planner): rename pull_over to goal_planner

- autoware_launch/rviz/autoware.rviz
show behavior path virtual wall markers.
Psim
Nothing.
> feat(rviz): add behavior path virtual wall

- autoware_launch/rviz/autoware.rviz
fix typo `Goalplanner` -> `GoalPlanner`
https://github.com/autowarefoundation/autoware_launch/pull/313
psim
no
no
> refactor(rviz): fix typo

- autoware_launch/config/map/lanelet2_map_loader.param.yaml
Update comment in the config file to match with the change in this PR: https://github.com/autowarefoundation/autoware.universe/pull/3492
> fix(lanelet2_map_loader): update comment for available projector type

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml
launcher for https://github.com/autowarefoundation/autoware.universe/pull/3584
Written in https://github.com/autowarefoundation/autoware.universe/pull/3584
Written in https://github.com/autowarefoundation/autoware.universe/pull/3584
> feat(autoware_launch): avoid oncoming vehicles

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml
launcher for https://github.com/autowarefoundation/autoware.universe/pull/3579
Written in https://github.com/autowarefoundation/autoware.universe/pull/3579
Nothing
> feat(autoware_launch): add min_drivable_width

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
- add parameters
- https://github.com/autowarefoundation/autoware.universe/pull/3624
> refactor(avoidance): remove hard code params in shift line triming process

- autoware_launch/rviz/autoware.rviz
visualize hatched road markings area in LL2.
Discussion for introducing hatched road markings area.
https://github.com/orgs/autowarefoundation/discussions/3414
can visualize the area with planning simulator
> chore(autoware_launch): update rviz for hatched road markings

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/path_sampler/path_sampler.param.yaml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
This PR adds the parameter file needed by the new `path_sampler` node.
`autoware.universe` PR: https://github.com/autowarefoundation/autoware.universe/pull/3532
> feat(path_sampler): add parameter file for the `path_sampler` node

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
See https://github.com/autowarefoundation/autoware.universe/pull/3566
See https://github.com/autowarefoundation/autoware.universe/pull/3566
Nothing.
See https://github.com/autowarefoundation/autoware.universe/pull/3566
> feat(autoware_launch): add lane change abort param

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
Add lateral acceleration map to the config file
> feat(planning_launch): add lateral acceleration map

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/scene_module_manager.param.yaml
- increase dynamic avoidance module priority so that dynamic avoidance run with normal avoidance.
Psim
Nothing.
> feat(behavior): increase dynamic avoidance module priority

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
Change lane change sampling number
> feat(planning_launch): change lane change sampling number

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/3763
Psim
> feat(intersection): denoise occlusion by morphology open process

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml
launcher for https://github.com/autowarefoundation/autoware.universe/pull/3743
See https://github.com/autowarefoundation/autoware.universe/pull/3743
See https://github.com/autowarefoundation/autoware.universe/pull/3743
> feat(autoware_launch): add hysteresis for slow down decision

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/3751
See https://github.com/autowarefoundation/autoware.universe/pull/3751
See https://github.com/autowarefoundation/autoware.universe/pull/3751
> feat(autoware_launch): time margin for slow down

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
- https://github.com/autowarefoundation/autoware.universe/pull/3767
Psim
Ignore objects around the crosswalk in avoidance module.
> feat(avoidance): don't avoid objects around crosswalks

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml
launcher for https://github.com/autowarefoundation/autoware.universe/pull/3759
See https://github.com/autowarefoundation/autoware.universe/pull/3759
See https://github.com/autowarefoundation/autoware.universe/pull/3759
> feat(autoware_launch): add time margins for dynamic avoidance

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml
launcher for https://github.com/autowarefoundation/autoware.universe/pull/3744
See https://github.com/autowarefoundation/autoware.universe/pull/3744
See https://github.com/autowarefoundation/autoware.universe/pull/3744
> feat(autoware_launch): remove min_acc in obstacle_cruise_planner for slow down

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml
launcher for https://github.com/autowarefoundation/autoware.universe/pull/3778
See https://github.com/autowarefoundation/autoware.universe/pull/3777
See https://github.com/autowarefoundation/autoware.universe/pull/3777
> feat(autoware_launch): update obstacle_cruise_planner param

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
add the option to use intersection_area
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/3784
refer to https://github.com/autowarefoundation/autoware.universe/pull/3784
> feat(intersection): add the option to use intersection_area

- autoware_launch/config/control/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml
For this PR: https://github.com/autowarefoundation/autoware.universe/pull/3790 we want to add just a parameter in the launch file.
> feat(vehicle_cmd_gate): add moderate_stop_interface parameter

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
Fix lateral distance max threshold
> fix(behavior_path_planner): fix lateral distance max threshold

- autoware_launch/config/planning/mission_planning/mission_planner/mission_planner.param.yaml
Add a minimum reroute length for the safety
> feat(planning_launch): add minimum reroute length

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_out/pull_out.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/3805
psim
not applicable 
not applicable
> feat(pull_out): support pull out normal lane

- autoware_launch/config/control/trajectory_follower/lateral/mpc.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/3810
See https://github.com/autowarefoundation/autoware.universe/pull/3810
See https://github.com/autowarefoundation/autoware.universe/pull/3810
> feat(autoware_launch): dynamic steer rate limit in mpc

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/3848
Psim
Improve FOA operation.
> feat(avoidance): add new parameter

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/3904
See https://github.com/autowarefoundation/autoware.universe/pull/3904
See https://github.com/autowarefoundation/autoware.universe/pull/3904
> feat(autoware_launch): suppress flickering to entry slow down

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/3785
Psim
Nothing.
> feat(avoidance): add option for yield during shifting

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner_tree.xml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner_tree_lane_change_only.xml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner_tree_pull_out.xml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner_tree_with_external_request_LC.xml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/scene_module_manager.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/rtc_auto_mode_manager/rtc_auto_mode_manager.param.yaml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
- autoware_launch/rviz/autoware.rviz
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/3908
https://github.com/autowarefoundation/autoware.universe/pull/3908
psim
topic names change `*pull_over*` -> `*start_planner*`
not applicable
> refactor(start_planner): rename pull out to start planner

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/behavior_velocity_planner.param.yaml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
Update launch and parameter files. See https://github.com/autowarefoundation/autoware.universe/issues/3724 for details.
This PR depends on https://github.com/autowarefoundation/autoware.universe/pull/3811.
Check autonomous driving in planning simulator.
None.
> refactor(behavior_velocity_planner): update launch and parameter files for plugin

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
Add a parameter for turn signal activation
> feat(planning_launch): add a parameter for turn signal activation

- autoware_launch/config/planning/scenario_planning/common/motion_velocity_smoother/motion_velocity_smoother.param.yaml
Parameter update for https://github.com/autowarefoundation/autoware.universe/pull/3948
see https://github.com/autowarefoundation/autoware.universe/pull/3948
see https://github.com/autowarefoundation/autoware.universe/pull/3948
> feat(velocity_smoother): plan from ego velocity on manual mode

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
If setting the goal closer than `object_check_backward_distance` behind the object, the avoidance module can not be finished.
This prevents `goal_module` from running.
https://github.com/autowarefoundation/autoware_launch/assets/39142679/1079cec2-f74b-4843-86e8-cc28b48a68c3
In this PR change the value from 100m to 10m
wip
not applicable
not applicable …
> feat(avoidance): change object_check_backward_distance from 100m to 10m

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
Add a new parameter for tuning the turn signal required end position for the lane change module
> feat(planning_launch): add a turn signal deactivation parameter for lane change

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
- https://github.com/autowarefoundation/autoware.universe/pull/3998
> feat(avoidance): can set stop/move judge threshold for each object class

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
change lateral_acceleration_sampling_num 1->3
https://github.com/autowarefoundation/autoware.universe/pull/4017
psim
none
none
> feat(start_planner): change lateral acceleration sampling num

- autoware_launch/config/control/trajectory_follower/lateral/mpc.param.yaml
For https://github.com/autowarefoundation/autoware.universe/pull/4021
Run Psim
None
> fix(mpc): relax steering rate limit

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
Changed parameter to be less likely to cancel based on the speed of vehicles in adjacent lanes.
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/4039
With real vehicle
> feat(behavior_path_planner): relax longitudinal_velocity_delta_time

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
enable avoidance option for pedestrian, bicycle, motorcycle
> feat(avoidance): avoid non car-like object (pedestrian, bicycle, motorcycle)

- autoware_launch/config/perception/occupancy_grid_map/laserscan_based_occupancy_grid_map.param.yaml
- autoware_launch/config/perception/occupancy_grid_map/pointcloud_based_occupancy_grid_map.param.yaml
Fixed unintended change in #409
#409 
Psim
> chore(probabilistic_occupancy_grid_map): revert map size

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml
launcher for https://github.com/autowarefoundation/autoware.universe/pull/4048
Additional parameter tuning is included as well.
See https://github.com/autowarefoundation/autoware.universe/pull/4048
See https://github.com/autowarefoundation/autoware.universe/pull/4048
> feat(autoware_launch): update dynamic avoidance param

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
Reverts autowarefoundation/autoware_launch#410 because scenario test fails
> revert: "feat(behavior_path_planner): relax longitudinal_velocity_delta_time"

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
- https://github.com/autowarefoundation/autoware.universe/pull/4041
Nothing.
> feat(avoidance): set additional buffer margin independently

- autoware_launch/config/control/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml
Add parameter corresponding to https://github.com/autowarefoundation/autoware.universe/pull/4060
https://github.com/autowarefoundation/autoware.universe/pull/4060
none
none
none
Refer to https://github.com/autowarefoundation/autoware.universe/pull/4060
> feat: use vehicle_stop_checker for judging vehicle stop vehicle_cmd_gate

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
use experimental lane change function
> fix(autoware_launch): use experimental lane change function

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
rename avoidance params.
https://github.com/autowarefoundation/autoware.universe/pull/4088
Nothing.
Nothing.
> refactor(avoidance): rename ununderstandable params

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
For https://github.com/autowarefoundation/autoware.universe/pull/4090
> refactor(lane_change): add namespace for lane-change-cancel

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
for https://github.com/autowarefoundation/autoware.universe/pull/4083
> feat(lane_change): add param for a lateral distance margin where the abort can be performed

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
update for https://github.com/autowarefoundation/autoware.universe/pull/4151
psim
none
none
> feat(start_planner): add option for lane departure

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
increase object ignore section for traffic jam.
Psim & Real Vehicle
Improve avoidance target filtering behavior.
> feat(avoidance): extend object ignore section

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
Add new parameters for https://github.com/autowarefoundation/autoware.universe/pull/4141.
Improve avoidance behavior
> feat(avoidance): insert slow down speed

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
should be merged before: [3947]( https://github.com/autowarefoundation/autoware.universe/pull/3947)
> feat(autoware_launch): add intersection param for wrong direction vehicles

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml
launcher for https://github.com/autowarefoundation/autoware.universe/pull/4137
See https://github.com/autowarefoundation/autoware.universe/pull/4137
See https://github.com/autowarefoundation/autoware.universe/pull/4137
> feat(autoware_launch): add min_obj_lat_offset_to_ego_path in dynamic_avoidance

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
The current waiting time of the force avoidance seems too long.
This PR shortens that waiting time.
Test with XX1.
> feat(behavior_path_planner): shorten the wating time of force avoidance

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
- https://github.com/autowarefoundation/autoware.universe/pull/4206
Nothing.
> feat(avoidance): use intersection areas

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
- https://github.com/autowarefoundation/autoware.universe/pull/4186
Make it possible to accelerate during avoidance maneuver.
> feat(avoidance): consider acceleration during avoidance maneuver

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
Enable to use `intersection area` for avodiance behavior.
Nothing.
> feat(avoidance): enable to use intersection area

- autoware_launch/rviz/autoware.rviz
Update lane change rviz configuration
> feat(autoware_launch): update lane change rviz configuration

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/walkway.param.yaml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4315
See https://github.com/autowarefoundation/autoware.universe/pull/4315
See https://github.com/autowarefoundation/autoware.universe/pull/4315
> refactor(autoware_launch): add walkway param yaml

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/walkway.param.yaml
launcher for https://github.com/autowarefoundation/autoware.universe/pull/4317
See https://github.com/autowarefoundation/autoware.universe/pull/4317
See https://github.com/autowarefoundation/autoware.universe/pull/4317
> refactor(autoware_launch): rename crosswalk/walkway parameters

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
update config to prevent unconfortable deceleration
prevent unconfortable deceleration
> fix(avoidance): update config to prevent unconfortable deceleration

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/4298.
> feat(avoidance): flexible avoidance path generation

- autoware_launch/rviz/autoware.rviz
Rename pull over to goal planner
https://github.com/autowarefoundation/autoware.universe/pull/3501
Not applicable. (Changes in Rviz drawing only)
> fix(autoware_launch): rename pull over to goal planner

- autoware_launch/config/perception/object_recognition/detection/lidar_model/pointpainting.param.yaml
This PR shuold be merged after <https://github.com/autowarefoundation/autoware.universe/pull/4314>.
update pointpainting params from <https://github.com/autowarefoundation/autoware.universe/pull/4314> following <https://github.com/autowarefoundation/autoware_launch/pull/450>
> feat(autoware_launch): update pointpainting param

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/stop_line.param.yaml
Rename and remove parameters to clean code.
> refactor(planning_launch): clean stop line parameters

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
- https://github.com/autowarefoundation/autoware.universe/pull/4388
Evaluator
Nothing.
> refactor(avoidance): use common safety checker

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/path_smoother/elastic_band_smoother.param.yaml
Add parameters for the `ReplanChecker` added to the `path_smoother` with PR https://github.com/autowarefoundation/autoware.universe/pull/4416
Psim
None
> feat(path_smoother): add parameters for the replan checker

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4390
See https://github.com/autowarefoundation/autoware.universe/pull/4390
See https://github.com/autowarefoundation/autoware.universe/pull/4390
> feat(autoware_launch): add enable_debug_info for dynamic_avoidance

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4449
See https://github.com/autowarefoundation/autoware.universe/pull/4449
See https://github.com/autowarefoundation/autoware.universe/pull/4449
> feat(autoware_launch): add acc/jerk parameters for stuck vehicle detection in crosswalk

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/4466
Psim and experiment
> feat(intersection_occlusion): ignore occlusion behind parked vehicles on the attention lane

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4465
See https://github.com/autowarefoundation/autoware.universe/pull/4465
See https://github.com/autowarefoundation/autoware.universe/pull/4465
> feat(autoware_launch): add option of disable_yield_for_new_stopped_object in crosswalk

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4471
See https://github.com/autowarefoundation/autoware.universe/pull/4471
See https://github.com/autowarefoundation/autoware.universe/pull/4471
> feat(autoware_launch): add chattering suppression margin in crosswalk

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4492
See https://github.com/autowarefoundation/autoware.universe/pull/4492
See https://github.com/autowarefoundation/autoware.universe/pull/4492
> feat(autoware_launch): add pass juge line parameter in crosswalk

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4494
See https://github.com/autowarefoundation/autoware.universe/pull/4494
See https://github.com/autowarefoundation/autoware.universe/pull/4494
> feat(autoware_launch): add gradable pass margin in crosswalk

- autoware_launch/config/perception/object_recognition/detection/object_merger/overlapped_judge.param.yaml
- Update object_merger package GIoU paramter for [PR#4499](https://github.com/autowarefoundation/autoware.universe/pull/4499)
> fix(object_merger): separate GIoU

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/4514
psim
none
none
> feat(start_planner): use stop objects in pull out lanes for collision check

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4433
See https://github.com/autowarefoundation/autoware.universe/pull/4433
See https://github.com/autowarefoundation/autoware.universe/pull/4433
> feat(autoware_launch): add successive_num_to_exit_dynamic_avoidance_condition in dynamic_avoidance

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
Remove an unused parameter from the lane change config file
> feat(lane_change): remove an unused parameter

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4527
See https://github.com/autowarefoundation/autoware.universe/pull/4527
See https://github.com/autowarefoundation/autoware.universe/pull/4527
> feat(autoware_launch): add cut out parameters for dynamic avoidance

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4548
See https://github.com/autowarefoundation/autoware.universe/pull/4548
See https://github.com/autowarefoundation/autoware.universe/pull/4548
> feat(autoware_launch): update dynamic_avoidance parameters

- autoware_launch/config/perception/object_recognition/detection/lidar_model/pointpainting.param.yaml
update pointpainting params.
<https://github.com/autowarefoundation/autoware.universe/pull/4544>
please see the related links above.
> feat(tier4_perception_launch): update pointpainting param

- autoware_launch/config/map/lanelet2_map_loader.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/3986
See https://github.com/autowarefoundation/autoware.universe/pull/3986
See https://github.com/autowarefoundation/autoware.universe/pull/3986
See https://github.com/autowarefoundation/autoware.universe/pull/3986
See https://github.com/autowarefoundation/autoware.universe/pull/3986
See https://github.com/autowarefoundation/autoware.universe/pull/3986
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/ …
> feat(map_projection_loader): add map_projection_loader

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/4536
Nothing.
> feat(avoidance): make it selectable avoidance policy

- autoware_launch/config/control/lane_departure_checker/lane_departure_checker.param.yaml
parameter change for this [PR](https://github.com/autowarefoundation/autoware.universe/pull/4607)
> feat(lane_departure_checker): add road_border departure checker

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4608
See https://github.com/autowarefoundation/autoware.universe/pull/4608
See https://github.com/autowarefoundation/autoware.universe/pull/4608
> feat(autoware_launch): add enable_pub_extra_debug_marker in obstacle_avoidance_planner

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
- https://github.com/autowarefoundation/autoware.universe/pull/4609
Nothing.
Nothing.
> feat(avoidance): reduce road shoulder margin if lateral distance is not enough to avoid

- autoware_launch/config/localization/ekf_localizer.param.yaml
Fix True to true
https://github.com/autowarefoundation/autoware.universe/pull/4659
N/A
N/A
N/A
N/A
> fix(ekf_localizer): fix parameter first capital letter

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/4610
psim
none
none
none
> feat(start_planner): support freespace pull out

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
Declare a separate parameter for stop_line_margin of merge_from_private
Psim
> feat(merge_from_private): use separate param

- autoware_launch/launch/autoware.launch.xml
- autoware_launch/launch/planning_simulator.launch.xml
rviz often dies so add respawn options
(We need to fix rviz_pulgin)
psim
none
none
> feat(rviz): respawn rviz

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/4674
psim
none
none
none
> feat(goal_planner): add extra front margin for collision check considering stopping distance

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/4719
Evaluator
Nothing.
> refactor(safety_check): use safety check common param struct

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4720
See https://github.com/autowarefoundation/autoware.universe/pull/4720
See https://github.com/autowarefoundation/autoware.universe/pull/4720
> feat(autoware_launch): add hold stop threshold in obstacle_cruise_planner

- autoware_launch/config/planning/scenario_planning/common/motion_velocity_smoother/JerkFiltered.param.yaml
update smoother jerk weight to the previous value.
https://github.com/autowarefoundation/autoware.universe/pull/4740
Nothing.
> fix(smoother): fix smoother jerk weight params

- autoware_launch/config/perception/object_recognition/prediction/map_based_prediction.param.yaml
Update prediction yaml parameter file to follow following universe PR.
- related PR
- https://github.com/autowarefoundation/autoware.universe/pull/4756
Tested in Psim.
None.
> refactor(map_based_prediction): update prediction yaml file

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/4735
Nothing.
> feat(avoidance): add time series hysteresis

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/4754
Evaluator
Nothing.
> feat(avoidance): flexible avoidance safety check param

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4758
See https://github.com/autowarefoundation/autoware.universe/pull/4758
See https://github.com/autowarefoundation/autoware.universe/pull/4758
> feat(autoware_launch): add min_longitudinal_polygon_margin and use object_path_base in dynamic_avoidance

- autoware_launch/config/perception/object_recognition/prediction/map_based_prediction.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4800
See https://github.com/autowarefoundation/autoware.universe/pull/4800
See https://github.com/autowarefoundation/autoware.universe/pull/4800
> feat(autoware_launch): add max_crosswalk_user_delta_yaw_threshold_for_lanelet in map_based_prediction

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4802
See https://github.com/autowarefoundation/autoware.universe/pull/4802
See https://github.com/autowarefoundation/autoware.universe/pull/4802
> feat(autoware_launch): add no stop decision parameters in crosswalk

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/4788
Psim
> feat(intersection): suppress intersection occlusion chattering

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4813
See https://github.com/autowarefoundation/autoware.universe/pull/4813
See https://github.com/autowarefoundation/autoware.universe/pull/4813
> feat(autoware_launch): remove polygon_generation_method from dynamic_avoidance

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/scene_module_manager.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/4811
Evaluator
Nothing.
> feat(interface): add new option `keep_last`

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/4889
> feat(goal_planner): set ignore_distance_from_lane_start 0.0

- autoware_launch/config/control/lane_departure_checker/lane_departure_checker.param.yaml
Change for the [PR](https://github.com/autowarefoundation/autoware.universe/pull/4861) in autowarefoundation/autoware.universe
> feat(lane_departure_checker): add border types to check

- autoware_launch/config/localization/ndt_scan_matcher.param.yaml
add a param in ndt_scan_matcher.param.yaml.
see https://github.com/autowarefoundation/autoware.universe/pull/4815
https://github.com/autowarefoundation/autoware.universe/pull/4815
see https://github.com/autowarefoundation/autoware.universe/pull/4815
None
see https://github.com/autowarefoundation/autoware.universe/pull/4815
see https://github.com/autowarefoundation/autoware.universe/pull/4815
[pull …
> feat(ndt_scan_matcher): add param lidar_topic_timeout_sec

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4952
See https://github.com/autowarefoundation/autoware.universe/pull/4952
See https://github.com/autowarefoundation/autoware.universe/pull/4952
> feat(autoware_launch): add approaching stop on curve in obstacle cruise planner

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/4968
psim
none
none
> feat(goal_planner): use only static objects in pull over lanes to path generation

- autoware_launch/config/localization/localization_error_monitor.param.yaml
Update default parameter, as the logging simulator tutorial outputs warning, which indicates that the threshold are not correctly set.
Confirmed that there is no warning
Not applicable
> chore(localization_error_monitor): update default parameter

- autoware_launch/rviz/autoware.rviz
See https://github.com/autowarefoundation/autoware.universe/pull/4945
See https://github.com/autowarefoundation/autoware.universe/pull/4945
See https://github.com/autowarefoundation/autoware.universe/pull/4945
> feat(tier4_system_rviz_plugin): add package

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/4970
> feat(goal_planner): add options of occupancy grid map to use only for goal search

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
should be merged with [PR](https://github.com/autowarefoundation/autoware.universe/pull/5014)
> feat(behavior_path_planner): update start_goal_planner's parameter

- autoware_launch/config/localization/ekf_localizer.param.yaml
see https://github.com/autowarefoundation/autoware.universe/pull/4914
https://github.com/autowarefoundation/autoware.universe/pull/4914
see https://github.com/autowarefoundation/autoware.universe/pull/4914
see https://github.com/autowarefoundation/autoware.universe/pull/4914
see https://github.com/autowarefoundation/autoware.universe/pull/4914
see https://github.com/autowarefoundation/autoware.universe/pull/4914
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/cont …
> feat(ekf_lolicazer): add diagnostics parameters

- autoware_launch/config/control/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml
parameter change for https://github.com/autowarefoundation/autoware.universe/pull/5044
see https://github.com/autowarefoundation/autoware.universe/pull/5044
see https://github.com/autowarefoundation/autoware.universe/pull/5044
> feat(vehicle_cmd_gate): add steering angle and rate filter

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/5068
New parameters added.
Using default parameters, no effects.
If change regulatory parameters, you can regulate lane change on crosswalk and intersection.
> feat(planning_launch): add config for regulate lane change

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/5085
psim
none
none
> fix(start/goal_planner): resample path and make params

- autoware_launch/config/planning/scenario_planning/common/motion_velocity_smoother/motion_velocity_smoother.param.yaml
For https://github.com/autowarefoundation/autoware.universe/pull/5064
see https://github.com/autowarefoundation/autoware.universe/pull/5064
see https://github.com/autowarefoundation/autoware.universe/pull/5064
> chore(motion_velocity_smoother): add enable curve filtering param

- autoware_launch/config/planning/mission_planning/mission_planner/mission_planner.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/5097
See https://github.com/autowarefoundation/autoware.universe/pull/5097
See https://github.com/autowarefoundation/autoware.universe/pull/5097
> feat(autoware_launch): add check_footprint_inside_lanes in mission_planner

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/5086
See https://github.com/autowarefoundation/autoware.universe/pull/5086
See https://github.com/autowarefoundation/autoware.universe/pull/5086
> feat(autoware_launch): add stop_distance_threshold in merge_from_private

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/5096
See https://github.com/autowarefoundation/autoware.universe/pull/5096
See https://github.com/autowarefoundation/autoware.universe/pull/5096
> feat(autoware_launch): add traffic protected level for amber color in intersection

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/5047
Psim
none
none
> feat(intersection): ensure-temporal-stop-before-upcoming-lane

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/5105
See https://github.com/autowarefoundation/autoware.universe/pull/5105
See https://github.com/autowarefoundation/autoware.universe/pull/5105
See https://github.com/autowarefoundation/autoware.universe/pull/5105
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelin …
> feat(lane_change): enable lane change in crosswalk/intersection if ego vehicle gets stuck

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/5142
See https://github.com/autowarefoundation/autoware.universe/pull/5142
See https://github.com/autowarefoundation/autoware.universe/pull/5142
> feat(autoware_launch): add max_obstacle_vel in dynamic_avoidance

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
update goal search area params
2023/09/25 https://evaluation.tier4.jp/evaluation/reports/3c8b3aa2-d3a3-5412-87e1-9bfd721c08cf/?project_id=prd_jt
2023/09/27 https://evaluation.tier4.jp/evaluation/reports/35e3a876-0801-5b60-a61f-dd612ee2a0ef/?project_id=prd_jt
2023/09/27 https://evaluation.tier4.jp/evaluation/reports/6efed89a-0fa8-5622-a5e7-42e117673e86?project_id=prd_jt
[pull request …
> feat(goal_planner): extend goal search area

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
the length is calculated from the current velocity and deceleration/jerk constraints
2023/09/27 https://evaluation.tier4.jp/evaluation/reports/3863c542-3370-5069-a542-dda67d6662e4/?project_id=prd_jt
> feat(goal_planner): change minimum_request_length 0.0

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
as in title
2023/09/27 https://evaluation.tier4.jp/evaluation/reports/ee1f698c-bc22-5110-9cd6-e09c7d8ba85f/?project_id=prd_jt
> feat(start_planner): change th_distance_to_middle_of_the_road 0.5

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/5137
psim
none
none
> feat(goal_planner): prioritize goals before objects to avoid

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/5188
See https://github.com/autowarefoundation/autoware.universe/pull/5188
See https://github.com/autowarefoundation/autoware.universe/pull/5188
> feat(autoware_launch): dynamic timeout for no intention to walk decision in crosswalk

- autoware_launch/config/perception/object_recognition/detection/detected_object_validation/obstacle_pointcloud_based_validator.param.yaml
- autoware_launch/launch/components/tier4_perception_component.launch.xml
This PR add param file for [#5177](https://github.com/autowarefoundation/autoware.universe/pull/5177) and should merge together with those PR.
> fix: add param file for obstacle pointcloud based validator

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/5217
Evaluator
> refactor(avoidance): use safety check parameter struct

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/5277
none.
none.
-  [X] The PR follows the [pull request guidelines].
> chore(intersection): parameterize stuck vehicle detection turn_direction

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/5270
See https://github.com/autowarefoundation/autoware.universe/pull/5270
See https://github.com/autowarefoundation/autoware.universe/pull/5270
> feat(autoware_launch): add yield_stuck.distance_thr in intersection

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/5304
Psim
none.
none.
> feat(intersection): ignore decelerating vehicle on amber traffic light

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
launcher update for
https://github.com/autowarefoundation/autoware.universe/pull/5300
none
none
> feat(lane_change): add rss paramas for stuck

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/drivable_area_expansion.param.yaml
Update parameters for https://github.com/autowarefoundation/autoware.universe/pull/5294
Psim.
Evaluation platform ([TIER IV INTERNAL LINK](https://evaluation.tier4.jp/evaluation/reports/fe916395-fa5c-5497-a3e4-612d519cb149?project_id=x2_dev)).
> feat(behavior_path_planner): curvature based drivable area expansion

- autoware_launch/launch/components/tier4_simulator_component.launch.xml
Added arguments to simulator.launch.xml to configure the tracking module for different sensor setups and scenarios. This allows tuning the object recognition performance in the simulation environment.
- https://github.com/autowarefoundation/autoware.universe/pull/5326
Psim
Nothing.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guide …
> fix(tier4_simulator_component): add lacked param path

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/5353
see https://github.com/autowarefoundation/autoware.universe/pull/5353
none.
none.
> feat(intersection): timeout static occlusion with traffic light

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
universe PR: https://github.com/autowarefoundation/autoware.universe/pull/5370
none.
none.
> feat(intersection): use own max acc/jerk param

- autoware_launch/config/system/duplicated_node_checker/duplicated_node_checker.param.yaml
necesary change for the [PR](https://github.com/autowarefoundation/autoware.universe/pull/5382)
run scenario_simulator_v2
> feat(duplicated_node_checker): add duplicated node names to msg

- autoware_launch/rviz/autoware.rviz
To easily visualize, add a sensing/perception debug topic to RViz.
* add the outputs of each algorithm with different colors
* color is decided based on [2014 Material Design color palettes](https://m2.material.io/design/color/the-color-system.html#tools-for-picking-colors)
* concatenated pointcloud topic
* pointcloud on image topic …
> feat(rviz): add sensing/perception debug topics

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/5394
see https://github.com/autowarefoundation/autoware.universe/pull/5394
none.
none.
> feat(intersection): check path margin for overshoot vehicles on red light

- autoware_launch/config/control/autonomous_emergency_braking/autonomous_emergency_braking.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/5413
https://github.com/autowarefoundation/autoware.universe/pull/5413
see https://github.com/autowarefoundation/autoware.universe/pull/5413
see https://github.com/autowarefoundation/autoware.universe/pull/5413
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request- …
> feat(AEB): implement parameterized prediction time horizon and interval

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/5436
Evaluator
Nothing.
> feat(behavior_path_planner): add traffic light recognition timeout threshold

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
add debug option
https://github.com/autowarefoundation/autoware.universe/pull/5432
> feat(intersection): add ttc debug plotter

- autoware_launch/config/control/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/5426
https://github.com/autowarefoundation/autoware.universe/pull/5426
see https://github.com/autowarefoundation/autoware.universe/pull/5426
none
none
> feat(vehicle_cmd_gate): improve debug marker activation

- autoware_launch/launch/components/tier4_planning_component.launch.xml
See https://github.com/autowarefoundation/autoware.universe/pull/5448.
Evaluator
Nothing.
> refactor(planning): update args name

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
> chore(goal_planner): fix typo

- autoware_launch/config/localization/ekf_localizer.param.yaml
- autoware_launch/config/system/system_error_monitor/system_error_monitor.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/5467
See https://github.com/autowarefoundation/autoware.universe/pull/5467
See https://github.com/autowarefoundation/autoware.universe/pull/5467
> feat(ekf_localizer, system_error_monitor): system_error_monitor handles ekf diags

- autoware_launch/config/planning/scenario_planning/common/costmap_generator.param.yaml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
See https://github.com/autowarefoundation/autoware.universe/pull/5502.
Evaluator.
Nothing.
> chore(tier4_planning_launch): add costmap generator config

- autoware_launch/config/perception/object_recognition/detection/detection_by_tracker/detection_by_tracker.param.yaml
- autoware_launch/launch/components/tier4_perception_component.launch.xml
This PR to add param file for https://github.com/autowarefoundation/autoware.universe/pull/5473
> fix(perception): add detection_by_tracker param file

- autoware_launch/config/system/system_error_monitor/system_error_monitor.planning_simulation.param.yaml
disabled by this [PR](https://github.com/autowarefoundation/autoware_launch/pull/649)
deggresion is solved by this [PR](https://github.com/tier4/scenario_simulator_v2/pull/1126)
so enable feature in this PR
confirmed in the [evaluator](https://evaluation.tier4.jp/evaluation/reports/2ac0aba6-a60d-5311-a8c1-bfce67d61b7a?project_id=prd_jt) …
> feat(duplicated_node_checker): enable duplicated_node_checker in simulation

- autoware_launch/config/perception/object_recognition/detection/detected_object_validation/obstacle_pointcloud_based_validator.param.yaml
This to add parameter for https://github.com/autowarefoundation/autoware.universe/pull/5327 and should be merged together.
> fix(detected_object_validation): add param

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/5572.
> fix(avoidance): prevent sudden steering at yield maneuver

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
for https://github.com/autowarefoundation/autoware.universe/pull/5662
> feat(goal_planner): add time hysteresis to keep unsafe

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/5387.
Evaluator
> feat(avoidance): add new parameter for target object filtering

- autoware_launch/config/perception/object_recognition/prediction/map_based_prediction.param.yaml
Adds parameter for https://github.com/autowarefoundation/autoware.universe/pull/5669
> feat(map_based_prediction): consider only routable neighbours for lane change

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
enable safety check.
psim
tested with https://github.com/autowarefoundation/autoware.universe/pull/5677
evaluator_description: feat/safer_safety_check_gp
2023/11/26 https://evaluation.tier4.jp/evaluation/reports/ddff9b07-ecd0-5013-9ea1-b25cd1c18ff1/?project_id=prd_jt
none
none
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines …
> feat(goal_planenr): enable safety check

- autoware_launch/config/control/trajectory_follower/longitudinal/pid.param.yaml
These changes are necessary for https://github.com/autowarefoundation/autoware.universe/pull/5549
> feat(pid_longitudinal_controller): error integration on vehicle takeoff

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/5685
See https://github.com/autowarefoundation/autoware.universe/pull/5685
See https://github.com/autowarefoundation/autoware.universe/pull/5685
> feat: add several min_object_vel in dynamic_avoidance

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/5722.
Evaluator.
Change crosswalk module behavior for stuck vehicle.
> fix(crosswalk): don't stop in front of the crosswalk if vehicle stuck in intersection

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml
remove unused params corresponds to https://github.com/autowarefoundation/autoware.universe/pull/5619
universe PR: https://github.com/autowarefoundation/autoware.universe/pull/5738
psim tests was perfomed.
> chore(obstacle_cruise)!: remove unused params

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
change for the [PR](https://github.com/autowarefoundation/autoware.universe/pull/5747)
> refactor(start_planner): refactor debug and safety check logic

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml
Launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/5726
See https://github.com/autowarefoundation/autoware.universe/pull/5726
See https://github.com/autowarefoundation/autoware.universe/pull/5726
> feat: add polygon_generation_method in dynamic_avoidance

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
change for the [PR](https://github.com/autowarefoundation/autoware.universe/pull/5782)
update start_planner.param.yaml 
> feat(start_planner): add surround moving obstacle check

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
sync with https://github.com/autowarefoundation/autoware.universe/pull/5813
> chore(crosswalk): sync a config file to the univese one

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
fix inappropriate sync in https://github.com/autowarefoundation/autoware_launch/pull/729
> fix(crosswalk): fix inappropriate sync

- autoware_launch/launch/components/tier4_localization_component.launch.xml
rename lidar topic.
`/sensing/lidar/<lidar name>/outlier_filtered/pointcloud` --> `/sensing/lidar/<lidar name>/pointcloud`
**Merge all Related PRs at the same time.**
https://github.com/autowarefoundation/autoware-documentation/pull/491
https://github.com/autowarefoundation/autoware.universe/pull/5781
https://github.com/autowarefoundation/sample_sensor_kit_launch/pull/82
https://github.com/autowarefoundation/autoware_launch/pull/722
https://github.com/RobotecAI/awsim_sensor_kit_launch/pull/12
https://github.com/autowarefoundation/awf_reference_sensor_kit_launch/pull/7
The PR author **must** check the checkboxes below …
> refactor(localization_component_launch): rename lidar topic

- autoware_launch/rviz/autoware.rviz
Add objects of interest marker in rviz.
https://github.com/autowarefoundation/autoware.universe/pull/5695
https://github.com/autowarefoundation/autoware.universe/pull/5875
Can be shown objects of interest marker
> feat(rviz_config): add objects of interest marker

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
feature PR for https://github.com/autowarefoundation/autoware.universe/pull/5849
see https://github.com/autowarefoundation/autoware.universe/pull/5849
none.
none.
> feat(crosswalk): ignore predicted path going across the crosswalk

- autoware_launch/config/planning/preset/default_preset.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/5889
See https://github.com/autowarefoundation/autoware.universe/pull/5889
See https://github.com/autowarefoundation/autoware.universe/pull/5889
> refactor(autoware_launch): remove use_experimental_lane_change_function

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/5883
see https://github.com/autowarefoundation/autoware.universe/pull/5883
none.
none.
> fix(intersection): generate yield stuck detect area from multiple lanes

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/run_out.param.yaml
New parameter regarding to a new feature is added.
https://github.com/autowarefoundation/autoware.universe/pull/5862
see the PR in universe
> feat(run_out)!: ignore the collision points on crosswalk

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
tune remaining buffer in avoidance module.
Related PR: (TIERIV Internal Link) https://github.com/tier4/autoware_launch.xx1/pull/711
Psim & Taxi vehicle
Nothing.
> fix(avoidance): shorten the parameter

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/5910
see https://github.com/autowarefoundation/autoware.universe/pull/5910
none.
none.
> feat(intersection): disable stuck detection against private lane

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/5922
Psim
Nothing.
> feat(avoidance): enable avoidance for objects that stop longer time than thresh

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
This reverts commit 024254c82f2687deddfadba716afe0f2b8a3a03c.
> revert: "fix(avoidance): shorten the parameter (#745)"

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/5947
See https://github.com/autowarefoundation/autoware.universe/pull/5947
See https://github.com/autowarefoundation/autoware.universe/pull/5947
> feat: add stopped_object.max_object_vel in dynamic_avoidance

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/drivable_area_expansion.param.yaml
Renames a parameter.
Needed for https://github.com/autowarefoundation/autoware.universe/pull/5640
Psim
None
> refactor(behavior_path_planner): rename parameter "extra_arc_length" to "arc_length_range"

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
apply params used in xx1 vehicle.
Nothing.
> fix(avoidance): apply params used in xx1 vehicle

- autoware_launch/launch/components/tier4_perception_component.launch.xml
Update model names for the pedestrian traffic light recognition.
related PR to autoware.universe: https://github.com/autowarefoundation/autoware.universe/pull/5871
> feat(autoware_launch): update traffic light recognition models

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/5953
See https://github.com/autowarefoundation/autoware.universe/pull/5953
See https://github.com/autowarefoundation/autoware.universe/pull/5953
> feat: add parameters to avoid sudden steering in dynamic avoidance

- autoware_launch/config/localization/ndt_scan_matcher.param.yaml
- autoware_launch/config/map/pointcloud_map_loader.param.yaml
* See https://github.com/autowarefoundation/autoware.universe/pull/5873
* See https://github.com/autowarefoundation/autoware.universe/pull/5873
* See https://github.com/autowarefoundation/autoware.universe/pull/5873
> refactor(ndt_scan_matcher, map_loader): remove unused parameters

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/behavior_velocity_planner.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/6023
See https://github.com/autowarefoundation/autoware.universe/pull/6023
See https://github.com/autowarefoundation/autoware.universe/pull/6023
> feat: add behavior_output_path_interval in behavior_velocity_planner

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml
Tuned parameters of the dynamic avoidance based on the behavior on the real vehicle.
psim
Nothing since it is disabled by default.
> feat: tune dynamic avoidance parameters with the real vehicle

- autoware_launch/config/localization/ekf_localizer.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/path_smoother/elastic_band_smoother.param.yaml
necessary change for the [PR](https://github.com/autowarefoundation/autoware.universe/pull/5994)
> feat(start_planner): define collision check margin as list

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/6050
https://github.com/autowarefoundation/autoware.universe/pull/6050
https://github.com/autowarefoundation/autoware.universe/pull/6050
none.
none
> fix(intersection): fix bugs

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
Changes for `stop_distance_from_object` and  `crosswalk_attention_range` are minor tuning.
Changes for `ego_pass_first_margin_y` is corresponding to the formula changes in https://github.com/autowarefoundation/autoware.universe/pull/6033
psim tests and tier4 internal tests were performed. …
> chore(crosswalk): change params

- autoware_launch/config/perception/object_recognition/tracking/multi_object_tracker/multi_object_tracker_node.param.yaml
Fix param name typo as well as changing the default value so that it publishes the processed time
Not applicable
Not applicable
> feat(multi_object_tracker): fix typo in param name and change default value

- autoware_launch/config/control/trajectory_follower/lateral/mpc.param.yaml
add parameter for https://github.com/autowarefoundation/autoware.universe/pull/5576
see https://github.com/autowarefoundation/autoware.universe/pull/5576
None, only for debug
> feat(mpc): add parameter for debug trajectory publisher

- autoware_launch/config/perception/object_recognition/detection/image_projection_based_fusion/roi_cluster_fusion.param.yaml
- autoware_launch/config/perception/object_recognition/detection/image_projection_based_fusion/roi_detected_object_fusion.param.yaml
- autoware_launch/config/perception/object_recognition/detection/image_projection_based_fusion/roi_pointcloud_fusion.param.yaml
- autoware_launch/launch/components/tier4_perception_component.launch.xml
add image_porojection_based_fusion params 
https://github.com/autowarefoundation/autoware.universe/pull/6075
> fix(image_projection_based_fusion): add image_porojection_based_fusion params

- autoware_launch/config/planning/preset/default_preset.yaml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
The surround_obstacle_checker was disabled recently, but the way to disable was wrong.
This PR fixes it.
psim
Nothing
> fix: change the way to disable surround_obstacle_checker

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/scene_module_manager.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/5979
see universe PR
none
none
none
> feat(avoidance/goal_planner): execute avoidance and pull over simultaneously

- autoware_launch/config/perception/object_recognition/detection/image_projection_based_fusion/roi_cluster_fusion.param.yaml
- To change `remove_unknown` default the same as current projects use.
> chore: update roi_cluster_fusion default param

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/6047
https://github.com/autowarefoundation/autoware.universe/pull/6047
https://github.com/autowarefoundation/autoware.universe/pull/6047
none.
none.
> feat(intersection): consider 1st/2nd pass judge line

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/surround_obstacle_checker.param.yaml
Use params that are tested in xx1 vehicle.
With real vehicle.
Nothing.
> fix(surround_obstacle_checker): use xx1 params

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/walkway.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml
change params to vehicle tested values
universe side: https://github.com/autowarefoundation/autoware.universe/pull/6118
Vehicle tests have been performed.
tier4 internal tests https://evaluation.tier4.jp/evaluation/reports/66872580-e421-5b93-9d03-45eadb92273f?project_id=prd_jt
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/cont …
> chore(planning): change params to vehicle tested values

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
update for 
https://github.com/autowarefoundation/autoware.universe/pull/6124
> feat(goal_planner): expand pull over lanes for detection area of path generation collision check

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
sync some param to robotaxi
none
> chore(intersection): align param to robotaxi

- autoware_launch/config/vehicle/raw_vehicle_cmd_converter/raw_vehicle_cmd_converter.param.yaml
- autoware_launch/launch/autoware.launch.xml
Add aw_vehicle_cmd_converter parameter file.
See https://github.com/autowarefoundation/autoware.universe/pull/6136
> fix(vehicle_launch): add raw_vehicle_cmd_converter parameter file

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
This reverts commit 96f2f18d23ba829804415135b241065ecf53b13d.
https://github.com/autowarefoundation/autoware.universe/pull/5982 was merged so
revert [revert change collision_check_distance_from_end to shorten back distance (#757)"
](https://github.com/autowarefoundation/autoware_launch/pull/757)
---------------------
collision_check_distance_from_end: 1.0
collision_check_distance_from_end: -10.0
https://github.com/autowarefoundation/autoware.universe/assets/39142679/322e0130-7501-4518-ae16-ff589569bba6
psim
evaluator_description: feat/back_distance
2024/01/23 https://evaluation.tier4.jp/evaluation/reports/26db1ee8-30ea-57d3-bf15-8e36f34be8d7/?project_id=prd_jt
The PR reviewers **must** check the …
> feat(start_planner): change collision_check_distance_from_end to shorten back distance (#757)"

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/6001.
Evaluator.
Improve avoidance flexibility.
> feat(avoidance): add new flag to use freespace in avoidance module

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
Change return dead line param.
Nothing.
> fix(avoidance): change return dead line param

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/6143
https://github.com/autowarefoundation/autoware.universe/pull/6143## Notes for reviewers
none
none
> feat(intersection): publish and visualize the reason for dangerous situation to blame past detection fault retrospectively

- autoware_launch/config/localization/ndt_scan_matcher.param.yaml
see https://github.com/autowarefoundation/autoware.universe/pull/6186
see https://github.com/autowarefoundation/autoware.universe/pull/6186
see https://github.com/autowarefoundation/autoware.universe/pull/6186
> refactor(ndt_scan_matcher): rename de-grounded

- autoware_launch/config/perception/object_recognition/tracking/tracking_object_merger/decorative_tracker_merger.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/6168
See https://github.com/autowarefoundation/autoware.universe/pull/6168
See https://github.com/autowarefoundation/autoware.universe/pull/6168
> fix(tracking_object_merger): fix bug and rework parameters

- autoware_launch/launch/components/tier4_map_component.launch.xml
see https://github.com/autowarefoundation/autoware.universe/pull/6185
see https://github.com/autowarefoundation/autoware.universe/pull/6185
see https://github.com/autowarefoundation/autoware.universe/pull/6185
see https://github.com/autowarefoundation/autoware.universe/pull/6185
see https://github.com/autowarefoundation/autoware.universe/pull/6185
see https://github.com/autowarefoundation/autoware.universe/pull/6185
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/ …
> refactor(tier4_map_lcomponent): use map.launch.xml instead of map.launch.py

- autoware_launch/config/perception/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml
- See https://github.com/autowarefoundation/autoware.universe/pull/6209
> chore(ground_segmentation): add default params

- autoware_launch/config/perception/object_recognition/detection/object_velocity_splitter/object_velocity_splitter_radar.param.yaml
- autoware_launch/config/perception/object_recognition/detection/object_velocity_splitter/object_velocity_splitter_radar_fusion.param.yaml
- autoware_launch/launch/components/tier4_perception_component.launch.xml
See https://github.com/autowarefoundation/autoware.universe/pull/6158
See https://github.com/autowarefoundation/autoware.universe/pull/6158
See https://github.com/autowarefoundation/autoware.universe/pull/6158
> chore(object_velocity_splitter): rework parameters

- autoware_launch/config/perception/object_recognition/detection/radar_crossing_objects_noise_filter/radar_crossing_objects_noise_filter.param.yaml
- autoware_launch/launch/components/tier4_perception_component.launch.xml
Add config files for perception launch
Test by rosbag
> fix(autoware_launch): add config file

- autoware_launch/config/localization/twist2accel.param.yaml
- autoware_launch/launch/components/tier4_localization_component.launch.xml
see https://github.com/autowarefoundation/autoware.universe/pull/6266
see https://github.com/autowarefoundation/autoware.universe/pull/6266
see https://github.com/autowarefoundation/autoware.universe/pull/6266
> chore(twist2accel): rework parameters

- autoware_launch/config/perception/object_recognition/prediction/map_based_prediction.param.yaml
add new param related to https://github.com/autowarefoundation/autoware.universe/pull/6189
> feat(map_based_prediction): consider crosswalks signals

- autoware_launch/config/planning/preset/default_preset.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/sampling_planner/sampling_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/scene_module_manager.param.yaml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
Is required by https://github.com/autowarefoundation/autoware.universe/pull/6131
> feat(behavior_path_sampling_planner): add sampling based planner to behavior path planner

- autoware_launch/config/localization/pose_initializer.param.yaml
See [autowarefoundation/autoware.universe#5773](https://github.com/autowarefoundation/autoware.universe/pull/5773)
See [autowarefoundation/autoware.universe#5773](https://github.com/autowarefoundation/autoware.universe/pull/5773)
See [autowarefoundation/autoware.universe#5773](https://github.com/autowarefoundation/autoware.universe/pull/5773)
> refactor(pose_initializer): rework parameters

- autoware_launch/config/perception/object_recognition/detection/lidar_model/centerpoint_tiny.param.yaml
Fix a bug in https://github.com/autowarefoundation/autoware_launch/pull/822
Not applicable
Not applicable
> fix(lidar_centerpoint): remove build_only param from param.yaml

- autoware_launch/config/perception/object_recognition/tracking/radar_object_tracker/radar_object_tracker.param.yaml
- autoware_launch/launch/components/tier4_perception_component.launch.xml
This is refactor PR so that move launch.xml parameter to yaml file.
Tested wiht lsim.
> chore(radar_object_tracker): move radar object tracker param to yaml

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/6369
https://github.com/autowarefoundation/autoware.universe/pull/6369
https://github.com/autowarefoundation/autoware.universe/pull/6369
none
none
> feat(goal_planne): check objects within the area between ego edge and boudary of pull_over_lanes

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
change ego pass later param related to 
https://github.com/autowarefoundation/autoware.universe/pull/6033
https://github.com/autowarefoundation/autoware_launch/pull/780
psim and tier4 internal test
> chore(crosswalk): change LATER param

- autoware_launch/config/localization/ar_tag_based_localizer.param.yaml
- autoware_launch/launch/components/tier4_localization_component.launch.xml
see https://github.com/autowarefoundation/autoware.universe/pull/6390
see https://github.com/autowarefoundation/autoware.universe/pull/6390
see https://github.com/autowarefoundation/autoware.universe/pull/6390
> fix(localization): add ar tag based localizer param

- autoware_launch/config/planning/scenario_planning/common/common.param.yaml
- autoware_launch/config/planning/scenario_planning/common/motion_velocity_smoother/motion_velocity_smoother.param.yaml
Launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/6388
See https://github.com/autowarefoundation/autoware.universe/pull/6388
See https://github.com/autowarefoundation/autoware.universe/pull/6388
> feat: define common max_vel

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/blind_spot.param.yaml
change ignore_width to zero
https://github.com/autowarefoundation/autoware.universe/pull/6405
see https://github.com/autowarefoundation/autoware.universe/pull/6405
none
none
> refactor(blind_spot): find first_conflicting_lane just as intersection module

- autoware_launch/config/planning/scenario_planning/common/planning_validator/planning_validator.param.yaml
- https://github.com/autowarefoundation/autoware.universe/pull/6195
Confirm it is able to engage in Psim.
Nothing.
> fix(planning_validator): add missing params

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
remove unused parameter: collision_check_distance_from_end
> chore(start_planner): remove unused parameter

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/6336
> feat(avoidance): use free steer policy for safety check

- autoware_launch/config/perception/traffic_light_arbiter/traffic_light_arbiter.param.yaml
Launch PR for https://github.com/autowarefoundation/autoware.universe/pull/6423 .
See https://github.com/autowarefoundation/autoware.universe/pull/6423
> feat(traffic_light_arbiter): add parameter of signal match validator

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/6412
> feat(goal_planner): change pull over path candidate priority with soft and hard margins

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/6501.
Evaluator.
Improve avoidance maneuver.
> feat(avoidance): wait next shift approval until the ego reaches shift length threshold

- .github/CODEOWNERS-manual
- autoware_launch/package.xml
Add package maintainers for autoware_launch.
This allows myself and @xmfcx to review the package as well.
> chore: update package maintainers for autoware_launch package

- autoware_launch/config/planning/scenario_planning/common/common.param.yaml
Based on the action items in https://github.com/orgs/autowarefoundation/discussions/4052, this PR set the max velocity to 15km/h.
Part of
- https://github.com/autowarefoundation/autoware/issues/4521
- https://github.com/autowarefoundation/autoware/issues/4520
planning simulator
The max velocity will be 15km/h.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/co …
> feat: set the max velocity to 15km/h

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance_by_lane_change/avoidance_by_lane_change.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/6520
Improve avoidance maneuver.
> feat(avoidance): change lateral margin based on if it's parked vehicle

- autoware_launch/config/vehicle/raw_vehicle_cmd_converter/raw_vehicle_cmd_converter.param.yaml
Part of:
- https://github.com/autowarefoundation/autoware.universe/issues/6473
Should be merged after:
- https://github.com/autowarefoundation/autoware.universe/pull/6476
> fix(raw_vehicle_cmd_converter): csv paths are resolved in param.yaml

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/out_of_lane.param.yaml
Add parameter for https://github.com/autowarefoundation/autoware.universe/pull/6478
> feat(out_of_lane): add cut_beyond_red_traffic_lights parameter

- autoware_launch/config/system/component_state_monitor/topics.yaml
see https://github.com/autowarefoundation/autoware.universe/pull/6563
> fix(component_state_monitor): change pose_estimator_pose rate

- autoware_launch/config/system/duplicated_node_checker/duplicated_node_checker.param.yaml
print which node name is duplicate
```
[system_error_monitor-17] [ERROR 1708923402.776953195] [system_error_monitor /autoware/system/duplicated_node_checker/duplicated_node_checker: duplicated_node_checker]: [Single Point Fault]: Error: Duplicated nodes detected[/dummy_diagnostics],
``` …
> chore(duplicated_node_checker): print duplication name

- autoware_launch/rviz/autoware.rviz
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/6579
See https://github.com/autowarefoundation/autoware.universe/pull/6579
See https://github.com/autowarefoundation/autoware.universe/pull/6579
> feat: add marker for control's stop reason, false by default

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/6601.
Nothing.
> refactor(avoidance): rename param

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/6631.
> fix(avoidance): wait and see objects

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/dynamic_obstacle_stop.param.yaml
Add parameter for https://github.com/autowarefoundation/autoware.universe/pull/6594
> feat(dynamic_obstacle_stop): add parameter to ignore unavoidable collisions

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/run_out.param.yaml
pick vehicle tuned parameter
tier4 internal tests was performed
https://evaluation.tier4.jp/evaluation/reports/51c28420-dc01-5290-80a0-6ed40e06ed85?project_id=prd_jt
> feat(run_out): adjust parameter

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/run_out.param.yaml
Changes needed by this PR: https://github.com/autowarefoundation/autoware.universe/pull/6680
> feat(run_out_module): new params for run out, add ego cut lane

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/run_out.param.yaml
Needed by https://github.com/autowarefoundation/autoware.universe/pull/6690
> feat(run_out): add obstacle types to run out

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
Needed for universe PR: https://github.com/autowarefoundation/autoware.universe/pull/6604
Psim
> feat(crosswalk): rename parameter to ignore traffic light

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/run_out.param.yaml
Needed by https://github.com/autowarefoundation/autoware.universe/pull/6703
> feat(run_out): add params to exclude obstacles already on the ego's path

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
Needed by https://github.com/autowarefoundation/autoware.universe/pull/6721
> feat(start_planner): add path validation check

- autoware_launch/config/perception/object_recognition/detection/lidar_model/centerpoint.param.yaml
- autoware_launch/config/perception/object_recognition/detection/lidar_model/centerpoint_sigma.param.yaml
Add centerpoint_sigma.param.yaml
related PR to autoware.universe: https://github.com/autowarefoundation/autoware.universe/pull/6573
> feat(autoware_launch): add centerpoint_sigma param

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/run_out.param.yaml
Required by: https://github.com/autowarefoundation/autoware.universe/pull/6732
> feat(run_out): maintain stop wall for some seconds

- autoware_launch/config/perception/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml
- To add param for https://github.com/autowarefoundation/autoware.universe/pull/6753
> chore(ground_segmentation): add tuning param

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/6698.
Nothing.
> feat(avoidance): limit acceleration during avoidance maneuver

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
https://star4.slack.com/archives/CEV8XMJBV/p1712724941387759
none
none
> chore(intersection_occlusion): increase possible_object_bbox size to ignore small occlusion and ghost stop

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance_by_lane_change/avoidance_by_lane_change.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/6786.
Nothing.
> refactor(avoidance, AbLC): rebuild parameter structure

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/6798
Psim
Nothing.
> refactor(avoidance): unify redundant parameters

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
Tune more than https://github.com/autowarefoundation/autoware_launch/pull/950
https://star4.slack.com/archives/CEV8XMJBV/p1713424607339679?thread_ts=1712724941.387759&cid=CEV8XMJBV
Lsim
> chore(intersection_occlusion): more increase possible_object_bbox size to ignore small occlusion and ghost stop

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/6822.
Psim
Nothing.
> refactor(bpp): remove unused params

- autoware_launch/config/control/autonomous_emergency_braking/autonomous_emergency_braking.param.yaml
For this PR: https://github.com/autowarefoundation/autoware.universe/pull/6875
> feat(autonomous_emergency_braking): add params for aeb

- autoware_launch/config/perception/object_recognition/detection/lidar_model/pointpainting.param.yaml
add centerpoint_sigma param to pointpainting.param.yaml
related PR to autoware.universe: https://github.com/autowarefoundation/autoware.universe/pull/6573
> feat(autoware_launch): add centerpoint_sigma param to pointpainting.param.yaml

- autoware_launch/config/perception/object_recognition/detection/lidar_model/centerpoint_tiny.param.yaml
- To add param file for change at PR: https://github.com/autowarefoundation/autoware.universe/pull/6901
> fix(lidar_centerpoint): add param file for centerpoint_tiny

- autoware_launch/config/localization/ekf_localizer.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/6871
See https://github.com/autowarefoundation/autoware.universe/pull/6871
See https://github.com/autowarefoundation/autoware.universe/pull/6871
> fix(ekf_localizer): updated ekf gate_dist params

- autoware_launch/config/system/component_state_monitor/topics.yaml
see https://github.com/autowarefoundation/autoware.universe/pull/6957
see https://github.com/autowarefoundation/autoware.universe/pull/6957
see https://github.com/autowarefoundation/autoware.universe/pull/6957
> fix(componet_state_monitor): remove ndt node alive monitoring

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/path_sampler/path_sampler.param.yaml
Add params for PR https://github.com/autowarefoundation/autoware.universe/pull/6939 
PSim
> feat(path_planner): params to adjust hard constraints and path reuse

- autoware_launch/rviz/autoware.rviz
Corrects position of overlay
**Merge with:**
- https://github.com/autowarefoundation/autoware.universe/pull/6883
**Part of:**
- https://github.com/autowarefoundation/autoware.universe/issues/6882
> fix: update widget size and position

- autoware_launch/config/perception/object_recognition/prediction/map_based_prediction.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/6905
https://github.com/autowarefoundation/autoware.universe/pull/6905
see https://github.com/autowarefoundation/autoware.universe/pull/6905
none
none
> feat(map_based_prediction): incorporate crosswalk user history

- autoware_launch/config/localization/ndt_scan_matcher/ndt_scan_matcher.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/6990
See https://github.com/autowarefoundation/autoware.universe/pull/6990
See https://github.com/autowarefoundation/autoware.universe/pull/6990
> fix(ndt_scan_matchere): improved tpe

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/7097.
Psim
Nothing.
> feat(avoidance)!: make it selectable output debug marker from yaml

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/blind_spot.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/7146
https://github.com/autowarefoundation/autoware.universe/pull/7146
see https://github.com/autowarefoundation/autoware.universe/pull/7146
none
none
> feat(blind_spot): consider time to collision

- autoware_launch/config/perception/object_recognition/prediction/map_based_prediction.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/6877
https://github.com/autowarefoundation/autoware.universe/pull/6877
https://github.com/autowarefoundation/autoware.universe/pull/6877
none
none
> feat(map_based_prediction): use different time horizon

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml
unvierse PR: https://github.com/autowarefoundation/autoware.universe/pull/7177
> feat(obstacle_cruise_planner)!: ignore to garze against unknwon objects

- autoware_launch/config/control/lane_departure_checker/lane_departure_checker.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
Required by https://github.com/autowarefoundation/autoware.universe/pull/7193
> feat(lane_departure_checker): add params for lane departure margin

- autoware_launch/rviz/autoware.rviz
> feat: update layout

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml
disable a recent implemented feature
psim
> feat(obstacle_curise): revert lateral stop margin for unknown objects

- autoware_launch/config/vehicle/raw_vehicle_cmd_converter/raw_vehicle_cmd_converter.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/7385
See https://github.com/autowarefoundation/autoware.universe/pull/7385
See https://github.com/autowarefoundation/autoware.universe/pull/7385
> refactor(raw_vehicle_cmd_converter)!: prefix package and namespace with autoware

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
neccesary change for the [PR](https://github.com/autowarefoundation/autoware.universe/pull/7477)
run psim 
> fix(start_planner): redefine the necessary parameters

- autoware_launch/config/perception/object_recognition/detection/object_filter/object_lanelet_filter.param.yaml
- autoware_launch/config/perception/object_recognition/detection/object_filter/radar_lanelet_filter.param.yaml
add missing parameter update
Universe PR https://github.com/autowarefoundation/autoware.universe/pull/7107
Launcher PR https://github.com/autowarefoundation/autoware_launch/pull/998
> fix(object_lanelet_filter): radar object lanelet filter parameter update

- autoware_launch/config/control/autoware_autonomous_emergency_braking/autonomous_emergency_braking.param.yaml
Required by https://github.com/autowarefoundation/autoware.universe/pull/7605
> feat(autonomous_emergency_braking): add and tune params

- autoware_launch/config/localization/ekf_localizer.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/7708
See https://github.com/autowarefoundation/autoware.universe/pull/7708
See https://github.com/autowarefoundation/autoware.universe/pull/7708
> feat(ekf_localizer): add covariance ellipse diagnostics

- autoware_launch/launch/components/tier4_control_component.launch.xml
See https://github.com/autowarefoundation/autoware.universe/pull/7682.
> refactor(tier4_control_launch): replace python launch with xml

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/7791
> feat(goal_planner): prioritize pull over path by curvature

- autoware_launch/config/control/autoware_autonomous_emergency_braking/autonomous_emergency_braking.param.yaml
Required by https://github.com/autowarefoundation/autoware.universe/pull/7894
> feat(autonomous_emergency_braking): add param for oublishing debug markers

- autoware_launch/config/map/lanelet2_map_loader.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/7074
see https://github.com/autowarefoundation/autoware.universe/pull/7074
see https://github.com/autowarefoundation/autoware.universe/pull/7074
see https://github.com/autowarefoundation/autoware.universe/pull/7074
> feat(map_loader, route_handler)!: add format_version validation

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/static_obstacle_avoidance.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/7851
> feat(static_obstacle_avoidance): add new option to change policy

- autoware_launch/launch/components/tier4_perception_component.launch.xml
This PR includes the following changes:
- Added the args from perception.launch.xml to tier4_perception_component.launch.xml.
- Modified the args to accept external parameters for better flexibility and configurability.
- Changed the default number of cameras for the traffic light recognition to 2.
These changes enable easier parameterization and customization of the launch configurations from external sources and improve the default setup for signal recognition.
- Verified in my local environment that the perception module launches without changes in behavior.
- Confirmed that nodes can be controlled using parameters provided externally. (e.g. `use_traffic_light_recognition:=false`)
- Ensured that the TLR works correctly even when there is only one image topic.
No effects
The PR author …
> feat(tier4_perception_component): refactored launch options

- .gitignore
Add `.gitignore` file to ignore dir `/node_modules` created by prettier.
Nothing.
Nothing.
> chore(git): add ignore file

- .github/CODEOWNERS
- .github/CODEOWNERS-manual
update code owners for tier4_system_component.launch.xml
> chore: update code owners for tier4_system_component.launch.xml

- autoware_launch/config/system/duplicated_node_checker/duplicated_node_checker.param.yaml
complimentary to this PR: https://github.com/autowarefoundation/autoware.universe/pull/7959
> feat(duplicated_node_checker): add duplicate nodes to ignore

- autoware_launch/config/system/processing_time_checker/processing_time_checker.param.yaml
- autoware_launch/launch/components/tier4_system_component.launch.xml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/7957
See https://github.com/autowarefoundation/autoware.universe/pull/7957
> feat: add config for processing_time_checker

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
necessary change for https://github.com/autowarefoundation/autoware.universe/pull/7881
Described in https://github.com/autowarefoundation/autoware.universe/pull/7881
> feat(autoware_behavior_path_planner): remove max_iteration_num parameter

- autoware_launch/config/perception/object_recognition/detection/lidar_model/centerpoint.param.yaml
- autoware_launch/config/perception/object_recognition/detection/lidar_model/centerpoint_sigma.param.yaml
- autoware_launch/config/perception/object_recognition/detection/lidar_model/centerpoint_tiny.param.yaml
- autoware_launch/config/perception/object_recognition/detection/lidar_model/pointpainting.param.yaml
This is the companion PR of https://github.com/autowarefoundation/autoware.universe/pull/7936
> chore: add ml detectors' buffer size

- autoware_launch/config/control/control_validator/control_validator.param.yaml
add velocity check function to validate vehicle velocity controllers
universe: https://github.com/autowarefoundation/autoware.universe/pull/7806
psim and tier4 internal test
> feat(control_validator)!: add velocity check

- autoware_launch/launch/e2e_simulator.launch.xml
Fixing the carla interface name in e2e_launch to follow updated Autoware naming rules.
> feat(e2e_simulator.launch): renamed carla interface package in e2e_launch

- autoware_launch/launch/components/tier4_simulator_component.launch.xml
- autoware_launch/launch/planning_simulator.launch.xml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/8065
> feat(simple_planning_simulator): add actuation command simulator

- autoware_launch/config/localization/ndt_scan_matcher/ndt_scan_matcher.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/8108
See https://github.com/autowarefoundation/autoware.universe/pull/8108
See https://github.com/autowarefoundation/autoware.universe/pull/8108
> feat(ndt_scan_matcher): add scale_factor to covariance_estimation

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
lanncher update for https://github.com/autowarefoundation/autoware.universe/pull/7901
> feat(start_planner): add end_pose_curvature_threshold

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/out_of_lane.param.yaml
Needed for https://github.com/autowarefoundation/autoware.universe/pull/7891
> feat(out_of_lane): add parameter to ignore objects behind ego

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
tuning
- https://github.com/autowarefoundation/autoware_launch/pull/1059
- https://github.com/autowarefoundation/autoware.universe/pull/7901
0.1
https://evaluation.tier4.jp/evaluation/reports/22321a1e-b6ad-5390-865e-3a81c6d32ae5?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/82233daf-67d1-55f1-b06b-16028354fab2?project_id=prd_jt …
> feat(start_planner): set end_pose_curvature_threshold 0.1

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/drivable_area_expansion.param.yaml
Required for https://github.com/autowarefoundation/autoware.universe/pull/8136
> feat(dynamic_drivable_area_expansion): min_bound_interval parameter

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/out_of_lane.param.yaml
Add parameters for https://github.com/autowarefoundation/autoware.universe/pull/7918
Psim
> feat(out_of_lane): add lateral buffer between the lane and stop pose

- autoware_launch/config/localization/ndt_scan_matcher/ndt_scan_matcher.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/8252
See https://github.com/autowarefoundation/autoware.universe/pull/8252
See https://github.com/autowarefoundation/autoware.universe/pull/8252
See https://github.com/autowarefoundation/autoware.universe/pull/8252
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelin …
> perf(ndt_scan_matcher): change the temperature of multi_ndt_score to 0.05

- autoware_launch/config/control/autoware_autonomous_emergency_braking/autonomous_emergency_braking.param.yaml
- autoware_launch/config/control/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml
- autoware_launch/config/system/mrm_emergency_stop_operator/mrm_emergency_stop_operator.param.yaml
Enables AEB module emergency stop
PSim
> feat(autonomous_emergency_braking): enable AEB stop in vehicle_cmd_gate and diag_graph_agg

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/scene_module_manager.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/8117
https://github.com/autowarefoundation/autoware.universe/pull/8117
https://github.com/autowarefoundation/autoware.universe/pull/8117
none
none
> feat(behavior_path _planner): divide planner manager modules into dependent slots

- autoware_launch/config/control/autoware_autonomous_emergency_braking/autonomous_emergency_braking.param.yaml
- autoware_launch/rviz/autoware.rviz
Needed by https://github.com/autowarefoundation/autoware.universe/pull/8312
> feat(autonomous_emergency_braking): add info marker to aeb and state check override

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
Add separate RSS param for parked object
https://github.com/autowarefoundation/autoware.universe/pull/8316
> feat(lane_change): use different rss param to deal with parked vehicle

- autoware_launch/config/system/system_monitor/process_monitor.param.yaml
Change the number of processes monitored by Process Monitor from the top 5 to the top 40, as measurements of bus-type real vehicles indicated that approximately 80% of the total number of processes amounted to about 40.
Tested and verified on real bus and taxi vehicles
([TIERIV Internal Link](https://star4.slack.com/archives/C050UA0LEAG/p1723081161836289?thread_ts=1720764608.012779&cid=C050UA0LEAG))
The number of processes monitored by process_monitor for CPU and memory will increase. Consequently, the volume of topics flowing into diagnostics will slightly increase
none
After all …
> feat: increase the number of processes monitored by process_monitor

- autoware_launch/config/perception/object_recognition/tracking/tracking_object_merger/decorative_tracker_merger.param.yaml
related pr : https://github.com/autowarefoundation/autoware.universe/pull/8418
> feat(tracking_object_merger): add merge frame

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/8363
> fix(lane_change): skip generating path if longitudinal distance difference is less than threshold

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
… 
launcher update for 
https://github.com/autowarefoundation/autoware.universe/pull/8449
> fix(goal_planner): fix lane departure check not working correctly due to uninitialized variable

- autoware_launch/config/perception/object_recognition/detection/lidar_model/centerpoint_sigma.param.yaml
> fix(lidar_model): add centerpoint_sigma param file

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/8457
> perf(goal_planner): faster path sorting and selection

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/static_obstacle_avoidance.param.yaml
Refer to https://github.com/autowarefoundation/autoware.universe/pull/8551
Added parameter for static_obstacle_avoidance
> feat(static_obstacle_avoidance): add parameter for envelope polygon creation

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
Rename parameter to a more  expressive name
> refactor(lane_change): rename prepare_segment_ignore_object_velocity_thresh

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/7943
> feat(lane_change): consider deceleration in safety check for cancel

- autoware_launch/config/vehicle/raw_vehicle_cmd_converter/raw_vehicle_cmd_converter.param.yaml
launcher update for https://github.com/autowarefoundation/autoware.universe/pull/8504
> feat(raw_vehicle_cmd_converter): add steer command conversion with VGR

- autoware_launch/config/vehicle/raw_vehicle_cmd_converter/raw_vehicle_cmd_converter.param.yaml
disable actuation to steering by defalut.
this is new feature introduced in https://github.com/autowarefoundation/autoware.universe/pull/8504
but many user don't kwnow the details.
In practice, the description config is called, and this launcher config is often not used, but for now it defaults to false. …
> feat(raw_vehicle_cmd_converter): disable actuation to steering

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/out_of_lane.param.yaml
Required for https://github.com/autowarefoundation/autoware.universe/pull/8453
> feat(out_of_lane): redesign to improve accuracy and performance

- autoware_launch/config/localization/ekf_localizer.param.yaml
see https://github.com/autowarefoundation/autoware.universe/pull/8619
see https://github.com/autowarefoundation/autoware.universe/pull/8619
see https://github.com/autowarefoundation/autoware.universe/pull/8619
see https://github.com/autowarefoundation/autoware.universe/pull/8619
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelin …
> fix(ekf_localizer): change roll, pitch proc dev

- autoware_launch/config/control/trajectory_follower/longitudinal/pid.param.yaml
New parameters are added to follow the universe PR https://github.com/autowarefoundation/autoware.universe/pull/8325
universe PR: https://github.com/autowarefoundation/autoware.universe/pull/8325
> feat(pid_longitudinal_controller)!: add acceleration feedback block

- autoware_launch/config/perception/object_recognition/detection/detected_object_validation/object_lanelet_filter.param.yaml
- autoware_launch/config/perception/object_recognition/detection/detected_object_validation/object_position_filter.param.yaml
- autoware_launch/config/perception/object_recognition/detection/detected_object_validation/obstacle_pointcloud_based_validator.param.yaml
- autoware_launch/config/perception/object_recognition/detection/detected_object_validation/occupancy_grid_based_validator.param.yaml
Related with universe change https://github.com/autowarefoundation/autoware.universe/pull/7750, autoware_launch paramters also should be updated.
> feat(detected_object_validation): copy parameter files update from universe

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/static_obstacle_avoidance.param.yaml
tune parameters to improve availability in dense urban usecases.
1. decrease envelope buffer.
2. increase lateral soft margin.
> fix(static_obstacle_avoidance): tune parameters

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/static_obstacle_avoidance.param.yaml
Increase max_prepare_time 2.0 to 3.0 seconds to improve turn signal behavior.
> fix(static_obstacle_avoidance): increase prepare time

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/dynamic_obstacle_avoidance.param.yaml
Related: https://github.com/autowarefoundation/autoware.universe/pull/8295
> feat(autoware_launch): add expansion params

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
see https://github.com/autowarefoundation/autoware.universe/pull/8795
see https://github.com/autowarefoundation/autoware.universe/pull/8795
see https://github.com/autowarefoundation/autoware.universe/pull/8795
none
none
> feat(goal_planner): dense goal candidate sampling in BusStopArea

- .github/CODEOWNERS
add myself to the maintainer of planning config
> chore(planning): add maintainer

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
launch PR for https://github.com/autowarefoundation/autoware.universe/pull/8817
See https://github.com/autowarefoundation/autoware.universe/pull/8817
See https://github.com/autowarefoundation/autoware.universe/pull/8817
> feat: add parameters for restart suppression in crosswalk

- autoware_launch/config/planning/mission_planning/mission_planner/mission_planner.param.yaml
launcher update for 
https://github.com/autowarefoundation/autoware.universe/pull/8757
> feat(mission_planner): add option to prevent rerouting in autonomous driving mode

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
necessary change for the [PR](https://github.com/autowarefoundation/autoware.universe/pull/8863)
run planning_simulator
> feat(start_planner): add option to skip rear vehicle check

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
This PR changes the parameter set to follow the universe side: https://github.com/autowarefoundation/autoware.universe/pull/8853
universe PR: https://github.com/autowarefoundation/autoware.universe/pull/8853
> feat(crosswalk)!: update stop position caluculation

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
remove unnecessary parameters in behavior_path_planner.
> refactor(behavior_path_planner): remove unnecessary parameters

- autoware_launch/config/system/system_monitor/ntp_monitor.param.yaml
add missing parameter in ntp_monitor.
> refactor(system_monitor/ntp_monitor): add-missing-parameters

- autoware_launch/config/system/system_monitor/net_monitor.param.yaml
remove unnecessary parameter in net_monitor.
> refactor(system_monitor/net_monitor): remove-missing-patameters

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance_by_lane_change/avoidance_by_lane_change.param.yaml
> fix(avoidance_by_lane_change): remove unused parameter

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
added lane change parameter to enable / disable new feature added by this [PR](https://github.com/autowarefoundation/autoware.universe/pull/8750)
> feat(lane_change): add lane change parameter

- autoware_launch/config/control/autoware_autonomous_emergency_braking/autonomous_emergency_braking.param.yaml
Required by https://github.com/autowarefoundation/autoware.universe/pull/9004
> feat(autonomous_emergency_braking): set max imu path length

- autoware_launch/rviz/autoware.rviz
necessary change for the [PR](https://github.com/autowarefoundation/autoware.universe/pull/9078)
run psim and result is explained in the [PR](https://github.com/autowarefoundation/autoware.universe/pull/9078)
> refactor(rviz): add VirtualWall display for Autonomous Emergency Braking

- autoware_launch/config/perception/object_recognition/detection/pointcloud_filter/pointcloud_map_filter.param.yaml
- To add new parameter as PR: https://github.com/autowarefoundation/autoware.universe/pull/9024
> fix(pointcloud_map_filter): add threshold for split map grid size 

- autoware_launch/config/control/autoware_autonomous_emergency_braking/autonomous_emergency_braking.param.yaml
These parameters changes are based on recent real-life tests on Odaiba. These tests were aimed at reducing unwanted AEB activation caused by vegetation close to the ego path and the AEB's IMU path activating an emergency stop when the ego turns at high speeds. 
The voxel grid changes are aimed at maintaining AEB performance while being able to detect thin and long objects.
With these parameters, no unwanted activation happened for our tests. These parameters are aimed at a regular sized vehicle implementation in urban environments and should be tuned based on the user's needs. These parameters might be considered to be a bit on the conservative side (harder to activate AEB stop).
Real life tests at Odaiba.
Degradation check: https://evaluation.tier4.jp/evaluation/reports/dbbc4faf-6813-5720 …
> feat(autonomous_emergency_braking): change params to cater to urban scenario

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
tuning max dry steer angle with real vehicle.  use 0.4 rad becauses it's lateral deviation is not large
[Screencast from 08-29-24 13_52_15.webm](https://github.com/user-attachments/assets/1753cdac-0657-4dfd-b238-2fca56346efb)
https://docs.google.com/spreadsheets/d/11E7iOB-pH0HPChzvNQvsN8rY6sVnwd9SEy3HRQyNavQ/edit?gid=122359661#gid=122359661
https://star4.slack.com/archives/CEV8XMJBV/p1724909641188309?thread_ts=1724832203.130269&cid=CEV8XMJBV
https://evaluation.tier4.jp/evaluation/reports/77e5936f-10cb-5050-9aa1-8f41f866878e?project_id=prd_jt
real vehicle
After all …
> feat(start/goal_planner): increse max dry steering angle

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/detection_area.param.yaml
This PR adds new parameter to follow universe side PR https://github.com/autowarefoundation/autoware.universe/pull/9255
psim and tier4 internal tests.
> feat(detection_area)!: add retruction feature

- autoware_launch/CHANGELOG.rst
- autoware_launch/package.xml
This is almost same as https://github.com/autowarefoundation/autoware.universe/pull/9266 but for `autoware_launch`.
This PR is based on https://github.com/orgs/autowarefoundation/discussions/5292 and aims to manage the versioning of `autowarefoundation/autoware_launch` using ROS package release tools. 
All package versions have been unified to 0.38.0 following `https://github.com/tier4/autoware_launch/tree/v0.38.0`.
Note that this PR is a merge request not for the `main` branch, but for the newly created `humble` branch. Once this PR is merged, I plan to tag `0.38.0` on the `humble` branch and create a PR to merge the differences into the `main` branch as well.
Currently, I was manually running the ROS package release tools to create PR, but in the future, we would like to modify …
> chore(package.xml): bump version to 0.38.0

- autoware_launch/CHANGELOG.rst
- autoware_launch/package.xml
This PR incorporates changes from the `humble` branch into the `main` branch. https://github.com/autowarefoundation/autoware_launch/pull/1226
> This is almost same as https://github.com/autowarefoundation/autoware.universe/pull/9266 but for `autoware_launch`.
> 
> This PR is based on https://github.com/orgs/autowarefoundation/discussions/5292 and aims to manage the versioning of `autowarefoundation/autoware_launch` using ROS package release tools. 
> All package versions have been unified to 0.38.0 following `https://github.com/tier4/autoware_launch/tree/v0.38.0`.
> 
> Note that this PR is a merge request not for the `main` branch, but for the newly created `humble` branch. Once this PR is merged, I plan to tag `0.38.0` on the `humble` branch and create a PR to merge the differences into …
> chore(package.xml): bump version to 0.38.0 (#1226)

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
disable slowdowns when the crosswalk is occluded
> feat(crosswalk): disable slowdowns when the crosswalk is occluded

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
see universe PR: https://github.com/autowarefoundation/autoware.universe/pull/9329
psim and tier4 scenario tests
> chore(crosswalk)!: delete wide crosswalk corresponding function

- autoware_launch/rviz/planning_bev.rviz
- autoware_launch/rviz/planning_tpv.rviz
Show steering/velocity factor on rviz bottom left. I think it's useful for us to investigate the cause of unexpected sudden brake or steering.
Psim
> feat(rviz): show velocity/steering factors

- autoware_launch/config/planning/scenario_planning/parking/freespace_planner/freespace_planner.param.yaml
lower safety distance margin from 0.5 to 0.4m
> feat(freespace_planner): lower safety distance margin from 0.5 to 0.4m

- autoware_launch/config/control/autoware_autonomous_emergency_braking/autonomous_emergency_braking.param.yaml
Required by https://github.com/autowarefoundation/autoware.universe/pull/9410
> feat(autonomous_emergency_braking): add params for limiting imu path with lat deviation

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
add new lane change parameters required due to following PR:
- https://github.com/autowarefoundation/autoware.universe/pull/9480
> feat(lane_change): add delay lane change parameters

- .github/sync-files.yaml
Part of:
- https://github.com/autowarefoundation/autoware/issues/4058
- https://github.com/autowarefoundation/autoware_launch/pull/1190
> ci(sync-files): make use of sync-file-templates repository

- autoware_launch/rviz/autoware.rviz
- autoware_launch/rviz/perception.rviz
- autoware_launch/rviz/planning_bev.rviz
- autoware_launch/rviz/planning_tpv.rviz
- autoware_launch/rviz/scenario_simulator.rviz
This PR consists of the following changes.
1. follow the virtual topic name align 
2. visualize cruise and slow_down wall as default settings 
3. add objects_of_interest for the obstacle_cruise
universe PR: https://github.com/autowarefoundation/autoware.universe/pull/9594
psim
None.
None.
> refactor(obstacle_cruise_planner)!: refactor rviz and terminal info

- autoware_launch/config/perception/object_recognition/tracking/multi_object_tracker/multi_object_tracker_node.param.yaml
Updated `multi_object_tracker_node.param.yaml` according to parameters extracted in PR:
https://github.com/autowarefoundation/autoware.universe/pull/9621
Tested parameters changes in Carla environment.
None.
None.
> refactor(autoware_multi_object_tracker): extract tracker parameters

- autoware_launch/config/perception/object_recognition/detection/image_projection_based_fusion/fusion_common.param.yaml
This PR will add option for time keeper feature to image_projection_based_fusion.
This PR must merge with https://github.com/autowarefoundation/autoware.universe/pull/9632
None.
None.
> feat(image_projection_based_fusion): add timekeeper option

- .github/sync-files.yaml
> ci(sync-files): add pre-commit-config

- autoware_launch/config/perception/object_recognition/detection/detected_object_validation/obstacle_pointcloud_based_validator.param.yaml
Add parameter validate_max_distance_m into obstacle_pointcloud_based_validator.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/9663
None.
None.
> feat(detected_object_validation): add validation for maximum distance in obstacle_pointcloud_based_validator

- .github/CODEOWNERS-manual
- autoware_launch/config/control/trajectory_follower/longitudinal/pid.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/9675
See https://github.com/autowarefoundation/autoware.universe/pull/9675
None.
None.
> feat: remove emergency_state_traj_{trans/rot}_dev from trajectory_follower

- autoware_launch/rviz/autoware.rviz
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/9685
See https://github.com/autowarefoundation/autoware.universe/pull/9685
None.
None.
> feat: add velocity control virtual wall

- autoware_launch/config/control/trajectory_follower/lateral/mpc.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/9684
See https://github.com/autowarefoundation/autoware.universe/pull/9684
None.
None.
> feat: remove admissible_{position/yaw}_error from trajectory_follower

- autoware_launch/config/control/trajectory_follower/longitudinal/pid.param.yaml
This PR change the slope compensation mode to trajectory_goal_adaptive
universe PR: https://github.com/autowarefoundation/autoware.universe/pull/9705
psim and tier4 scenario tests
None.
None.
> feat(pid_longitudinal_controller): change slope compensation mode to trajectory_goal_adaptive

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/detection_area.param.yaml
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/9802
None.
None.
> feat: remove enable_rtc from detection_area

- autoware_launch/rviz/autoware_test_utils.rviz
related to this https://github.com/autowarefoundation/autoware.universe/pull/9925
None.
None.
> chore(autoware_test_utils): add test_utils rviz config

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
Add parameter for specifying lane change path sampling time limit, related to following PR:
https://github.com/autowarefoundation/autoware.universe/pull/9908
- PSIM.
None.
None.
> feat(lane_change): add time limit param

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/stop_line.param.yaml
Removed unnecessary parameters which are not used
None.
None.
> fix: remove unnecesary parameters

- .github/CODEOWNERS-manual
Add P/C team's member to the codeowner-manual
None.
None.
> chore(planning): add p/c maintainers

- autoware_launch/package.xml
Apply package name change.
https://github.com/autowarefoundation/autoware.universe/pull/9965.
Check rosdep install.
None.
None.
> feat: apply autoware prefix for adapi helpers

- autoware_launch/launch/components/tier4_system_component.launch.xml
Apply package name change.
https://github.com/autowarefoundation/autoware.universe/pull/9961
Launch planning simulation.
None.
None.
> feat: apply autoware prefix for state monitor

- autoware_launch/config/planning/preset/default_preset.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/motion_velocity_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/obstacle_cruise.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/obstacle_slow_down.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/obstacle_stop.param.yaml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
- autoware_launch/rviz/autoware.rviz
Update autoware.rviz for motion_velocity_obstacle_<stop/slow_down/cruise>_module for the following PRs
https://github.com/autowarefoundation/autoware.universe/pull/10035
https://github.com/autowarefoundation/autoware.universe/pull/9807
Issue:
https://github.com/autowarefoundation/autoware.universe/issues/10036
None.
None.
> feat(rviz): update autoware.rviz for motion_velocity_obstacle_<stop/slow_down/cruise>_module

- autoware_launch/launch/components/tier4_perception_component.launch.xml
Change tlr pedestrian classifier model
Related link https://github.com/autowarefoundation/autoware.universe/pull/10116
https://evaluation.ci.tier4.jp/evaluation/reports/e7ce0622-19ed-53ac-8406-4f1d8e3caabd?project_id=prd_jt
None.
None.
> feat(tier4_perception_component): change tlr pedestrian classifier model

- .github/CODEOWNERS-manual
Remove Miura from the maintainer list.
No test
None.
None.
> chore: refine perception related code owner

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
see https://github.com/autowarefoundation/autoware.universe/pull/10118
see https://github.com/autowarefoundation/autoware.universe/pull/10118
None.
None.
> feat(goal_planner): align vehicle center to be parallel to lane boundary

- autoware_launch/config/localization/ekf_localizer.param.yaml
Please see https://github.com/autowarefoundation/autoware.core/pull/211
Please see https://github.com/autowarefoundation/autoware.core/pull/211
None.
None.
> chore(ekf_localizer): increase z_filter_proc_dev for large gradient road

- autoware_launch/config/perception/object_recognition/detection/image_projection_based_fusion/fusion_common.param.yaml
I have created a [PR](https://github.com/autowarefoundation/autoware.universe/pull/10016) for redesigning the fusion node, resulting in different parameter settings.
None.
None.
> feat(image_based_projection_fusion): update parameters for new image based projection fusion node

- autoware_launch/config/control/control_validator/control_validator.param.yaml
follow a universe PR: https://github.com/autowarefoundation/autoware.universe/pull/10236
None.
None.
> feat(control_validator)!: add overrun_stop_point_dist parameter

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/drivable_area_expansion.param.yaml
modify drivable area expansion parameters due to changes in the following PR:
https://github.com/autowarefoundation/autoware.universe/pull/10220
N/A
None.
None.
> feat(behavior_path_planner_common): update drivable area expansion parameters

- autoware_launch/config/planning/scenario_planning/common/planning_validator/planning_validator.param.yaml
Add threshold for the yaw deviation metric.
Related universe PR: https://github.com/autowarefoundation/autoware.universe/pull/10258
Psim
None.
None.
> feat(planning_validator): add parameter for yaw deviation metric

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/out_of_lane.param.yaml
Add parameter required by https://github.com/autowarefoundation/autoware.universe/pull/9584
> feat(out_of_lane): add 'use_map_stop_lines' parameter

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/obstacle_stop.param.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/10269
None.
None.
> feat(autoware_launch): rename to max_lat_margin_against_predicted_object_unknown

- .github/CODEOWNERS-manual
- autoware_launch/CHANGELOG.rst
- autoware_launch/config/localization/ekf_localizer.param.yaml
- autoware_launch/config/perception/object_recognition/prediction/map_based_prediction.param.yaml
- autoware_launch/config/perception/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml
- autoware_launch/config/perception/occupancy_grid_map/pointcloud_based_occupancy_grid_map.param.yaml
- autoware_launch/config/perception/traffic_light_multi_camera_fusion/traffic_light_multi_camera_fusion.param.yaml
- autoware_launch/config/planning/preset/default_preset.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/traffic_light.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/motion_velocity_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/obstacle_cruise.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/obstacle_slow_down.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/obstacle_stop.param.yaml
- autoware_launch/launch/autoware.launch.xml
- autoware_launch/launch/components/tier4_perception_component.launch.xml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
- autoware_launch/launch/e2e_simulator.launch.xml
- autoware_launch/package.xml
- autoware_launch/rviz/autoware.rviz
This syncs humble branch up to d4fc23e3aa46f5a266b9e985855ec1b27c745c10 in main branch.
None.
None.
> chore: bump version to 0.42.0

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
launcher update for https://github.com/autowarefoundation/autoware_universe/pull/10294
same to https://github.com/autowarefoundation/autoware_universe/pull/10294
None.
None.
> feat(goal_planner): expand outer collision check margin

- autoware_launch/config/perception/object_recognition/detection/image_projection_based_fusion/roi_pointcloud_fusion.param.yaml
- Update parameter for roi_pointcloud_fusion which is added by https://github.com/autowarefoundation/autoware_universe/pull/10333
None.
None.
> fix(roi_pointcloud_fusion): add roi scale factor param

- autoware_launch/config/perception/object_recognition/prediction/map_based_prediction.param.yaml
This PR adds the parameter for diagnostics introduced by https://github.com/autowarefoundation/autoware.universe/pull/10219
[TIER IV INTERNAL LINK](https://evaluation.ci.tier4.jp/evaluation/reports/17102d51-5559-59b2-b142-9d0a0ad25eac?project_id=prd_jt)
None.
None.
> feat: add parameter for diagnostics

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
necaessary change for the [PR](https://github.com/autowarefoundation/autoware_universe/pull/10321)
Description is writtent in the pr.
Described in the [PR](https://github.com/autowarefoundation/autoware_universe/pull/10321)
None.
None.
> feat(start/goal_planner): update max steer angle parameters to use margin scale

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/detection_area.param.yaml
- See https://github.com/autowarefoundation/autoware_universe/pull/10376
None.
None.
> fix(detection_area): integrate RTC feature

- sensor_kit/awsim_labs_sensor_kit_launch/awsim_labs_sensor_kit_description/package.xml
- sensor_kit/awsim_labs_sensor_kit_launch/awsim_labs_sensor_kit_launch/package.xml
- sensor_kit/awsim_labs_sensor_kit_launch/common_awsim_labs_sensor_launch/package.xml
- sensor_kit/awsim_sensor_kit_launch/awsim_sensor_kit_description/package.xml
- sensor_kit/awsim_sensor_kit_launch/awsim_sensor_kit_launch/package.xml
- sensor_kit/sample_sensor_kit_launch/common_sensor_launch/package.xml
- sensor_kit/sample_sensor_kit_launch/sample_sensor_kit_description/package.xml
- sensor_kit/sample_sensor_kit_launch/sample_sensor_kit_launch/package.xml
- sensor_kit/single_lidar_sensor_kit_launch/single_lidar_common_launch/package.xml
- sensor_kit/single_lidar_sensor_kit_launch/single_lidar_sensor_kit_description/package.xml
- sensor_kit/single_lidar_sensor_kit_launch/single_lidar_sensor_kit_launch/package.xml
- vehicle/awsim_labs_vehicle_launch/awsim_labs_vehicle_description/package.xml
- vehicle/awsim_labs_vehicle_launch/awsim_labs_vehicle_launch/package.xml
- vehicle/sample_vehicle_launch/sample_vehicle_description/package.xml
- vehicle/sample_vehicle_launch/sample_vehicle_launch/package.xml
Since we have moved different versioned packages here, this PR sets them all to the parent package version.
This will make it easier to resolve conflicts once we make the patch PR.
Related:
- https://github.com/autowarefoundation/autoware_launch/pull/1369
None.
None.
> chore: set all versions to 0.43.0

- autoware_launch/config/perception/object_recognition/tracking/multi_object_tracker/multi_object_tracker_node.param.yaml
universe PR
https://github.com/autowarefoundation/autoware_universe/pull/10301
None.
None.
> feat(multi_object_tracker): add diagnostics warning when extrapolation time exceeds limit with latency guarantee enabled

- autoware_launch/config/perception/object_recognition/detection/lidar_model/centerpoint_common.param.yaml
This PR adds a common parameter file for the `lidar_centerpoint` package to introduce diagnostics.
See https://github.com/autowarefoundation/autoware_universe/pull/10284
This PR must merge with https://github.com/autowarefoundation/autoware_universe/pull/10396
Checked by running a sample ROS bag and confirmed that it can read the parameter file properly with https://github.com/autowarefoundation/autoware_universe/pull/10396 .
None.
None.
> feat(lidar_centerpoint): add common param file

- autoware_launch/config/perception/object_recognition/tracking/multi_object_tracker/multi_object_tracker_node.param.yaml
PR https://github.com/autowarefoundation/autoware_universe/pull/10431
Implementing time keeper for processing time analysis
```
ros2 run autoware_debug_tools processing_time_visualizer 
```
```
🌲 Total Processing Time Tree 🌲
100.00% onTimer: total 4816.24 [ms], avg. 4.20 [ms], run count: 1148
├── 99.73% checkAndPublish: total 4803.33 [ms], avg. 40.36 [ms], run count: 119
│   ├── 59.38% prune: total 2859.67 [ms], avg. 24.03 [ms], run count: 119
│   │   ├── 0.13% removeOldTracker: total 6.22 [ms], avg. 0.05 [ms], run count: 119
│   │   ├── 59.23% removeOverlappedTracker: total 2852.50 [ms], avg. 23.97 [ms], run count: 119
│   │   └── 0.02% rest: 0.95 [ms]
│   ├── 40.30% publish: total 1940.76 [ms], avg. 16.31 [ms], run count: 119
│   │   ├── 1.10% getTrackedObjects: total 53.05 [ms], avg. …
```
> feat(multi_object_tracker): add detailed processing time publishing option

- sensor_kit/awsim_labs_sensor_kit_launch/awsim_labs_sensor_kit_launch/config/concatenate_and_time_sync_node.param.yaml
- sensor_kit/awsim_sensor_kit_launch/awsim_sensor_kit_launch/config/concatenate_and_time_sync_node.param.yaml
- sensor_kit/sample_sensor_kit_launch/sample_sensor_kit_launch/config/concatenate_and_time_sync_node.param.yaml
Remove unused parameter.
**Order of PRs merge:**
- https://github.com/autowarefoundation/autoware/pull/5611
- https://github.com/autowarefoundation/autoware_utils/pull/41
- https://github.com/autowarefoundation/autoware_universe/pull/9197
- https://github.com/autowarefoundation/autoware_core/pull/360
- https://github.com/autowarefoundation/autoware_launch/pull/1393 `<---`
None.
None.
> chore(sensor_kit_launch): remove unused has_static_tf_only param

- autoware_launch/config/perception/object_recognition/detection/lidar_model/transfusion_common.param.yaml
This PR adds a common parameter file for the `lidar_transfusion` package to introduce diagnostics.
See https://github.com/autowarefoundation/autoware_universe/pull/10398
This PR must merge with https://github.com/autowarefoundation/autoware_universe/pull/10434
None.
None.
> feat(lidar_transfusion): add transfusion common param file

- autoware_launch/config/planning/scenario_planning/common/planning_validator/planning_validator.param.yaml
necessary change for the [PR](https://github.com/autowarefoundation/autoware_universe/pull/10438)
None.
None.
> refactor(planning_validator): separate validation check for steering and steering rate

- autoware_launch/config/control/control_validator/control_validator.param.yaml
add params for new feature
unvierse PR: https://github.com/autowarefoundation/autoware_universe/pull/10422
None.
None.
> feat(control_validator): add over run estimation feature

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/out_of_lane.param.yaml
Apply config changes required by following out_of_lane PR's:
- https://github.com/autowarefoundation/autoware_universe/pull/10446
- https://github.com/autowarefoundation/autoware_universe/pull/10447
- https://github.com/autowarefoundation/autoware_universe/pull/10448
- PSIM
None.
None.
> feat(out_of_lane): improve out of lane stability

- autoware_launch/config/planning/scenario_planning/common/planning_validator/planning_validator.param.yaml
necessary change for https://github.com/autowarefoundation/autoware_universe/pull/10440
explained in the autoware_universe side PR
None.
None.
> feat(planning_validator): add lateral jerk validation parameters

- autoware_launch/config/planning/preset/default_preset.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/run_out.param.yaml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
- autoware_launch/rviz/autoware.rviz
Add parameters for the new `run_out` module of the `motion_velocity_planner`.
Required for https://github.com/autowarefoundation/autoware_universe/pull/10388
- [TIER IV INTERNAL LINK](https://evaluation.tier4.jp/evaluation/reports/38a857f7-4d11-504a-aedd-660d122ac448?project_id=prd_jt)
None.
None. (the new module is currently disabled by default)
> feat(mvp_run_out): update for new motion_velocity_planner run_out

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/motion_velocity_planner.param.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/out_of_lane.param.yaml
launcher changes for https://github.com/autowarefoundation/autoware_core/pull/377
https://evaluation.tier4.jp/evaluation/reports/1eb4e631-9375-5403-a5e7-0b19c4f963a6/?page=1&project_id=prd_jt
None.
None.
> feat(autoware_motion_velocity_planner): point-cloud clustering optimization

- autoware_launch/config/perception/traffic_light_recognition/traffic_light_selector/traffic_light_selector.param.yaml
- autoware_launch/launch/components/tier4_perception_component.launch.xml
This PR remove config file and delete path description in launcher caused by https://github.com/autowarefoundation/autoware_universe/pull/10352
https://evaluation.ci.tier4.jp/evaluation/reports/258eb2c9-e19c-59e7-b84c-821f07e8ac75?project_id=prd_jt
None.
None.
> feat(traffic_light): remove unnecessary config file

- autoware_launch/config/control/operation_mode_transition_manager/operation_mode_transition_manager.param.yaml
launcher change for https://github.com/autowarefoundation/autoware_universe/pull/10457
See https://github.com/autowarefoundation/autoware_universe/pull/10457
None.
None.
> feat: add input_timeout in operation_mode_transition_manager

- autoware_launch/launch/components/tier4_simulator_component.launch.xml
This PR remove params of traffic_light_selector.
https://github.com/autowarefoundation/autoware_universe/pull/10352
None.
None.
> chore(simulator.launch): remove params of traffic_light_selector

- autoware_launch/config/perception/object_recognition/detection/lidar_model/bevfusion_camera_lidar.param.yaml
- autoware_launch/config/perception/object_recognition/detection/lidar_model/bevfusion_common.param.yaml
- autoware_launch/config/perception/object_recognition/detection/lidar_model/bevfusion_lidar.param.yaml
Added the corresponding bevfusion config files
Related PR: https://github.com/autowarefoundation/autoware_universe/pull/10541
Launcher bevfusion by setting the model to `bevfusion/bevfusion_lidar` instead of the default centerpoint
None.
None.
> feat(autoware_bevfusion): added bevfusion config files

- sensor_kit/awsim_labs_sensor_kit_launch/common_awsim_labs_sensor_launch/config/ring_outlier_filter_node.param.yaml
- sensor_kit/sample_sensor_kit_launch/common_sensor_launch/config/ring_outlier_filter_node.param.yaml
- sensor_kit/single_lidar_sensor_kit_launch/single_lidar_common_launch/config/ring_outlier_filter_node.param.yaml
This PR relates to https://github.com/autowarefoundation/autoware_universe/pull/10537
None.
None.
> feat(ring_outlier_filter): update node parameters

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/static_obstacle_avoidance.param.yaml
See https://github.com/autowarefoundation/autoware_universe/pull/10585.
See https://github.com/autowarefoundation/autoware_universe/pull/10585.
None.
None.
> feat(static_obstacle_avoidance): add flag to wait approval when the ego uses opposite lane

- autoware_launch/config/perception/occupancy_grid_map/multi_lidar_pointcloud_based_occupancy_grid_map.param.yaml
Please see this https://github.com/autowarefoundation/autoware_universe/pull/10578
Please see this https://github.com/autowarefoundation/autoware_universe/pull/10578
None.
None.
> fix(probabilistic_occupancy_grid_map): add missing parameter for multi-lidar 

- autoware_launch/launch/components/tier4_perception_component.launch.xml
- Add parameter for https://github.com/autowarefoundation/autoware_universe/pull/10609
None.
None.
> fix(tier4_perception_launch): add camera ids param for segmentation_pointcloud_fusion

- autoware_launch/config/system/diagnostics/autoware-main.yaml
- autoware_launch/config/system/diagnostics/localization.yaml
- autoware_launch/config/system/diagnostics/planning.yaml
Use diags added by following PRs:
- https://github.com/autowarefoundation/autoware_universe/pull/10550
- https://github.com/autowarefoundation/autoware_universe/pull/10539
Check that the vehicle drives in autonomous mode using planning simulator.
None.
None.
> feat(autoware_launch): update adapi diags

- autoware_launch/config/control/control_validator/control_validator.param.yaml
This PR adds lateral jerk threshould for steering rate validation
necessary change for the [PR](https://github.com/autowarefoundation/autoware_universe/pull/10619)
None.
None.
> feat(control_validator): add lateral jerk validation

- autoware_launch/config/control/autoware_collision_detector/collision_detector.param.yaml
Rename parameters for https://github.com/autowarefoundation/autoware_universe/pull/10651
Evaluator (all pass):
- [TIER IV internal link](https://evaluation.tier4.jp/evaluation/reports/cf3e136f-c2fe-5e42-9c30-c46600d073e3?project_id=prd_jt)
None.
None.
> fix(collision_detector): rename parameters to prevent launch issues

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
follow universe PR: https://github.com/autowarefoundation/autoware_universe/pull/10439
see universe PR
None.
> feat(crosswalk): update stop position logic

- autoware_launch/config/perception/traffic_light_recognition/traffic_light_map_based_detector/camera6_traffic_light_map_based_detector.param.yaml
- autoware_launch/config/perception/traffic_light_recognition/traffic_light_map_based_detector/camera7_traffic_light_map_based_detector.param.yaml
- autoware_launch/config/perception/traffic_light_recognition/traffic_light_map_based_detector/traffic_light_traffic_light_map_based_detector.param.yaml
This PR add comment in config of autoware_traffic_light_map_based_detector to understand clearly.
Related PR : https://github.com/autowarefoundation/autoware_universe/pull/10353
None.
None.
> chore(traffic_light_recognition): add comment in config of autoware_traffic_light_map_based_detector

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/obstacle_stop.param.yaml
Launch changes for https://github.com/autowarefoundation/autoware_core/pull/451
None.
None.
> feat(obstacle_stop_module): maintain larger stop distance for opposing traffic

- autoware_launch/config/planning/preset/default_preset.yaml
- autoware_launch/config/system/processing_time_checker/processing_time_checker.param.yaml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
- autoware_launch/rviz/autoware.rviz
Removed obstacle_stop_planner and obstacle_cruise_planner following the issue below.
https://github.com/autowarefoundation/autoware_universe/issues/10641
None.
None.
> feat!: remove obstacle_stop_planner and obstacle_cruise_planner

- autoware_launch/rviz/autoware.rviz
organize the planning info/debug topics in autoware.rviz
The debug markers will locate in the "Debug" directory.
None.
None.
> refactor(rviz): organize planning info/debug topics

- autoware_launch/config/perception/object_recognition/detection/irregular_object_detection/irregular_object_detector.param.yaml
- Add option parameter for https://github.com/autowarefoundation/autoware_universe/pull/10655
None.
None.
> fix(irregular_object_detector): add param for roi_pointcloud

- autoware_launch/rviz/autoware.rviz
- I often want to display vehicle acceleration information as debugging information, so update the rviz configuration.
- For the directory structure, added `Vehicle` to the Debug folder similar to other components, and added Info and Debug.
None.
None.
> feat(rviz): add AccelerationMeter display configuration to RViz

- autoware_launch/config/perception/object_recognition/detection/detected_object_validation/object_lanelet_filter.param.yaml
- autoware_launch/config/perception/object_recognition/detection/object_filter/object_lanelet_filter.param.yaml
- autoware_launch/config/perception/object_recognition/detection/object_filter/radar_lanelet_filter.param.yaml
This PR will add a lanelet object elevation filter option to configs.
see: https://github.com/autowarefoundation/autoware_universe/pull/10649
None.
None.
> feat(autoware_detected_object_validation): add lanelet object elevation filter option

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
Add parameters for https://github.com/autowarefoundation/autoware_universe/pull/10667
Psim
None.
None (the new feature is disabled by default).
> feat(crosswalk_module): add parked vehicles stop feature

- autoware_launch/config/perception/traffic_light_recognition/crosswalk_traffic_light_estimator/crosswalk_traffic_light_estimator.param.yaml
See https://github.com/autowarefoundation/autoware_universe/pull/10763
See  https://github.com/autowarefoundation/autoware_universe/pull/10763
None.
None.
> feat(perception): add parameters to use pedestrian traffic signal result estimated in perception pipeline

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/run_out.param.yaml
Required for https://github.com/autowarefoundation/autoware_universe/pull/10754
[TIER IV Evaluator](https://evaluation.tier4.jp/evaluation/reports/3ac53984-eb09-5dcc-b6ff-7b4b00722122?project_id=prd_jt).
None.
None.
> feat(run_out): option to preserve parts of ignored predicted paths

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/path_generator/path_generator.param.yaml
update for https://github.com/autowarefoundation/autoware_core/pull/511 
psim
None.
None.
> fix(path_generator): ensure refined path connects start and goal

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/behavior_velocity_planner.param.yaml
launcer update for https://github.com/autowarefoundation/autoware_core/pull/513
psim 
None.
None.
> feat(planning_factor): add console output option

- autoware_launch/launch/components/tier4_simulator_component.launch.xml
This PR is a `humble` backport of #1479 .
> feat: add pointcloud container arg for simulator component (#1479)

- autoware_launch/config/planning/preset/default_preset.yaml
- autoware_launch/config/planning/scenario_planning/common/planning_validator/collision_checker.param.yaml
- autoware_launch/config/planning/scenario_planning/common/planning_validator/intersection_collision_checker.param.yaml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
Add parameter file for new `planning_validator` sub module `collision_checker`.
universe PR: https://github.com/autowarefoundation/autoware_universe/pull/10750
see universe PR
None.
None.
> feat(planning_validator): implement collision prevention feature when ego makes a turn

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/detection_area.param.yaml
launcher update for https://github.com/autowarefoundation/autoware_universe/pull/10797
same to https://github.com/autowarefoundation/autoware_universe/pull/10797
None.
None.
> feat(detection_area): improve log message

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
Rename parameter in crosswalk_module,
See https://github.com/autowarefoundation/autoware_universe/pull/10759 in detail.
None.
None.
> fix(crosswalk_module): rename parameters in crosswalk_module

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/static_obstacle_avoidance.param.yaml
- https://github.com/autowarefoundation/autoware_universe/pull/10813
None.
None.
> fix(autoware_static_obstacle_avoidance): fix classification method of unstable object

- autoware_launch/config/planning/preset/default_preset.yaml
- autoware_launch/config/planning/scenario_planning/common/planning_validator/rear_collision_checker.param.yaml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
See https://github.com/autowarefoundation/autoware_universe/pull/10800
None.
None.
> feat(planning_validator): add new validation feature

- autoware_launch/launch/autoware.launch.xml
- autoware_launch/launch/components/tier4_autoware_api_component.launch.xml
- autoware_launch/launch/components/tier4_control_component.launch.xml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
This PR cherry-picks the following PR.
See following link to check details.
https://github.com/autowarefoundation/autoware_launch/pull/1469
I check running planning simulator.
None.
None.
> feat(launch/components): launch in a component-wise manner

- autoware_launch/config/perception/object_recognition/detection/image_projection_based_fusion/roi_cluster_fusion.param.yaml
- To align with change in https://github.com/autowarefoundation/autoware_universe/pull/10833
None.
None.
> fix(roi_cluster_fusion): rename param

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/traffic_light.param.yaml
- https://github.com/autowarefoundation/autoware_universe/pull/10768
None.
None.
> feat(autoware_behavior_velocity_traffic_light_module): add v2i 

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
before this PR:
https://github.com/user-attachments/assets/009c163d-e73a-4aec-872c-b845ad17ab32
after this PR:
https://github.com/user-attachments/assets/a6319e74-76ad-43a6-93fe-dc1d7d206edd
None.
None.
> feat(intersection): more conservative stop for NOT_PRIORITIZED

- autoware_launch/config/system/processing_time_checker/processing_time_checker.param.yaml
launcher update for https://github.com/autowarefoundation/autoware_core/pull/549
same to https://github.com/autowarefoundation/autoware_core/pull/549
None.
None.
> feat(path_generator): publish processing time

- autoware_launch/config/planning/scenario_planning/common/planning_validator/intersection_collision_checker.param.yaml
update `intersection_collision_checker` param yaml, required by following PR.
https://github.com/autowarefoundation/autoware_universe/pull/10839
None.
None.
> feat(intersection_collision_checker): update config

- autoware_launch/config/perception/object_recognition/tracking/multi_object_tracker/multi_object_tracker_node.param.yaml
1. let user select if estimate motion (velocity) of unknown object or not.
2. adjust object shape (footprint) to be aligned to the input detected object
* before
try to estimate its shape, extrapolate by time. therefore, the cluster and the tracked object shape are not matched
https://github.com/user-attachments/assets/503cd104-2bba-4acb-a9c8-4b7a57ae4915
* after (with velocity estimation)
it tracks position and velocity, but the shape is originated by the latest measurement. no shape extrapolation by time.
the cluster and the tracked object shape are matched all the time
https://github.com/user-attachments/assets/2c28ddf8-8777-412c-92b3-2ed1fa1304f3
* after (static motion model)
it dose not estimate velocity. 
the cluster and the tracked object shape are matched all the time …
> feat(autoware_multi_object_tracker): unknown as static object

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/static_obstacle_avoidance.param.yaml
See https://github.com/autowarefoundation/autoware_universe/pull/10870
None.
None.
> feat(static_obstacle_avoidance): support separate lateral jerk constraints for avoidance and return maneuvers

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
see https://github.com/autowarefoundation/autoware_universe/pull/10868
see https://github.com/autowarefoundation/autoware_universe/pull/10868
None.
None.
> feat(intersection_occlusion): adjustable occlusion wall position for intersection without traffic_light

- autoware_launch/config/perception/object_recognition/tracking/multi_object_tracker/multi_object_tracker_node.param.yaml
Disabling debug object of the multi object tracker, since the performance impact is not negligible.
```
🌲 Total Processing Time Tree 🌲
100.00% onTrigger: total 2689.73 [ms], avg. 13.65 [ms], run count: 197
├── 59.29% runProcess: total 1594.85 [ms], avg. 5.19 [ms], run count: 307
│   ├── 1.18% predict: total 31.71 [ms], avg. 0.10 [ms], run count: 307
│   ├── 40.73% associate: total 1095.64 [ms], avg. 3.57 [ms], run count: 307
│   │   ├── 30.79% calcScoreMatrix: total 828.07 [ms], avg. 2.70 [ms], run count: 307
│   │   ├── 9.88% assign: total 265.80 [ms], avg. 0.87 [ms], run count: 307
│   │   └── 0.07% rest: 1.76 [ms]
│   ├── 3.25% update: total 87.43 [ms], avg. 0.28 [ms], run count: 307
│   ├── 6.20% prune: total 166.90 [ms], avg. 0.54 [ms], run count: 307
│   │   ├── 0.33% …
```
> fix(multi_object_tracker): disable debug markers in configuration for improved performance

- autoware_launch/launch/components/tier4_perception_component.launch.xml
- autoware_launch/launch/components/tier4_sensing_component.launch.xml
This PR is for sensing/perception components of https://github.com/autowarefoundation/autoware_launch/pull/1469.
- https://github.com/autowarefoundation/autoware/pull/6225
None.
None.
> feat(launch/components): launch `autoware_global_parameter_loader` in a component-wise manner

- autoware_launch/rviz/autoware.rviz
visualize all static_obstacle_avoidance info marker
See https://github.com/autowarefoundation/autoware_universe/pull/10729 in detail.
None.
None.
> feat: visualize all static_obstacle_avoidance info marker

- autoware_launch/launch/components/tier4_perception_component.launch.xml
- autoware_launch/launch/components/tier4_sensing_component.launch.xml
This PR addresses the issue https://github.com/autowarefoundation/autoware_launch/pull/1513#issuecomment-3011027954 from @technolojin.
None.
None.
> chore: remove default values of `pointcloud_container_name`

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
Add curvature threshold for frenet planner
Related PR: https://github.com/autowarefoundation/autoware_universe/pull/10920
None.
None.
> fix(lane_change): add curvature threshold for frenet planner

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/obstacle_stop.param.yaml
add new parameters for the core PR https://github.com/autowarefoundation/autoware_core/pull/537
see the core PR
psim and tier4 scenario tests
Real vehicle testing
None.
None.
> feat(obstacle_stop_module)!: add leading vehicle following by rss stop position determination

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
see https://github.com/autowarefoundation/autoware_universe/pull/10947
see https://github.com/autowarefoundation/autoware_universe/pull/10947
None.
None.
> feat(intersection_occlusion): request approval when occluded without traffic light

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/detection_area.param.yaml
The parameters were adjusted to be more appropriate.
https://tier4.atlassian.net/browse/RT1-10612
- https://evaluation.tier4.jp/evaluation/reports/52b71197-6cc7-54c9-888e-03d089d8642b?project_id=prd_jt
None.
None.
> fix(detection_area): change max_acceleration of detection_area module

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/path_generator/path_generator.param.yaml
:warning: **This PR must be merged at the same time with https://github.com/autowarefoundation/autoware_core/pull/564** :warning:
This PR renames a parameter for goal connection feature of `path_generator`.
See https://github.com/autowarefoundation/autoware_core/pull/564 for details.
None.
None.
> feat(path_generator): improve goal connection for goal on the side

- autoware_launch/config/planning/scenario_planning/common/planning_validator/rear_collision_checker.param.yaml
See https://github.com/autowarefoundation/autoware_universe/pull/10992
None.
None.
> feat(rear_collision_checker): added a parameter to configure how many seconds ahead to predict collisions

- autoware_launch/config/planning/scenario_planning/common/planning_validator/intersection_collision_checker.param.yaml
update intersection collision checker params. required by https://github.com/autowarefoundation/autoware_universe/pull/11030
None.
None.
> feat(intersection_collision_checker): update intersection collision checker params

- sensor_kit/awsim_labs_sensor_kit_launch/awsim_labs_sensor_kit_launch/launch/pointcloud_preprocessor.launch.py
- sensor_kit/awsim_sensor_kit_launch/awsim_sensor_kit_launch/launch/pointcloud_preprocessor.launch.py
- sensor_kit/sample_sensor_kit_launch/sample_sensor_kit_launch/launch/pointcloud_preprocessor.launch.py
Simple update of new output topic for pointcloud preprocessor.
Introduced in https://github.com/autowarefoundation/autoware_universe/pull/10851.
None.
None.
> feat(autoware_pointcloud_preprocessor): add remappings

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
- See https://github.com/autowarefoundation/autoware_universe/pull/11027
None.
None.
> feat(crosswalk): improve robustness to prevent stop decision from being canceled by transient noise

- autoware_launch/config/perception/object_recognition/tracking/multi_object_tracker/data_association_matrix.param.yaml
- autoware_launch/config/perception/object_recognition/tracking/multi_object_tracker/multi_object_tracker_node.param.yaml
please see https://github.com/autowarefoundation/autoware_universe/pull/11036
None.
None.
> feat(multi_object_tracker): add generalized iou thresholds and overlap distance thresholds

- autoware_launch/config/perception/object_recognition/detection/object_merger/ml_camera_lidar_object_association_merger.param.yaml
- autoware_launch/launch/components/tier4_perception_component.launch.xml
- Update launch and add parameter file for https://github.com/autowarefoundation/autoware_universe/pull/11042
None.
None.
> fix(object_merger): update launch and add param file

- autoware_launch/config/perception/object_recognition/prediction/map_based_prediction.param.yaml
- See https://github.com/autowarefoundation/autoware_universe/pull/11028.
None.
None.
> feat(map_based_prediction): prevent predicted path from chattering under noisy pose and velocity estimation

- autoware_launch/config/planning/preset/default_preset.yaml
- See https://github.com/autowarefoundation/autoware_universe/pull/11052
None.
None.
> feat(launch): add flag to launch remaining distance calculator

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
necessary change for https://github.com/autowarefoundation/autoware_universe/pull/11040
None.
None.
> feat(start_planner): add clothoid path parameters

- autoware_launch/config/control/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml
necessary change for https://github.com/autowarefoundation/autoware_universe/pull/11057
None.
None.
> feat(autoware_vehicle_cmd_gate): steer rate limit with lateral jerk constraint

- autoware_launch/config/planning/scenario_planning/common/planning_validator/intersection_collision_checker.param.yaml
Add parameter `max_history_time` to configure max valid age of tracked object data before its discarded.
None.
None.
> feat(intersection_collision_checker): add parameter max_history_time

- autoware_launch/config/planning/scenario_planning/common/planning_validator/rear_collision_checker.param.yaml
- See https://github.com/autowarefoundation/autoware_universe/pull/11067
None.
None.
> refactor(rear_collision_checker): update parameter structure

- autoware_launch/config/planning/preset/default_preset.yaml
- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/road_user_stop.param.yaml
- autoware_launch/launch/components/tier4_planning_component.launch.xml
- autoware_launch/rviz/autoware.rviz
See https://github.com/autowarefoundation/autoware_universe/pull/11041 in detail.
None.
None.
> feat(road_user_stop): add road_user_stop module config

- autoware_launch/config/planning/scenario_planning/common/planning_validator/rear_collision_checker.param.yaml
- See https://github.com/autowarefoundation/autoware_universe/pull/11072
None.
None.
> feat(rear_collision_checker): support selecting safety metric from TTC or RSS

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/blind_spot.param.yaml
see https://github.com/autowarefoundation/autoware_universe/pull/11079
see https://github.com/autowarefoundation/autoware_universe/pull/11079
None.
None.
> feat(blind_spot): new re-designed blind_spot module

- autoware_launch/config/perception/object_recognition/tracking/multi_object_tracker/input_channels.param.yaml
- Add parameter for PR https://github.com/autowarefoundation/autoware_universe/pull/11102
None.
None.
> fix(multi_object_tracker): add param for irregular_object

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/motion_velocity_planner.param.yaml
follow the core PR : https://github.com/autowarefoundation/autoware_core/pull/591
The effect on system behavior is negligible.
see core PR
None.
None.
> feat(motion_velocity_planner): update pointcloud preprocess design

- autoware_launch/config/system/component_state_monitor/topics.yaml
- autoware_launch/launch/autoware.launch.xml
- autoware_launch/rviz/autoware.rviz
- autoware_launch/rviz/autoware_test_utils.rviz
- autoware_launch/rviz/perception.rviz
- autoware_launch/rviz/planning_bev.rviz
- autoware_launch/rviz/planning_tpv.rviz
- autoware_launch/rviz/scenario_simulator.rviz
This is the PR corresponding to phase 2. This PR is scheduled to be merged on August 11.
https://github.com/autowarefoundation/autoware/issues/6292
Please refer to this.
https://github.com/autowarefoundation/autoware/issues/6292#issuecomment-3166352528
None.
None.
> feat: change planning output topic name to /planning/trajectory

- autoware_launch/config/planning/scenario_planning/common/planning_validator/rear_collision_checker.param.yaml
See https://github.com/autowarefoundation/autoware_universe/pull/11151
None.
None.
> feat(rear_collision_checker): add new parameters

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/boundary_departure_prevention.param.yaml
Enable slow down feature for boundary departure
[FuncVerificationScenario_Basic](https://evaluation.tier4.jp/evaluation/reports/c9536130-dbc4-5921-8ea1-e31411eae4b6?project_id=prd_jt)
[CommonScenario_Basic](https://evaluation.tier4.jp/evaluation/reports/1821bb30-5025-5f8e-bb73-c893023028f4?project_id=prd_jt)
None.
None.
> feat(boundary_departure): enable slow down feature

- autoware_launch/rviz/autoware.rviz
Enable virtual wall for boundary departure slow down.
None.
None.
> chore(boundary_departure): add rviz marker for slow down

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/obstacle_stop.param.yaml
scc core PR: https://github.com/autowarefoundation/autoware_core/pull/590
None.
None.
> feat(obstacle_stop): add velocity estimation feature for point cloud

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/blind_spot.param.yaml
https://github.com/autowarefoundation/autoware_universe/pull/11234
see https://github.com/autowarefoundation/autoware_universe/pull/11234
None.
None.
> feat(blind_spot): add the flag to ignore non vru

- autoware_launch/config/planning/scenario_planning/common/planning_validator/intersection_collision_checker.param.yaml
- autoware_launch/config/planning/scenario_planning/common/planning_validator/planning_validator.param.yaml
See https://github.com/autowarefoundation/autoware_universe/pull/11238
None.
None.
> fix(intersection_collision_checker): use traffic light context for intersection collision detection

- autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/obstacle_stop.param.yaml
follow core PR: https://github.com/autowarefoundation/autoware_core/pull/619
see core PR
None.
None.
> feat(motion_velocity_planner_common):  lateral margin adjustment for the ego's curvature and target obstacle motion

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
necessary parameter change for https://github.com/autowarefoundation/autoware_universe/pull/11275
None.
None.
> feat(start_planner): prioritize planner type with list

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
parameters update for https://github.com/autowarefoundation/autoware_universe/pull/11287
same to https://github.com/autowarefoundation/autoware_universe/pull/11287
None.
None.
> feat(goal_planner): make parameters for stopping buffer

- autoware_launch/config/localization/pose_instability_detector.param.yaml
This PR adds a new parameter `enable_validation` to the pose_instability_detector so that the validation can be toggled by each dimension (x, y, z, roll, pitch and yaw).
Please look https://github.com/autowarefoundation/autoware_universe/pull/11298
Please look https://github.com/autowarefoundation/autoware_universe/pull/11298
This PR should be merged with https://github.com/autowarefoundation/autoware_universe/pull/11298
None.
> feat(pose_instability_detector): add enable_validation param to pose_instability_detector

- sensor_kit/awsim_labs_sensor_kit_launch/awsim_labs_sensor_kit_launch/launch/imu.launch.xml
- sensor_kit/awsim_sensor_kit_launch/awsim_sensor_kit_launch/launch/imu.launch.xml
- sensor_kit/sample_sensor_kit_launch/sample_sensor_kit_launch/launch/imu.launch.xml
This PR includes the necessary modifications to run with the latest changes of the autoware_imu_corrector
None.
None.
> chore: necessary mod to run with latest gyro scale estimation changes

- autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
add backward depth parameter for roundabout turn signal
related PR: https://github.com/autowarefoundation/autoware_universe/pull/11235
psim
this pr should be merged before https://github.com/autowarefoundation/autoware_universe/pull/11235
None.
> feat(turn_signal_decider): add backward depth parameter for roundabout turn signal
