autowarefoundation/autoware_launch

autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/logging_simulator.launch.xml
autoware_launch/launch/planning_simulator.launch.xml

Adjusted the interface to https://github.com/autowarefoundation/autoware.universe/pull/443.

fix: fix launch args

---

autoware_launch/launch/logging_simulator.launch.xml

Signed-off-by: Yukihiro Saito <yukky.saito@gmail.com>
Fixed incorrect arguments and including launch.
The logging simulator does not launch the vehicle interface since the vehicle interface often requires the connection of a real machine.
~In other words, the logging simulator is out of the scope of the vehicle interface test.
If you want to test it, you can do so by setting this to true, but the default is false. This will be considered depending on future requests.~ …

fix: incorrect arguments and including launch

---

autoware_launch/rviz/autoware.rviz

**Note**: Confirm the [contribution guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/) before submitting a pull request.
Click the `Preview` tab and select a PR template:
- [Standard change](?expand=1&template=standard-change.md)
- [Small change](?expand=1&template=small-change.md)
**Do NOT send a PR with this description.**

feat(autoware_launch): update autoware.rviz not to visualize obstacle_avoidance_planner markers

---

autoware_launch/rviz/autoware.rviz

disable namespace
- center_line_arrows, https://github.com/autowarefoundation/autoware.universe/pull/931
- lane_start_bound, https://github.com/autowarefoundation/autoware.universe/pull/923

feat: disable some namespace for lanelet2

---

autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/logging_simulator.launch.xml
autoware_launch/rviz/autoware.rviz

Signed-off-by: Tomohito Ando <tomohito.ando@tier4.jp>
add arguments for pointcloud container to planning.launch.xml to run compare map filter in container.
https://github.com/TomohitoAndo/autoware.universe/blob/feature/dynamic_obstacle_stop/launch/tier4_planning_launch/launch/scenario_planning/lane_driving.launch.xml#L21-L26
https://github.com/autowarefoundation/autoware.universe/pull/752
I confirmed `voxel_based_compare_map_filter_node` was in `pointcloud_constainer` when the argument is true.
This PR should be merged with this PR.
https://github.com/autowarefoundation/autoware.universe/pull/752
The PR author **must** check the checkboxes below …

feat: add arguments for pointcloud container to planning

---

autoware_launch/rviz/autoware.rviz

Signed-off-by: h-ohta <hiroki.ota@tier4.jp>
disable lane_start_bound namespace in mission_planner

fix(mission_planner): disable lane_start_bound in Rviz

---

autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/logging_simulator.launch.xml
autoware_launch/launch/planning_simulator.launch.xml

Signed-off-by: tanaka3 <ttatcoder@outlook.jp>
Without this PR, we cannot designate use_sim_time by ros2 launch
With this PR fix use sim time option for planning simulator and logging simulator
I confirm use sim time is correctly set with simulation clock rviz plugin
https://user-images.githubusercontent.com/65527974/181677348-ada9f356-d719-4f0f-b884-0012e23a630b.mp4 …

fix: use sim time option

---

autoware_launch/rviz/autoware.rviz

- add debug markers for scene modules of `behavior_path_planner` (hide markers as default)
- add dummy 2d bus into top bar as default

feat(rviz): update rviz planning module's debug marker

---

autoware_launch/launch/autoware.launch.xml

designate vehicle_id in tier4_control_launch

chore(autoware_launch): designate vehicle_id to tier4_control_launch

---

autoware_launch/launch/autoware.launch.xml
autoware_launch/package.xml

Move adapi adaptor to add a dedicated launch flag.
https://github.com/autowarefoundation/autoware/discussions/2868
https://github.com/autowarefoundation/autoware.universe/pull/1900

feat: move adapi rviz adaptor 

---

autoware_launch/launch/planning_simulator.launch.xml

Explained in https://github.com/autowarefoundation/autoware_launch/issues/94

fix(autoware_launch): launch dummy_localization regardless of scenario_simulation flag

---

autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/e2e_simulator.launch.xml
autoware_launch/launch/logging_simulator.launch.xml
autoware_launch/launch/planning_simulator.launch.xml

Signed-off-by: Berkay Karaman <berkay@leodrive.ai>
This PR about adding obstacle_collision_checker to control.launch.py. This will be optional.
This PR should merge after https://github.com/autowarefoundation/autoware.universe/pull/2193 merged!

feat(autoware_launch): add obstacle_collision_checker to launch

---

autoware_launch/rviz/autoware.rviz

Signed-off-by: Berkay Karaman <berkay@leodrive.ai>
In current rviz file, `pure_pursuit` debug topic name is wrong. I want to change it.

refactor(autoware_launch): change pure_pursuit debug marker topic name

---

autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/planning_simulator.launch.xml

Signed-off-by: Azumi Suzuki <azumi.suzuki@tier4.jp>
Set `use_external_emergency_stop` to false by default when launching planning_simulator.
Please review with related PR: 
https://github.com/autowarefoundation/autoware.universe/pull/2155
TIER IV INTERNAL LINK
https://tier4.atlassian.net/browse/T4PB-21179
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contrib …

feat: set use_external_emergency_stop to false by default when launching psim

---

autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/e2e_simulator.launch.xml
autoware_launch/launch/logging_simulator.launch.xml
autoware_launch/launch/planning_simulator.launch.xml

Signed-off-by: ito-san <fumihito.ito@tier4.jp>
Add launch parameter to launch system_monitor or not.
The system monitor should be configured according to system configuration but it it difficult to cover all system configurations all over the world, so we made the system_monitor optional.
- The system_monitor launches by default but it does not launch in planning_simulator, logging_simulator, and e2e_simulator.
https://github.com/autowarefoundation/autoware.universe/issues/630
The same tests were done described in https://github.com/autowarefoundation/autoware.universe/pull/2285.
Please see this PR for details.
Here is related PR that should be merged at the same time.
https://github.com/autowarefoundation/autoware.universe/pull/2285
The PR author **must** check the checkboxes below when …

fix(autoware_launch): add parameter to launch launch_system_monitor

---

autoware_launch/launch/autoware.launch.xml

Currently, Autoware has a web controller. In the early days, Autoware was controlled via web controller.
https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/launch/autoware.launch.xml#L145
However, Now that the autoware state rviz plugin has been introduced, the need for web controller seems to have disappeared.
https://github.com/orgs/autowarefoundation/discussions/3082 …

feat: remove web controller

---

autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/planning_simulator.launch.xml

See https://github.com/autowarefoundation/autoware.universe/pull/2455

fix: rename use_external_emergency_stop to check_external_emergency_heartbeat

---

autoware_launch/CMakeLists.txt
autoware_launch/config/map/pointcloud_map_loader.param.yaml
autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/components/tier4_map_component.launch.xml

Signed-off-by: kminoda <koji.minoda@tier4.jp>
Move config to autoware_launch.
Two PRs should be merged at the same time.
- https://github.com/autowarefoundation/autoware.universe/pull/2538
- https://github.com/autowarefoundation/autoware_launch/pull/128
https://github.com/autowarefoundation/autoware_launch/issues/66
Please refer to the PR in autoware.universe …

feat(autoware_launch): move config from autoware.universe for map

---

autoware_launch/CMakeLists.txt
autoware_launch/config/control/common/nearest_search.param.yaml
autoware_launch/config/control/components/tier4_control_component.launch.xml
autoware_launch/config/control/lane_departure_checker/lane_departure_checker.param.yaml
autoware_launch/config/control/obstacle_collision_checker/obstacle_collision_checker.param.yaml
autoware_launch/config/control/operation_mode_transition_manager/operation_mode_transition_manager.param.yaml
autoware_launch/config/control/shift_decider/shift_decider.param.yaml
autoware_launch/config/control/trajectory_follower/lateral_controller.param.yaml
autoware_launch/config/control/trajectory_follower/longitudinal_controller.param.yaml
autoware_launch/config/control/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml
autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/components/tier4_control_component.launch.xml

Move config to autoware_launch.
Two PRs should be merged at the same time.
https://github.com/autowarefoundation/autoware.universe/pull/2544
https://github.com/autowarefoundation/autoware_launch/issues/66
Launch planning_simulator.launch.xml and verified that all the nodes in /control/* are launched successfully.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main …

feat(autoware_launch): move config from autoware.universe for control

---

autoware_launch/config/perception/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml

Signed-off-by: badai-nguyen <dai.nguyen@tier4.jp>
This PR to extend the detection region of ground segmentation. As the result, it also extend the region of perception module. The computational cost has been discussed at this [PR](https://github.com/autowarefoundation/autoware.universe/pull/2521#issue-1502492084)
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main …

feat(perception): change detection region

---

autoware_launch/config/control/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml

Parameter in vehicle_cmd gate is missing due to https://github.com/autowarefoundation/autoware.universe/pull/2585

fix(autoware_launch): add missing param of vehicle_cmd_gate in yaml

---

autoware_launch/config/control/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml
autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/components/tier4_control_component.launch.xml

Depending on the physical vehicles' characteristics or how much the vehicle was tuned, the lateral/longitudinal controller sometimes has to be tuned for individual vehicles.
To enable this individual tuning for the controller, I added a flag `use_individual_control_param` set to false by default.
- When `use_individual_control_param` is true
- lateral/longitudinal controller param path is `autoware_launch/config/control/trajectory_follower/$(var vehicle_id)`
- When `use_individual_control_param` is false
- lateral/longitudinal controller param path is `autoware_launch/config/control/trajectory_follower/`
**TODO**
The PR author **must** check the …

feat(autoware_launch): enable use_individual_control_param

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/behavior_velocity_planner.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/speed_bump.param.yaml
autoware_launch/launch/components/tier4_planning_component.launch.xml

This PR adds speed bump config file path description to `tier4_planning_component` launch file.
https://github.com/autowarefoundation/autoware.universe/pull/647
Config file is read as it is intended. Changes some parameters in config file to make sure that everything works as expected. 
**This PR needs to be merged before** [speed bump PR](https://github.com/autowarefoundation/autoware.universe/pull/647)
To test this PR:
Follow the[ test steps in speed bump PR](https://github.com/autowarefoundation/autoware.universe/pull/647#:~:text=Notes%20for%20reviewers-,Test%20Method,-If%20autowarefoundation/autoware_common)
Change some parameters in config file and observe the expected changes (using debud markers in rviz)
The PR …

feat(autoware_launch): add speed bump parameters

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

Signed-off-by: satoshi-ota <satoshi.ota928@gmail.com>
I'll add new logic in the avoidance module (behavior_path_planner). 
Parameter description is [here](https://github.com/autowarefoundation/autoware.universe/pull/2515).
- https://github.com/autowarefoundation/autoware.universe/pull/2515
- [[TIER IV INTERNAL LINK]](https://github.com/tier4/autoware_launch/pull/657) …

feat(avoidance): add new param for yield maneuver in avoidance module

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/drivable_area_expansion.param.yaml

Signed-off-by: Maxime CLEMENT <maxime.clement@tier4.jp>
Add parameters for the feature newly added to universe (https://github.com/autowarefoundation/autoware.universe/pull/2288#).

feat(behavior_path_planner): param to skip some linestring types when expanding the drivable area

---

autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/components/tier4_planning_component.launch.xml

The wrong parameter name was merged with the following PR.
https://github.com/autowarefoundation/autoware_launch/pull/165
Renamed to use_experimental_lane_change_function, which is correct.
Relates to https://github.com/autowarefoundation/autoware.universe/pull/2676 …

fix(autoware_launch): fix wrong parameter name

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_out/pull_out.param.yaml

launcher update of https://github.com/autowarefoundation/autoware.universe/pull/2675
psim

feat(behavior_path_planner): ignore pull out start near lane end

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml

This PR adds a new parameter for fitting_uniform_circle configuration for mpt optimizer.
**Related links:**
- https://github.com/autowarefoundation/autoware.universe/pull/2646
- https://github.com/orgs/autowarefoundation/discussions/3189

feat(autoware_launch): add fitting_uniform_circle parameter for mpt

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

Signed-off-by: Mehmet Dogru <42mehmetdogru42@gmail.com>
Remove redundant parameters from bpp-avoidance config file regarding:
https://github.com/orgs/autowarefoundation/discussions/3207#discussioncomment-4704021

refactor(autoware_launch/bpp-avoidance): remove redundant parameters

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml

Signed-off-by: Muhammad Zulfaqar Azmi <zulfaqar.azmi@tier4.jp>
Fix default parameter issues when merging previous lane change parameter PR

fix(lane_change): fix default abort param

---

autoware_launch/config/planning/scenario_planning/common/motion_velocity_smoother/motion_velocity_smoother.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_out/pull_out.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_over/pull_over.param.yaml

change default parameters:
- min_curve_velocity: since the current value is too slow for the passenger vehicle (bus/taxi, etc), it is increased to 10km/h. 

fix(autoware_launch): change planning parameters

---

autoware_launch/config/planning/scenario_planning/common/planning_validator/planning_validator.param.yaml
autoware_launch/launch/components/tier4_planning_component.launch.xml

Add plannig_validator related param. See https://github.com/autowarefoundation/autoware.universe/pull/1947 for details
same as https://github.com/tier4/autoware_launch/pull/675

feat(autoware_lauch): modify launch for planning_validator

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml

Signed-off-by: beyza <bnk@leodrive.ai>
This PR adds parameters for considering footprint edges to autoware_launch/config
[1999](https://github.com/autowarefoundation/autoware.universe/pull/1999
)

feat(autoware_launch): add param for considering footprint edges when check the drivable area

---

autoware_launch/launch/components/tier4_autoware_api_component.launch.xml

This flag has to be enabled to make autoware work with scenario_simulator

fix(autoware_launch): enable launch_deprecated_api

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_out/pull_out.param.yaml

launcher update for https://github.com/autowarefoundation/autoware.universe/pull/2700
psim 

fix(behavior_path_planner): prevent pull out back twice

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml

Signed-off-by: Mamoru Sobue <mamoru.sobue@tier4.jp>
Add param for the overshoot from stuck stop line that was previously hardcoded
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/2756

feat(intersection): add param for stuck stopline overshoot margin

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/behavior_velocity_planner.param.yaml

Signed-off-by: Muhammad Zulfaqar Azmi <zulfaqar.azmi@tier4.jp>
This PR aims to disable occlusion spot module by default.
The occlusion spots feature was introduced to decelerate anticipating people jumping out from behind nearby vehicles, but it causes unnecessary slowing down in multi-lane driving. This design issue has yet to be fixed.
Due to the issue, currently, some functional test are facing complication. To reduce this occurrence, occlusion spot is disabled. …

fix(occlusion_spot): occlusion spot parameter disable as default

---

autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/components/tier4_planning_component.launch.xml

clean up autoware.launch.xml regarding tier4_planning_component

fix(autoware_launch): minor change with tier4_planning_component

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

Because safety check is now adaptive, we dont need lane change safety check time anymore.
Also the parameter reflected current stable lane change parameter that was used in odaiba test.

fix(lane_change): update default parameter

---

autoware_launch/config/localization/ndt_scan_matcher.param.yaml
autoware_launch/config/map/pointcloud_map_loader.param.yaml

See https://github.com/autowarefoundation/autoware.universe/pull/2339

feat(autoware_launch): add NDT parameters for dynamic_map_loading

---

autoware_launch/config/planning/scenario_planning/common/common.param.yaml
autoware_launch/config/planning/scenario_planning/common/motion_velocity_smoother/motion_velocity_smoother.param.yaml

The maximum speed with the current planning parameter is about 40km/h. This limit mainly comes from
- Maximum acceleration limit,
- Maximum jerk limit, and
- Trajectory length in motion_velocity_smoother`.
This PR changes the acceleration and jerk limit, which was very small, and slightly makes the trajectory longer internally used in `motion_velocity_smoother` to achieve 60km/h speed.
This change slightly increases the CPU cost (40% -> 45% of one core in the attached movie).
https://user-images.githubusercontent.com/21360593/216321628-d264c3fd-ed89-4707-8239-55f831edbf41.mp4
[TIERIV INTERNAL LINK](https://tier4.atlassian.net/browse/T4PB-20279)
Psim & real vehicle 
The PR reviewers **must** check the checkboxes below …

feat(planning_config): update params to enable 60kmph speed

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml

Signed-off-by: Mamoru Sobue <mamoru.sobue@tier4.jp>
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/2859

fix(behavior_velocity_planner): continue collision checking after pass judge

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop_planner.param.yaml

Signed-off-by: beyza <bnk@leodrive.ai>
This PR adds parameters for using predicted objects to autoware_launch/config
https://github.com/autowarefoundation/autoware.universe/pull/2290

feat(autoware_launch): add param for configurable lateral_distance

---

autoware_launch/launch/components/tier4_planning_component.launch.xml

The smoother parameters for behavior_velocity and motion_velocity_smoother are vice versa

fix(autoware_launch): fix the planning param

---

autoware_launch/config/system/system_error_monitor/diagnostic_aggregator/system.param.yaml
autoware_launch/launch/components/tier4_system_component.launch.xml

Currently, autoware_launch cannot be launched due to the following error. :bow: 
I removed the necessary file and setting by mistake in this PR.
I reverted the change.
I confirmed planning simulator worked well.

fix(autoware_launch): add missing system file

---

autoware_launch/config/control/lane_departure_checker/lane_departure_checker.param.yaml

With this [PR](https://github.com/autowarefoundation/autoware.universe/pull/2709) we added some options about which lanes should be included to drivable area borders.

feat(lane_departure_checker): add optional neighbor lanelets parameters

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/adaptive_cruise_control.param.yaml

Add erased deform values as parameters.

fix(obstacle_stop_planner): add lacking param

---

autoware_launch/launch/autoware.launch.xml

Fixed the wrong commit in https://github.com/autowarefoundation/autoware_launch/pull/207.

fix(autoware_launch): use tier4_sensing_component.launch.xml

---

autoware_launch/rviz/autoware.rviz

Added a walkway visualization, which was removed by mistake.

fix(autoware_launch): add walkway visualization

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_over/pull_over.param.yaml

`maximum_deceleration: 1.0` of pull_over sometimes causes a sudden stop in the latter module.
https://user-images.githubusercontent.com/39142679/221588989-a2e13c5e-7164-4bed-a005-8f44ceb548ca.mp4
scenario test
[TIER IV internal scenario test](https://evaluation.tier4.jp/evaluation/reports/3af5348f-d4dc-59ce-8f96-9ba25452f99d?project_id=prd_jt) 
875/877 -> 876/877
https://user-images.githubusercontent.com/39142679/221589034-5754c204-0882-4a32-b6d8-c52564b22940.mp4 …

fix(behavior_path_planner): change pull over maximum_deceleration

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

Change safety_check_backward_distance value from 50m to 100m according to the perception module.
( The value of ```min_x```, distance of backward point cloud used by perception module, was changed from 50m to 100m [here](https://github.com/autowarefoundation/autoware_launch/pull/141) )
https://github.com/autowarefoundation/autoware_launch/pull/141 …

feat: lengthen safety_check_backward_distance in avoidance module

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml

:arrow_down: PR for autoware.universe
https://github.com/autowarefoundation/autoware.universe/pull/2987
add config for avoidance on new framework
```yaml
...
avoidance:
enable_module: true
enable_simultaneous_execution: false
priority: 0
max_module_size: 1
```

feat(avoidance): add config for new framework

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml

launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/2800
NOTE: Akima spline is disabled by default.

feat(autoware_launch): add option to use akima spline at first

---

autoware_launch/rviz/autoware.rviz

- add path marker config for path reference of behavior path planner.
- the marker is hided as default.
---
- **translucent purple**: reference path
- **translucent green**: behavior output path

feat(rviz): add path reference marker

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml

This PR is related to new framework in behavior path planner.
The objective of this PR is as follow
1. supporting `external_lane_change` module in the new framework.
2. separating `lane_change` module to `lane_change_left` and `lane_change_right`

feat(lane_change): support param for new framework (include external lc)

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/behavior_velocity_planner.param.yaml

Closes: https://github.com/autowarefoundation/autoware.universe/issues/2390

fix(behavior_velocity_planner): disable launch_virtual_traffic_light parameter by default

---

autoware_launch/config/control/autonomous_emergency_braking/autonomous_emergency_braking.param.yaml
autoware_launch/launch/components/tier4_control_component.launch.xml
autoware_launch/rviz/autoware.rviz

Add parameters for autonomous emergency braking

feat(control_launch): add parameter for aeb

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml

Disable external lane change module by default in the new behavior path planner architecture.
https://github.com/autowarefoundation/autoware.universe/pull/3068#issuecomment-1475117823

fix(planning_launch): disable external lc module in new framework

---

autoware_launch/config/control/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml
autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/components/tier4_control_component.launch.xml

add check_external_emergency_heartbeat option to designate it at runtime.
launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/3079

feat(autoware_launch): add check_external_emergency_heartbeat option

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_following/lane_following.param.yaml

closes https://github.com/autowarefoundation/autoware.universe/issues/2125
parameters for https://github.com/autowarefoundation/autoware.universe/pull/2732 & https://github.com/autowarefoundation/autoware_common/pull/148

feat(lane_following): consider lane ego angle diff

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/blind_spot.param.yaml

feature PR: https://github.com/autowarefoundation/autoware.universe/pull/3175
https://tier4.atlassian.net/browse/T4PB-24187

feat(behavior_velocity_planner::blind_spot): consider adjacent lane

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance_by_lc/avoidance_by_lc.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/scene_module_manager.param.yaml
autoware_launch/launch/components/tier4_planning_component.launch.xml
autoware_launch/rviz/autoware.rviz

- https://github.com/autowarefoundation/autoware.universe/pull/3125

feat(avoidance_by_lc): add new module to avoid obstacle by lane change

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/scene_module_manager.param.yaml

Following modules can run simultaneously.
- avoidance
- lane_change_right
- lane_change_left

feat(behavior_path_planner): enable LC+Avoidacne simultaneous execution

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

Remove an unnecessary parameter and add target object parameters

fix(behavior_path_planner): remove unnecessary lane change parameter

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

refactor(behavior_path_planner): rename lane change parameters

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

Rename some lane change parameters. Use `velocity` rather than `speed` and `segment` rather than `phase`.

refactor(behavior_path_planner): rename lane chagne parameters

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/traffic_light.param.yaml

feature PR: https://github.com/autowarefoundation/autoware.universe/pull/3407
In Psim
Removed deprecated topic `~/input/external_{intersection, crosswalk, traffic_light}_status`.
No influence on current system configuration

refactor(behavior_velocity_planner): removed external input from behavior_velocity

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml

Organized param file for intersection module for readability
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/3409
Both intersection/merge_from_private module works without throwing ros parameter exceptions.
None

refactor(behavior_velocity_planner::intersection): organize param intersection

---

autoware_launch/config/perception/occupancy_grid_map/laserscan_based_occupancy_grid_map.param.yaml
autoware_launch/config/perception/occupancy_grid_map/pointcloud_based_occupancy_grid_map.param.yaml
autoware_launch/launch/components/tier4_perception_component.launch.xml
autoware_launch/launch/components/tier4_simulator_component.launch.xml

add occupancy_grid_map method/param var to launcher and use those ones in autoware_launch by default
Just like other packages I changed the auoware_launch to refer to launcher param file.
universe PR: https://github.com/autowarefoundation/autoware.universe/pull/3393
Psim works as before.
None
None
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pu …

refactor(occupancy_grid_map): add occupancy_grid_map method/param var to launcher

---

autoware_launch/launch/components/tier4_simulator_component.launch.xml
autoware_launch/launch/planning_simulator.launch.xml

PR universe: https://github.com/autowarefoundation/autoware.universe/pull/3457
In current implementation of autoware, dummy_perception_publisher always uses the baselink z position while publishing dummy object. Object's Z position can not be arranged from rviz plugin. I added a parameter to make it configurable. Default value of the parameter is true.
[pull request …

feat(tier4_simulator_launch): add use_baselink_z option for dummy_perception_publisher

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
autoware_launch/rviz/autoware.rviz

Remove `lane changing length` parameter from the planning launch parameter file.

refactor(planning_launch): remove minimum lane changing length

---

autoware_launch/rviz/autoware.rviz

With the following PR, the path width is calculated automatically from the global parameters' vehicle width.
https://github.com/autowarefoundation/autoware.universe/pull/3504
However, the predicted trajectory from the lateral controller is supposed to be thin as follows.
The white trajectory is the predicted trajectory.
**with this PR**
**without this PR**
planning simulator works well
Nothing
[pull …

chore(autoware_launch): visualize thin predicted trajectory on rviz

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml

launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/3098
planning simulator worked well.
Nothing. (When avoiding obstacles by motion_planner, the sudden steering behavior can be suppressed.)

feat(autoware_launch): add time to fix reference points's boundary width

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

For avoidance by the motion_planner, we keep an attention of obstacles to avoid longer.
planning simulator worked well.
Nothing.

chore(autoware_launch): make backward detection length for avoidance longer

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/drivable_area_expansion.param.yaml

launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/3499
planning simulator worked well.
Nothing.

feat(autoware_launch): make drivable area expansion parameters common

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/rtc_auto_mode_manager/rtc_auto_mode_manager.param.yaml

add intersection occlusion param
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/3458
see the feature PR
None
A topic /planning/cooperate_status/intersection_occlusion is newly added
If enabled, the vehicle will stop in the intersection if occlusion is detected.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request- …

feat(behavior_velocity_planner::intersection): add occlusion detection feature

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml

launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/3510
planning simulator works well
If intersection occlusion is enabled, the creep velocity for intersection occlusion will not be used.

feat(intersection): add flag to enable creep towards intersection occlusion

---

autoware_launch/rviz/autoware.rviz

Add lane_change candidate path visualization for behavior path planning old architecture
1. compile behavior path planner in old architecture.
2. set lane change RTC approval to manual.
3. visualize lane change path

fix(autoware_launch): old architecture lane change path in rviz

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

Remove redundant parameters from the lane change parameter files.

refactor(planning_launch): use common params for lane change

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/scene_module_manager.param.yaml

launcher update for https://github.com/autowarefoundation/autoware.universe/pull/3481
psim, scenario test
no
can run avoidance and pull out simultaneously

feat(behavior_path_planner): run avoidance and pull out simultaneously

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml

Tuned intersection parameters
In the following video the ray-trace origin of occupancy grid map is `velodyne_top` and ego is able to autonomously handle the static occlusion.
https://user-images.githubusercontent.com/28677420/234277148-b45a0110-5a9b-425c-8001-51024961eeae.mp4
Only when the occlusion feature for the intersection module works, a behavior changes a bit. …

chore(autoware_launch): tune intersection parameters

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml

Remove duplicated lane change parameter, i.e. `lane_change_prepare_duration`.

refactor(planning_launch): remove duplicated lane change parameter

---

autoware_launch/rviz/autoware.rviz

Add debug marker box for intersection occlusion grid.
`grid_map_rviz_plugin` should be installed manually or by `rosdep install`.
https://github.com/autowarefoundation/autoware.universe/pull/3509
To view this check the "IntersectionOcclusion" box.
Not applicable
Not applicable
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines …

feat(behavior_velocity_planner::intersection): add intersection occlusion gridmap marker

---

autoware_launch/config/control/trajectory_follower/lateral/mpc.param.yaml

Current MPC's parameters seem to stick to decrease a lateral error too much lacking steering angle stability.
Since the path changes dynamically in complicated environments and the path may have a bit high curvature, MPC's stability against a more unstable path is important as follows.
https://www.youtube.com/watch?v=opqtckENIs8&amp;ab_channel=ApolloAuto&ab_channel=ApolloAuto
With this PR, MPC
- can still make a small tracking error
- is not so sensitive to a more unstable path (the dynamic path change and a bit high curvature)
(Hard to see the difference from the video though)
The following is a case of avoidance by obstacle_avoidance_planner which has a bit high curvature.
The critical difference is when returning to the reference path after avoidance. Without this PR, the steering …

perf(mpc_lateral_controller): mpc works more stably

---

autoware_launch/rviz/autoware.rviz

add interface in order to publish marker that is always shown in rviz
- https://github.com/autowarefoundation/autoware.universe/pull/3580
Psim
Nothing.

feat(behavior): add interface in order to publish marker that is always shown in rviz

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml

launcher update for https://github.com/autowarefoundation/autoware.universe/pull/3610
https://github.com/autowarefoundation/autoware.universe/pull/3610
psim
scenario tests
nothing
nothing

refactor(behavior_path_planner): refactoring goal_planner and pull_out params

---

autoware_launch/rviz/autoware.rviz

- behavior path module outputs important module's information, and that are shown in Rviz by default.
- avoidance module outputs `avoidable_target_objects` and `unavoidable_target_objects` marker as important information.
- hide detail information of the `avoidable_target_objects` and `unavoidable_target_objects`.
- https://github.com/autowarefoundation/autoware.universe/pull/3582
Psim
Nothing.
[pull …

feat(avoidance): hide detail information

---

autoware_launch/rviz/autoware.rviz

revert two PRs
- https://github.com/autowarefoundation/autoware_launch/pull/333
- https://github.com/autowarefoundation/autoware_launch/pull/339

fix(behavior): don't show behaivor module's marker

---

autoware_launch/rviz/autoware.rviz

rviz change for https://github.com/autowarefoundation/autoware.universe/pull/3658
By default, no additional visualization.
planning simulator
Can visualize dynamic objects to avoid

feat(autoware_launch): add marker of dynamic avoidance

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop_planner.param.yaml

https://github.com/autowarefoundation/autoware.universe/pull/3558
It adds distance threshold parameter for filtering in that PR.

feat(obstacle_stop_planner): add filtering feature for predicted objects

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

- rename `avoidance_execution_lateral_threshold` -> `lateral_execution_threshold`.
- remove `lateral_passable_safety_buffer` and use each objects' `safety_buffer_lateral` instead.
- https://github.com/autowarefoundation/autoware.universe/pull/3623
Evaluator
Nothing.

refactor(avoidance): remove redundant parameter

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

Add maximum and minimum longitudinal acceleration for the lane change

feat(planning_launch): add maximum and minimum longitudinal acceleration for the lane change

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml

Add the option to publish intersection_occlusion grid when intersection_occlusion feature is enabled.
universe PR: https://github.com/autowarefoundation/autoware.universe/pull/3844
On Psim

fix(intersection): add the flag for intersection_occlusion grid publication

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml

`margin_from_boundary`: 0.5 -> 0.75
The motivation of this change is to prevent the ego from going out of the drivable area by control error.
Test with real vehicle

feat(behavior_path_planner): relax margin_from_boundary in goal_planner param

---

autoware_launch/launch/components/tier4_planning_component.launch.xml

Replace duplicated config path with a common arg.

refactor(autoware_launch): remove duplicated path in planning launch

---

autoware_launch/config/perception/object_recognition/detection/roi_sync.param.yaml
autoware_launch/launch/components/tier4_perception_component.launch.xml

This PR add a copy of [roi_sync.param.yaml](https://github.com/autowarefoundation/autoware.universe/blob/main/perception/image_projection_based_fusion/config/roi_sync.param.yaml) to [here](https://github.com/autowarefoundation/autoware_launch/tree/main/autoware_launch/config/perception/object_recognition/detection), and pass those parameters to `tier4_perception_launch`
This PR and [another](https://github.com/autowarefoundation/autoware.universe/pull/3713) are intended to solve the problem mentioned  [here](https://github.com/orgs/autowarefoundation/discussions/3465#discussioncomment-5869137)
The PR author **must** …

fix(tier4_perception_component_launch): add sync_param_path

---

autoware_launch/config/control/trajectory_follower/lateral/mpc.param.yaml

launcher update for https://github.com/autowarefoundation/autoware.universe/pull/2454
I checked psim and tier4 [internal scenario test](https://evaluation.tier4.jp/evaluation/reports/7e93224f-887c-58c0-bc9d-419cf720d66e?project_id=prd_jt) (1326/1372->1329/1372), and it worked fine.
not applicable 
not applicable 
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main …

fix(trajectory_follower_nodes): mpc_follower does not send proper converged data under low steering rate limit

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml

Parameterize `longitudinal_velocity_delta_time` in the behavior path planner node for safe lane change. 
RSS check only secure the future distance, therefore, even when RSS logic returns safe, we cannot guarantee that the physical distance between real vehicle is safe. Originally the value is fixed to `0.8` but there might be necessity to reduce or increase the value depending on situation.
Update the YAML file, the parameter struct, the node constructor, and the safety check function to use the new parameter.
After all checkboxes are checked, anyone …

fix(planning_launch): parameterize scale for lc safety check

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/behavior_velocity_planner.param.yaml
autoware_launch/launch/components/tier4_planning_component.launch.xml

From this comment: https://github.com/autowarefoundation/autoware_launch/pull/369#issuecomment-1581173744. Load all module parameters by default. The user only needs to edit `launch_modules`.

refactor(behavior_velocity_planner): load all module parameters

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/scene_module_manager.param.yaml

add parameter `enable_rtc`
if true, the scene modules should be approved by rtc. if false, the module can be run without approval from rtc.
merge with this [PR](https://github.com/autowarefoundation/autoware.universe/pull/3894)

feat(behavior_path_planner): add flag to enable auto mode without rtc_auto_mode_manager

---

autoware_launch/config/perception/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml

because elevation grid is too small for vls 16 I fix this bug for awsim
/perception/obstacle_segmentation/range_cropped/pointcloud
/perception/obstacle_segmentation/single_frame/pointcloud_raw
before this PR
after this PR
https://github.com/autowarefoundation/autoware_launch/assets/65527974/b1f3dd4a-bf80-43c1-bdb9-c5008f4fb125
[Internal](https://tier4.atlassian.net/browse/AT-136)
by awsim
perception module …

fix: ground_segmentation.param for vls16

---

autoware_launch/config/control/autonomous_emergency_braking/autonomous_emergency_braking.param.yaml

https://github.com/autowarefoundation/autoware.universe/pull/3292
Add missing parameter in autonomous_emergency_braking.param.yaml for fixing the following error.
```
'autoware::motion::control::autonomous_emergency_braking::AEB' in container '/control/control_container': Component constructor threw an exception: Statically typed parameter 'collision_keeping_sec' must be initialized.
```
Not applicable. (AEB can start normally by this fix. ) …

fix(autoware_launch): add missing parameter in autonmous emergency braking

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml

refactor
https://github.com/autowarefoundation/autoware.universe/pull/3899
See https://github.com/autowarefoundation/autoware.universe/pull/3899

refactor: intersection module

---

autoware_launch/rviz/autoware.rviz

Add flag to control crosswalk areas visualization.
Psim
Nothing.

feat(rviz): hide crosswalk areas

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

- https://github.com/autowarefoundation/autoware.universe/pull/3855
Nothing.

feat(avoidance): additional buffer for perception noise

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

update for  https://github.com/autowarefoundation/autoware.universe/pull/4026
https://github.com/autowarefoundation/autoware.universe/pull/4026
psim
none 
none

feat(start_planner): add length_ratio_for_turn_signal_deactivation_near_intersection

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml

If a stuck vehicle is detected in private intersection lane, cancel the stop decision after a specified period.
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/4022
In Psim

feat(intersection): timeout stuck vehicle stop in private area

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

Enable avoidance for unknown object.
](https://evaluation.tier4.jp/evaluation/reports/5cefba5d-0920-5304-98d2-a66c4938a5a3?project_id=prd_jt)
Enable avoidance for unknown object.

feat(avoidance): enable avoidance for unknown object

---

autoware_launch/config/perception/occupancy_grid_map/binary_bayes_filter_updater.param.yaml
autoware_launch/config/perception/occupancy_grid_map/laserscan_based_occupancy_grid_map.param.yaml
autoware_launch/config/perception/occupancy_grid_map/pointcloud_based_occupancy_grid_map.param.yaml

A minor change of launcher for changing "updater_type" from upper stream launch configuration.
https://github.com/autowarefoundation/autoware.universe/pull/4063
Both Psim and Lsim works

fix(occupancy grid): fix launcher

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml

The relationship between the parameter use_stuck_stopline and corresponding behavior of Autoware was reversed
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/4086
refer to https://github.com/autowarefoundation/autoware.universe/pull/4086
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-r …

fix(behavior_velocity_intersection_module): fix condition of use_stuck_stopline

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

Update following params:
- use_constraints_for_decel: false -> true
- don't allow sudden stop even when there is object that should be avoid.
- lateral_execution_threshold: 0.499 -> 0.09
- it can output small shift avoidance path.
- quantize_filter_threshold: 0.2 -> 0.1
- it can output small shift avoidance path.
- don't allow sudden stop even when there is object that should be avoid.
- it can output small shift avoidance path. …

feat(avoidance): update avoidance params

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml

Currently, the leaves of trees are recognized as unknown objects in some cases, resulting in slowdown by obstacle_cruise_planner.
To suppress this unnecessary slowdown, I set a default slow down feature for unknown object false.
planning simulator
No slow down against unknown object
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guid …

feat(autoware_launch): no slow down against unknown object

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

See https://github.com/autowarefoundation/autoware.universe/pull/4150.
Psim
Nothing.

fix(avoidance): don't output new candidate path if there is huge offset between the ego and previous output path

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

Enable to use hatched road marking in avoidance module.
See https://github.com/orgs/autowarefoundation/discussions/3414
Make it possible to use hatched road marking area in avoidance module.

feat(avoidance): enable zebra zone avoidance

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

add parameter for https://github.com/autowarefoundation/autoware.universe/pull/4263
see https://github.com/autowarefoundation/autoware.universe/pull/4263
see https://github.com/autowarefoundation/autoware.universe/pull/4263

feat(start_planner): add curvature limit for path generation

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml

launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4211
The behavior won't change with those PRs.
See https://github.com/autowarefoundation/autoware.universe/pull/4211
See https://github.com/autowarefoundation/autoware.universe/pull/4211

feat(autoware_launch): add disable_stop_for_yield_cancel in crosswalk

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

See https://github.com/autowarefoundation/autoware.universe/pull/4294
Psim
Nothing.

refactor(avoidance): update parameter names

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/occlusion_spot.param.yaml

Close https://github.com/autowarefoundation/autoware.universe/issues/4192
Nothing.
Nothing.

fix(occlusion_spot): add lacking param

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml

parameter for https://github.com/autowarefoundation/autoware.universe/pull/4305
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/4305
See feature PR: https://github.com/autowarefoundation/autoware.universe/pull/4305
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request- …

feat(intersection): add behavior for arrow signal

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

Add flags for the safety check in the lane change module to enable the user to select whether they want to use objects on the specific lanes.

feat(planning_launch): add safety check flags for lane change

---

autoware_launch/config/perception/object_recognition/prediction/map_based_prediction.param.yaml
autoware_launch/launch/components/tier4_perception_component.launch.xml

This PR adds map_based_prediction.param.yaml to autoware_launch config directory
- https://github.com/autowarefoundation/autoware.universe/pull/4337
Releated: 
- https://github.com/autowarefoundation/autoware.universe/issues/4250

refactor(autoware_launch): add map_based_prediction param file

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml

This PR is to add missing functionality of stop margin due to out of drivable area in `obstacle_avoidance_planner` since refactoring done in https://github.com/autowarefoundation/autoware.universe/pull/2796
Related : https://github.com/autowarefoundation/autoware.universe/pull/4194
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main …

fix(obstacle_avoidance_planner): adding missing functionality for stop margin due to out of drivable area

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml

Related PR: https://github.com/autowarefoundation/autoware.universe/pull/4194
TODO after this PR is merged: Fix the issue of the outside drivable area wall appears much as expected.
This PR set the stop margin for outside the drivable area to zero.
Due to the issue of the outside drivable area wall tends to appear close to the other stop wall like crosswalk, intersection, etc, the several scenarios TIER IV is maintaining failed.
scenario simulator
Almost nothing …

chore(autoware_launch): zero margin for outside the drivable area

---

autoware_launch/config/perception/object_recognition/detection/object_merger/data_association_matrix.param.yaml
autoware_launch/config/perception/object_recognition/detection/object_merger/overlapped_judge.param.yaml
autoware_launch/launch/components/tier4_perception_component.launch.xml

This PR adds map_based_prediction.param.yaml to autoware_launch config directory
- https://github.com/autowarefoundation/autoware.universe/pull/4339
Releated: 
- https://github.com/autowarefoundation/autoware.universe/issues/4250

refactor(autoware_launch): add object_merger param files

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

This pull request refactors the avoidance module of the behavior path planner to use a new parameter `lateral_avoid_check_threshold` for checking the lateral shift of the ego vehicle during avoidance maneuvers.
Nothing.

refactor(avoidance): parameterize magic number

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/path_sampler/path_sampler.param.yaml

This PR changes the `lateral_deviation_weight` so that the output trajectory is more likely to stay close to the reference path.
Evaluation platform: https://evaluation.tier4.jp/evaluation/reports/d45cfc83-e85d-5ff0-8251-a2603f30f5c6?project_id=prd_jt (TIER IV internal link)
Better trajectory when using the `path_sampler`. …

perf(path_sampler): tune lateral_deviation_weight for more stable planning

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml

launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4381
See https://github.com/autowarefoundation/autoware.universe/pull/4381
See https://github.com/autowarefoundation/autoware.universe/pull/4381

feat(autoware_launch): add dynamic avoidance parameters

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml

launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4412
See https://github.com/autowarefoundation/autoware.universe/pull/4412
See https://github.com/autowarefoundation/autoware.universe/pull/4412

feat(autoware_launch): add cut_in_object.min_lon_offset_ego_to_object in dynamic avoidance

---

autoware_launch/launch/components/tier4_localization_component.launch.xml

This PR adds input/pointcloud parameter to tier4_localization_component.launch.xml from https://github.com/autowarefoundation/autoware.universe/blob/main/launch/tier4_localization_launch/launch/localization.launch.xml and https://github.com/autowarefoundation/autoware.universe/blob/main/launch/tier4_localization_launch/launch/pose_twist_estimator/pose_twist_estimator.launch.xml. Also parameter renamed to input_pointcloud for the sake of keeping namespace simplicity in autoware_launch. 
Related: https://github.com/autowarefoundation/autoware.universe/pull/4411
İt worked without error on logging simulator.
The PR author **must** check …

refactor(tier4_localization_component): input_pointcloud param added

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
autoware_launch/rviz/autoware.rviz

This feature replaces the occlusion grid with occlusion polygon and filtering based on its size.
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/4442
Psim

feat(intersection): extract occlusion contour as polygon

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

Add new parameter `remain_buffer_distance` in order to keep constant remaining distance between avoidance end point and path end point.
https://github.com/autowarefoundation/autoware.universe/pull/4467

feat(avoidance): add parameter to configurate avoidance return point

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/scene_module_manager.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/out_of_lane.param.yaml

Add parameter for https://github.com/autowarefoundation/autoware.universe/pull/4217
Tested in Psim. 
The predicted path with `0.08` confidence is detected to collide with ego when it overlaps the right-side lane.
The predicted path with `0.08` confidence is ignored and no collisions are detected.
Less false positives when using the `out_of_lane` module.  …

feat(out_of_lane): add param for the min confidence of a predicted path

---

autoware_launch/config/perception/traffic_light_arbiter/traffic_light_arbiter.param.yaml
autoware_launch/launch/components/tier4_perception_component.launch.xml

This PR adds `traffic_light_arbiter.param.yaml` to autoware launch.
autoware universe PR:
- https://github.com/autowarefoundation/autoware.universe/pull/4454
please see https://github.com/autowarefoundation/autoware.universe/pull/4454

refactor(traffic_light_arbiter): add traffic_light_arbiter param file

---

autoware_launch/rviz/autoware.rviz

Add acceleration meter for debugging, which should be aligned with the speed meter, and disabled by default. The Acceleration meter is implemented and discussed in https://github.com/autowarefoundation/autoware.universe/pull/4506
PSim.
Please check the images in https://github.com/autowarefoundation/autoware.universe/pull/4506 .
The meter does not pop up by default and requires manual selection in system/vehicle to enable the plugin.
A new panel recording acceleration is expected to opened on the right of speed panel. (In the screenshot we manually select the checkbox to enable the acceleration meter)
The center text should turn red (by default) if acceleration is larger than a max-threshold (re-configurable on Rviz), or smaller than a min-threshold. (In the screenshot we manually …

feat(rviz): add acceleration meter for debugging which is disabled by default

---

autoware_launch/launch/components/tier4_perception_component.launch.xml

This PR adds an option which determines object filtering and object validation method to tier4_perception_component.
releated: 
- https://github.com/autowarefoundation/autoware.universe/issues/4250
autoware.universe PR:
- https://github.com/autowarefoundation/autoware.universe/pull/4402
The tests are performed in logging simulator: object_lanelet_filter, object_position_filter, obstacle_pointcloud and occupancy_grid (we need change occupancy_grid_map_method to laserscan_based_occupancy_grid_map also) mode works as expected.
After all checkboxes are checked, anyone who …

refactor(autoware_launch): add an option for filtering and validation

---

autoware_launch/config/planning/mission_planning/mission_planner/mission_planner.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/behavior_velocity_planner.param.yaml

This PR is to add as solution for routing `no_drivable_lane(s)` only when the module is enabled.
Related to this [Task](https://github.com/autowarefoundation/autoware.universe/issues/4307)
Using planning simulator :
- When `no_drivable_lane` is disabled, the routing for `no_drivable_lane(s)` is not considered
- When When `no_drivable_lane` is enabled, routing for `no_drivable_lane(s)` is considered
Routing for `no_drivable_lane(s)` is considered only when the module is enabled. …

feat(routing_no_drivable_lane_when_module_enabled): add solution for routing no_drivable_lane only when module enabled

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml

launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4566
- use hatched road markings in dynamic avoidance
- add minor ros parameters in dynamic avoidance
See https://github.com/autowarefoundation/autoware.universe/pull/4566
See https://github.com/autowarefoundation/autoware.universe/pull/4566 …

feat(autoware_launch): use hatched road markings in dynamic avoidance

---

autoware_launch/config/system/system_error_monitor/system_error_monitor.planning_simulation.param.yaml

check lateral deviation in sim.
I would like to use this diag topic in evaluator with diagnostic_converter.
Psim
output error diag if the ego is far from trajectory.

feat(system_error_monitor): check lateral deviation in sim

---

autoware_launch/launch/components/tier4_simulator_component.launch.xml

This PR adds `traffic_light_arbiter_param_path` to configure parameter of `traffic_light_arbiter` in scenario simulation.
Related PR
- https://github.com/autowarefoundation/autoware.universe/pull/4522
I confirmed the parameters is set in simple planning simulator.
Changed parameter file in autoware launch.
```
/**:
ros__parameters:
external_time_tolerance: 5.0
perception_time_tolerance: 1.1
external_priority: true
```
The result of ros2 param dump.
```
$ ros2 param dump /perception/traffic_light_recognition/traffic_light_arbiter/arbiter
/perception/traffic_light_recognition/traffic_light_arbiter/arbiter:
ros__parameters:
external_priority: true
external_time_tolerance: 5.0
perception_time_tolerance: 1.1
qos_overrides:
/parameter_events:
publisher:
depth: 1000
durability: volatile
history: …
```

chore(tier4_simulator_component): add traffic light arbiter param path

---

autoware_launch/config/control/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml
autoware_launch/launch/components/tier4_control_component.launch.xml

This PR adds an option for using raw external commands for vehicle such as R/C controlled car.
autoware.universe PR: 
- https://github.com/autowarefoundation/autoware.universe/pull/4325
releated: 
- https://github.com/autowarefoundation/autoware.universe/issues/4324
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pu …

feat(autoware_launch): add use_raw_remote_control_command_input argument

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

https://github.com/autowarefoundation/autoware.universe/pull/4731
Improve avoidance performance.

fix(avoidance): avoidance shift line processing bug

---

autoware_launch/launch/components/tier4_perception_component.launch.xml

Related to this PR https://github.com/autowarefoundation/autoware.universe/pull/4805, this PR adds the default value for the TLR models

chore: add default args for TLR models

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml

calculate the stuck vehicle detect area using
- the path from the first point inside `conflicting area` to the last point inside the intersection lane
- the path on the next lane up to `stuck_vehicle_detect_dist`
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/4782
evaluator …

feat(intersection): strict definition of stuck vehicle detection area

---

autoware_launch/config/system/system_error_monitor/system_error_monitor.param.yaml

I made a change to set the diagnostic level to "latent fault" and change the state of Autoware to "Emergency" when the state of resource_monitoring becomes an error.
none
none
As the description,

feat(autoware_launch): enable emergency handling when resource monitoring state becomes error

---

autoware_launch/config/control/control_validator/control_validator.param.yaml

suppress warning message and publish diag for now.
Apparently it has problem with code.
I will revert this PR's change after solve the problem.
Checked no warning is shown in terminal.

fix(control_validator): default false for publishing diag and display terminal

---

autoware_launch/rviz/autoware.rviz

Add localization rviz config
Launch RViz and confirm that it launches fine
Not applicable

chore(rviz_config): add localization debug config

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/drivable_area_expansion.param.yaml

Add parameter required by PR https://github.com/autowarefoundation/autoware.universe/pull/4677.
Psim and evaluator.
More stable drivable area bounds when using the dynamic expansion.

feat(behavior_path_planner): add path resampling interval param

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/out_of_lane.param.yaml

Add parameter required for the universe PR https://github.com/autowarefoundation/autoware.universe/pull/4784
Psim and evaluator.
Less incorrect stops when using the `out_of_lane` module, and when ego is stopped or driving slowly, stops are triggered more consistently.

feat(out_of_lane): add min_assumed_velocity parameter

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

Should be merged with this [PR](https://github.com/autowarefoundation/autoware.universe/pull/4873)

feat(behavior_path_planner): add safety check against dynamic objects for start/goal planner

---

autoware_launch/config/control/operation_mode_transition_manager/operation_mode_transition_manager.param.yaml

For https://github.com/autowarefoundation/autoware.universe/pull/4891
see https://github.com/autowarefoundation/autoware.universe/pull/4891
see https://github.com/autowarefoundation/autoware.universe/pull/4891

feat(operation_transition_mannager): add param enable_engage_on_driving

---

autoware_launch/launch/e2e_simulator.launch.xml

Confirmed that traffic light recognition is working by `ros2 launch autoware_launch e2e_simulator.launch.xml ` with AWSIM_v1.1.0 
by this tutorial https://tier4.github.io/AWSIM/GettingStarted/QuickStartDemo/)

feat: add traffic light recogition namespace to e2e sim launch

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/surround_obstacle_checker.param.yaml

launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/4925
See https://github.com/autowarefoundation/autoware.universe/pull/4925
See https://github.com/autowarefoundation/autoware.universe/pull/4925

feat(autoware_launch): additional margin parameters in surround obstacle checker

---

autoware_launch/rviz/autoware.rviz

https://github.com/autowarefoundation/autoware.universe/issues/4848
rviz reports the following error:
```
[rviz2-74] [ERROR 1693558088.618417957] [rviz2]: PluginlibFactory: The plugin for class 'tier4_localization_rviz_plugin/InitialPose
```
This plugin was removed https://github.com/autowarefoundation/autoware.universe/pull/4519.
So I will also remove tier4_localization_rviz_plugin/InitialPoseButtonPanel from the autoware.rviz.
LSim works well without an above error message.
[contribution …

fix(autoware.rviz): remove initial_pose_button_panel

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

Default disable feature of safety check against dynamic objects, because this feature is unstable at the moment.

fix(behavior_path_planner): change safety check default disable

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

Set param of `ignore_object_velocity_threshold` from 0.0 to 1.0.
This temporal value is to avoida chattering and should be tuned properly depends on the use case.
Before:
https://github.com/autowarefoundation/autoware_launch/assets/32741405/712f129f-6864-4b47-9862-055b82fb0226
After:
https://github.com/autowarefoundation/autoware_launch/assets/32741405/4f046031-6d3b-40f8-ad34-e178ac478dd0
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/m …

feat(behavior_path_planner): set param ignore_object_velocity_threshold

---

autoware_launch/config/perception/object_recognition/detection/object_filter/radar_lanelet_filter.param.yaml
autoware_launch/launch/components/tier4_perception_component.launch.xml

This PR add lanelet filter parameter for radar faraway detection.
related PR
* https://github.com/autowarefoundation/autoware.universe/pull/4995
Test by rosbag.
In radar faraway detection, lanelet filter can be applied by the config yaml adding by this PR.

fix(autoware_launch): add radar lanelet filter parameter

---

autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/components/tier4_perception_component.launch.xml
autoware_launch/launch/e2e_simulator.launch.xml
autoware_launch/launch/logging_simulator.launch.xml
autoware_launch/launch/planning_simulator.launch.xml

Belongs to [Standardize a strategy for packages with downloaded artifacts](https://github.com/orgs/autowarefoundation/discussions/3649)
As [artifact downloading in ansible](https://github.com/autowarefoundation/autoware/pull/3375) was merged to Autoware.universe. It is possible to use artifacts downloaded there. 
This PR introduces new launch argument data_path in the form: 
```  <arg name="data_path" default="$(env HOME)/autoware_data" description="packages data and artifacts directory path"/>```
It should be downstreamed to all packages with downloaded artifacts, mostly perception. 
Logging_simulator and planning_simulator launch fine with this parameter.
The PR reviewers **must** check the …

feat(perception): add data_path argument to launch file

---

autoware_launch/config/localization/ndt_scan_matcher.param.yaml

Fixed ndt_scan_matcher.param.yaml to match to [the one in universe](https://github.com/autowarefoundation/autoware.universe/blob/main/localization/ndt_scan_matcher/config/ndt_scan_matcher.param.yaml), where autoware_launch misses `ndt_base_frame` and has an unneeded `neighborhood_search_method`.
Successfully built, autoware_launch, and [rosbag replay simulation in the tutorial](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/) has been tested in my environment too.
This shouldn't affect the system behavior.
After …

refactor(ndt_scan_matcher): match ndt_scan_matcher.param.yaml

---

autoware_launch/config/planning/scenario_planning/common/motion_velocity_smoother/motion_velocity_smoother.param.yaml

For https://github.com/autowarefoundation/autoware.universe/pull/4924
run psim
see https://github.com/autowarefoundation/autoware.universe/pull/4924

fix(motion_velocity_smoother): change curvature calculation distance parameter

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml
autoware_launch/launch/components/tier4_planning_component.launch.xml

We add two parameters corresponding to the new feature https://github.com/autowarefoundation/autoware.universe/pull/5036
This PR should be merged BEFORE the corresponding PR in the autoware.univverse is merged.
Tests are performed in Psim, and the all of new parameters work well.
`obstacle_cruise_planner` will not be launched with the default settings, so there is no effects when this PR is merged. …

feat(obstacle_cruise_planner): add parameters for a new feature

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml

launcher update for https://github.com/autowarefoundation/autoware.universe/pull/5110
psim
none
none

feat(goal_planner): sort goal candidates priority by weighted distance

---

autoware_launch/config/localization/ndt_scan_matcher.param.yaml

This PR provides integration of autoware.universe and autoware_launch for localization. Adds critical_upper_bound_exe_time_ms to ndt_scan_matcher.param.yaml.
Related: https://github.com/autowarefoundation/autoware.universe/pull/4916
All added options runned through logging simulator and test vehicle. 
It gives a facility for observing changes in nearest_voxel_transformation_likelihood and exe_time.
The Reviewers **must** check the checkboxes below before approval.
[pull …

feat(ndt_scan_matcher): adding exe time parameter

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/scene_module_manager.param.yaml

The dynamic avoidance module should be launched at last since the algorithm will not fix the path requesting the approval as other modules do.
Nothing (dynamic avoidance is not used by default)
Nothing

feat(autoware_launch): move dynamic_avoidance last

---

autoware_launch/config/system/system_error_monitor/system_error_monitor.awsim.param.yaml
autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/components/tier4_system_component.launch.xml
autoware_launch/launch/e2e_simulator.launch.xml

We added a system_monitor configuration file specifically for AWSIM, as there are differences between the real-world environment and the AWSIM environment
Not yet
To enable Autoware to drive in the AWSIM environment without being in an emergency state.

feat: add system monitor param file for awsim

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

enable divide_pull_out_path 
2023/09/27 https://evaluation.tier4.jp/evaluation/reports/575a15e6-2dea-5564-912f-8b78ca5573c0/?project_id=prd_jt
stop at once the middle of two arc paths.

feat(start_planner): enable divide_pull_out_path

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml

Add a flag to use the planned velocity profile from the upstream modules, especially for stop line.
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/5156
Psim
none.
none.

feat(intersection): use planned velocity from upstream modules

---

autoware_launch/config/localization/ndt_scan_matcher.param.yaml

Fixed ndt_scan_matcher.param.yaml to match with [the one in universe](https://github.com/autowarefoundation/autoware.universe/blob/main/localization/ndt_scan_matcher/config/ndt_scan_matcher.param.yaml).
Related: https://github.com/autowarefoundation/autoware.universe/pull/5155 
autoware_launch successfully built, and [rosbag replay simulation in the tutorial](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/) has been tested in my environment.
This shouldn't affect the system behavior.
After all checkboxes are …

refactor(ndt_scan_matcher): modified ndt_scan_matcher.param.yaml to match with the one in universe

---

autoware_launch/config/control/predicted_path_checker/predicted_path_checker.param.yaml
autoware_launch/launch/components/tier4_control_component.launch.xml

Related links:
https://github.com/autowarefoundation/autoware.universe/pull/2528
https://github.com/autowarefoundation/autoware.universe/pull/3911

feat(autoware_launch): add predicted_path_checker package

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

Add lane expansion parameters and logic for object filtering in lane change module. This improves safety check by allowing user to determine if they want to consider slightly out of lane object as target.
Note: 
Purple cube: other lane object
Aqua cube: target lane object
Yellow cube: current lane object
https://github.com/autowarefoundation/autoware.universe/pull/5167 …

feat(lane_change):  expand target lanes for object filtering

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

update RSS param
[Screencast.webm](https://github.com/autowarefoundation/autoware_launch/assets/32741405/abd77501-c9c8-4e81-8a7e-6a42eaa8dae8)

feat(behavior_path_planner): update rss param

---

autoware_launch/config/localization/localization_error_monitor.param.yaml

Update parameter.
Current Autoware's EKF may ignore low velocity depending on the zero band of its sensor, making the localization error covariance larger. With this update, we can suppress such warnings with the default value, improving the usability for OSS users. Note that it is always recommended to tune the parameters for each vehicle.
https://github.com/autowarefoundation/autoware_launch/pull/614
Tested on pilot-auto.x2
Threshold of localization_accuracy gets larger. …

feat(localization_error_monitor): update parameter

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/out_of_lane.param.yaml

Add parameter for https://github.com/autowarefoundation/autoware.universe/pull/5207
Psim
More precise stop point with the `out_of_lane` module.

fix(autoware_launch): improve stop decision in out_of_lane

---

autoware_launch/config/localization/ndt_scan_matcher.param.yaml

See https://github.com/autowarefoundation/autoware.universe/pull/5220
See https://github.com/autowarefoundation/autoware.universe/pull/5220
See https://github.com/autowarefoundation/autoware.universe/pull/5220

perf(ndt_scan_matcher): changed default `initial_estimate_particles_num` to 200

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml

For occlusion detection, the lanelets whose maximum curvature is higher than the threshold are not used.
TODO: trim part of lanelet with low curvature
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/5223
see feature PR
none.
none.

feat(intersection): ignore occlusion beyond high curvature point

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml

add new params for the following PR
https://github.com/autowarefoundation/autoware.universe/pull/5229
Test was performed for the related PR

feat(intersection)!: disable the exception behavior in the private areas

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml
autoware_launch/launch/components/tier4_planning_component.launch.xml

Companion launch necessary for this PR: https://github.com/autowarefoundation/autoware.universe/pull/5208 

feat(obstacle_cruise_planner): obstacle type dependent slow down for obstacle cruise planner param change

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

Separating safety check parameters for lane change execution and cancel.
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/5246

feat(lane_change): separate execution and cancel safety check param

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml

feature PR: https://github.com/autowarefoundation/autoware.universe/pull/5234
See https://github.com/autowarefoundation/autoware.universe/pull/5234
none.
none.

feat(intersection): yield initially on green light

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

https://github.com/autowarefoundation/autoware.universe/pull/5032
Evaluator
Nothing.

feat(avoidance): check if the avoidance path is in drivable area

---

autoware_launch/config/perception/object_recognition/tracking/radar_object_tracker/radar_object_tracker.param.yaml
autoware_launch/config/perception/object_recognition/tracking/radar_object_tracker/tracking/linear_motion_tracker.yaml
autoware_launch/config/perception/object_recognition/tracking/tracking_object_merger/data_association_matrix.param.yaml
autoware_launch/config/perception/object_recognition/tracking/tracking_object_merger/decorative_tracker_merger.param.yaml
autoware_launch/config/perception/object_recognition/tracking/tracking_object_merger/decorative_tracker_merger_policy.param.yaml
autoware_launch/launch/components/tier4_perception_component.launch.xml

Add parameters to handle `tracking_object_merger` and `radar object tracking` module.
This is related with
- tier4_perception_launch [PR](https://github.com/autowarefoundation/autoware.universe/pull/5269)
- tracking object merger [PR](https://github.com/autowarefoundation/autoware.universe/pull/4340)
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing …

feat: add tracking object merger for long range radar sensor

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

stational predicted objects sometimes have 0.3 velocity. so change the threshold for that to 0.5

feat(lane_change): change stuck velocity to 0.5

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/drivable_area_expansion.param.yaml

Disable the dynamic drivable area expansion in the default configuration of the `behavior_path_planner`.
Drivable area will not be dynamically expanded. This is usually fine for car-sized vehicles but it should be turned back on for larger vehicles.

fix(drivable_area_expansion): disable by default

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml

Now the collision checking in the intersection module is stable, this parameter can be set to zero.
evaluator: https://evaluation.tier4.jp/evaluation/reports/a6989803-5c35-5eb8-aab4-1e41a803cc2a?project_id=prd_jt
none.
none.

fix(intersection): lower state_transit_margi_time to 0

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

This pull request refactors and improves the avoidance target filtering logic for the `behavior_path_planner` node. It introduces new parameters to configure the detection area for avoidance and lane change, and uses a dynamic detection range based on the vehicle speed and jerk limit. It also simplifies and optimizes the object separation code in `utils.cpp` and `avoidance_module.cpp`.
- https://github.com/autowarefoundation/autoware.universe/pull/5303
Evaluator
Nothing. …

feat(avoidance): add paramenters for dynamic detection area

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml

This pull request adds a new parameter max_itration_num to the behavior path planner node and its components. The parameter controls the maximum number of iterations for the planner manager to run the behavior modules and select the best output. This improves the performance and stability of the path planning process.
- https://github.com/autowarefoundation/autoware.universe/pull/5352
Evaluator
Nothing. …

feat(planner_manager): limit iteration number by parameter

---

autoware_launch/config/perception/object_recognition/prediction/map_based_prediction.param.yaml

Add parameter to control lateral prediction path shape.
Related with this https://github.com/autowarefoundation/autoware.universe/pull/5285.

feat(map_based_prediction): enable to control lateral path convergence time

---

autoware_launch/config/system/system_error_monitor/system_error_monitor.param.yaml
autoware_launch/config/system/system_error_monitor/system_error_monitor.planning_simulation.param.yaml

disable `duplicated_node_checker` for now.
The reason for this is that simulation fails by enabling this feature.
It should be fixed by preventing double launch, but for now, disable it.

feat(duplicated_node_checker): disable duplicated_node_checker

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/path_smoother/elastic_band_smoother.param.yaml

Increase the replan lateral distance threshold to prevent costly replanning when the path deviates only a little.
Psim
The path is not smoothed again if the path changes laterally by less than 0.2m (previously 0.1m).
The path is still smoothed every 1s, regardless of how much it changed.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request …

perf(elastic_band_smoother): increase lateral replan threshold

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/5405
See https://github.com/autowarefoundation/autoware.universe/pull/5405
See https://github.com/autowarefoundation/autoware.universe/pull/5405

feat: add use_conservative_buffer_longitudinal in avoidance

---

autoware_launch/rviz/autoware.rviz

Hide intersection area.
related PRs:
- https://github.com/autowarefoundation/autoware.universe/pull/5401
- https://github.com/autowarefoundation/autoware_common/pull/211
Psim
Nothing.

chore(rviz): hide interseciton area polygon as default

---

autoware_launch/rviz/autoware.rviz

I am testing on latest Autoware Universe main branch and the latest AWSIM.
I couldn't see the traffic light visualization on RViz2.
When I changed `/perception/traffic_light_recognition/debug/rois` to `/perception/traffic_light_recognition/traffic_light/debug/rois` it was working again.
- https://github.com/autowarefoundation/autoware_launch/pull/555
- probably from this PR.
Tested with AWSIM and now it works. …

fix(rviz2): update traffic_light/debug/rois topic name

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

Separate backward buffer parameter for blocking object
See https://github.com/autowarefoundation/autoware.universe/pull/5434
`backward_length_buffer_for_blocking_object` is added.
Able to change backward length buffer for blocking object.

fix(lane_change): separate backward buffer for blocking object

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

See https://github.com/autowarefoundation/autoware.universe/pull/5441.
Evaluator.

refactor(avoidance): cleanup force avoidance params

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

See https://github.com/autowarefoundation/autoware.universe/pull/5395.
Evaluator.

feat(avoidance): return original lane by red traffic light

---

autoware_launch/launch/components/tier4_planning_component.launch.xml

See https://github.com/autowarefoundation/autoware.universe/pull/5470.
Evaluator.
Nothing.

refactor(planning): update args name

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml

feature PR: https://github.com/autowarefoundation/autoware.universe/pull/5496
see https://github.com/autowarefoundation/autoware.universe/pull/5496
none.
none.

feat(intersection): rectify initial accel/velocity profile in ego velocity profile

---

autoware_launch/config/planning/preset/default_preset.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/scene_module_manager.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/behavior_velocity_planner.param.yaml
autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/components/tier4_planning_component.launch.xml
autoware_launch/launch/e2e_simulator.launch.xml
autoware_launch/launch/logging_simulator.launch.xml
autoware_launch/launch/planning_simulator.launch.xml

Add new option `planning_module_preset` so that it is able to switch launch modules more easily and flexibly.
```
ros2 launch autoware_launch planning_simulator.launch.xml map_path:=foo vehicle_model:=bar sensor_model:=baz planning_module_preset:=default
```
```xml
<arg name="planning_module_preset" default="default" description="planning module preset"/>
```
We can select launch modules in preset yaml file as follow. In addition, since we can manage launch modules by only one file, we don't have to create new branch in order to change launch modules.
```yaml
...
- arg:
name: use_experimental_lane_change_function
default: "true"
- arg:
name: launch_surround_obstacle_checker
default: "true"
- arg:
name: motion_path_smoother_type
default: elastic_band
- arg:
name: motion_path_planner_type …
```

refactor(launch): add new option to select planning preset

---

autoware_launch/config/planning/preset/default_preset.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/run_out.param.yaml

enable the run_out module in the behavior_velocity_planner
https://autowarefoundation.github.io/autoware.universe/main/planning/behavior_velocity_run_out_module/
scenario test: https://evaluation.tier4.jp/evaluation/reports/0589e6cc-9228-5801-b297-64839e81d418?project_id=prd_jt
When the pedestrian is moving to the ego path and TTS is close, the ego will plan stopping. …

feat: enable the run_out module

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml

Related Draft PR: https://github.com/autowarefoundation/autoware.universe/pull/5510
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-3610)
See related PR on description.
See related PR on description.
Vehicle slow down response can be customized for moving or static objects.  
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-requ …

feat(obstacle_cruise_planner): use obstacle velocity based obstacle parameters

---

autoware_launch/config/perception/object_recognition/detection/clustering/radar_object_clustering.param.yaml
autoware_launch/launch/components/tier4_perception_component.launch.xml

Move `radar_object_clustering` parameter to autoware_launch so that each pilot.auto project can change these parameters.
Show universe pr here later.
Tested with lsim and checked with ros2 param.

feat(radar_object_clustering): move radar object clustering params to autoware_launch

---

autoware_launch/config/control/lane_departure_checker/lane_departure_checker.param.yaml

The current lane_departure_checker unnecessarily publishes the diag even when it is not dangerous.
A better logic for the real use-case was implemented here checking if the ego's predicted trajectory will collide with the curbstones.
https://github.com/autowarefoundation/autoware.universe/pull/4607
This PR enables this logic and disables the previous logic.
psim
What lane_departure_checker detects will be whether the ego's predicted trajectory will collide with the curbstones. …

feat: lane_departure_checker with curbstones

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

https://github.com/autowarefoundation/autoware.universe/pull/5457
Regulate lane change at the traffic light.
In this PR, by setting `regulate_on_traffic_light` to `true`, lane change module accepts path only when
1) lane changing start pose is after traffic light's stop line.
2) lane changing end pose is before traffic light's stop line.
https://github.com/autowarefoundation/autoware.universe/assets/93502286/6e122c5d-4cc6-4643-8058-7a2167451dde …

fix(lane_change): regulate at the traffic light

---

autoware_launch/config/system/component_state_monitor/topics.yaml

See https://github.com/autowarefoundation/autoware.universe/pull/5617
See https://github.com/autowarefoundation/autoware.universe/pull/5617
See https://github.com/autowarefoundation/autoware.universe/pull/5617

feat(component_state_monitor): monitor pose_estimator output

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

disbale verbose flag to false in start_planner.param.yaml
It causes node die, I will investigate further later.
But disable the future for now to fix this phenomena for now. 

fix(start_planner): disbale verbose flag to false in start_planner.param.yaml

---

autoware_launch/config/system/component_state_monitor/topics.yaml

merge to autoware-msg branch: 
replace autoware_auto_mapping_msg/msg/HADMapBin with autoware_map_msgs/msg/ LaneletMapBin

feat(autoware_launch): replace autoware_auto_mapping_msg with autoware_map_msg

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

enable safety check feature for start_planner with this PR
[Screencast from 2023年11月24日 16時30分50秒.webm](https://github.com/autowarefoundation/autoware_launch/assets/32741405/6927da56-4a70-44d7-9125-f88d1be2a391)
[Screencast from 2023年11月24日 16時19分04秒.webm](https://github.com/autowarefoundation/autoware_launch/assets/32741405/1d4e7f40-7a2b-4f74-afd4-7ac05efb7be1)
[Screencast from 2023年11月24日 16時17分20秒.webm](https://github.com/autowarefoundation/autoware_launch/assets/32741405/68c8b2a0-6638-40f5-994a-f9fc9ca0508b)
After all checkboxes are checked, anyone who has write …

feat(start_planner): enable safety check for start planner

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/run_out.param.yaml

Added parameter for this PR.
- https://github.com/autowarefoundation/autoware.universe/pull/5672
PSim

feat(run_out): add parameter to decide whether to use the object's velocity

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml

launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/5679
See https://github.com/autowarefoundation/autoware.universe/pull/5679
See https://github.com/autowarefoundation/autoware.universe/pull/5679

feat: add parameters for the front object decision in dynamic_avoidance module

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance_by_lc/avoidance_by_lc.param.yaml

See https://github.com/autowarefoundation/autoware.universe/pull/5699

feat(avoidance): configurable object type for safety check

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml

In the obstacle_avoidance_planner, generating debug markers for optimization can occupy a major part of the processing time, so we will turn off generation by default.
Additional information about the figure:
- Ocher: Total processing time (milliseconds)
- Pink: Debug marker generation time (milliseconds) …

feat: disable obstacle avoidance debug marker for optimization

---

autoware_launch/config/system/component_state_monitor/topics.yaml

I propose adding a topic monitor for the output of the traffic light recognition system. 
Please see the https://github.com/autowarefoundation/autoware.universe/pull/5778 for more details.
See https://github.com/autowarefoundation/autoware.universe/pull/5778
If traffic signal messages are not received or its topic rate is decreased, the vehicle will enter the emergency state. …

feat(component_state_monitor): monitor traffic light recognition output

---

autoware_launch/rviz/autoware.rviz

Fix perception debug topics in rviz

feat(rviz): fix perception debug topics in Rviz

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/traffic_light.param.yaml

See https://github.com/autowarefoundation/autoware.universe/pull/5819
See https://github.com/autowarefoundation/autoware.universe/pull/5819
`stop_time_hysteresis` is added.
See https://github.com/autowarefoundation/autoware.universe/pull/5819

fix(traffic_light): stop if the traffic light signal timed out

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/blind_spot.param.yaml

https://github.com/autowarefoundation/autoware.universe/pull/5635
https://github.com/autowarefoundation/autoware.universe/pull/5635
see feature PR
see feature PR
see feature PR
see feature PR

feat(blind_spot): consider opposite adjacent lane for wrong vehicles

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/run_out.param.yaml

Currently, when the ego is decelerating due to modules such as obstacle stop, the run out module inserts a stop point in the path.
In this case, the `min_behavior_stop_margin` feature of the obstacle stop makes its stop point closer to the run out's stop point, resulting in getting closer to the object.
To fix this issue, when there is enough time for stopping at the run out's stop point because of other modules' stop point, the run out will not insert a stop point.
psim
scenario test
Nothing
[contribution …

feat: run_out does not plan to stop when there is enough time for stopping

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

collision_check_distance_from_end: 1.0
collision_check_distance_from_end: -10.0
https://github.com/autowarefoundation/autoware.universe/assets/39142679/322e0130-7501-4518-ae16-ff589569bba6
https://evaluation.tier4.jp/evaluation/reports/d93d82ca-bd33-57ef-9d62-247c06796602?project_id=prd_jt
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contrib …

feat(start_planner): change collision_check_distance_from_end to shorten back distance  ## Description

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

https://github.com/autowarefoundation/autoware_launch/pull/754
This reverts commit 680fb05e9bebdff6cf2c9734631cb4e949d7c499.
https://github.com/autowarefoundation/autoware_launch/pull/754 degragete some tier4 internal scenarios
this PR is not wrong but revert tempolary until fixing scenario …

feat(start_planner): revert change collision_check_distance_from_end to shorten back distance

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop_planner.param.yaml

goal planner's `longitudinal_margin: 3.0` is exactly same to `terminal_safe_distance_margin` and `max_longitudinal_margin_behind_goal`.
This may prevent arrving the goal, so the value is slightly reduced.
with obstacle stop planner
before
after
https://github.com/autowarefoundation/autoware_launch/assets/39142679/ed31ebcc-a103-40f6-b099-263d310066ce
[pull request …

feat(obstacle_stop_planner): change stop distance after goal

---

autoware_launch/config/perception/object_recognition/prediction/map_based_prediction.param.yaml

Necessary changes for this PR: https://github.com/autowarefoundation/autoware.universe/pull/5960

feat(map_based_prediction): map prediction with acc constraints

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml

Towards the real world's driving, this PR enables the following feature since **the current crosswalk decision is too conservative**.
- When there is a **stopped** pedestrian close to the crosswalk where the pedestrian's traffic signal is green,
- Without this PR, the decision is STOP in front of the crosswalk for 3 seconds, which annoys the car behind so much.
- With this PR, only for the first 3 seconds regardless of the ego stopping or not, the decision is STOP. After that the decision will be GO.
- When the **new stopped** pedestrian appears close to the crosswalk where the ego will cross soon.
- Without this PR, the initial decision is STOP, so even when it requires a sudden stop, the ego tries to stop.
- With this PR, the initial decision is GO when the pedestrian is stopped, so the …

feat: make crosswalk decision more aggressive towards the real world's driving

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

Change lane change parameters to real vehicle environment
[TIER IV INTERNAL TEST](https://evaluation.tier4.jp/evaluation/reports/1610f81c-bbf4-5413-baab-34ae0a7b00f9?project_id=prd_jt)

fix(lane_change): set lane change parameters to real vehicle environment

---

autoware_launch/rviz/autoware.rviz

See https://github.com/autowarefoundation/autoware_common/pull/225.
Psim
Nothing.

fix(rviz): hide traffic light regulatory element id

---

autoware_launch/launch/components/tier4_planning_component.launch.xml

During the [Planning & Control working group](https://github.com/orgs/autowarefoundation/discussions/3831) it was decided to disable the surround_obstacle_checker by default.
Original discussion: https://github.com/orgs/autowarefoundation/discussions/3799
Psim
The Autoware vehicle will no longer stop if an obstacle is close to its footprint. …

feat(surround_obstacle_checker): disable the surround obstacle checker

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/path_smoother/elastic_band_smoother.param.yaml

Tune parameters for the optimization path planning (obstacle_avoidance_planner and path_smoother packages)
- Solve the optimization every timestep
- Without this PR, the optimization is solved every 1 second due to the calculation cost. Now the calculation cost decreased enough.
- Tune the collision-free weight so that the trajectory's footprint will be inside the drivable area
- The current weight is too large to do the optimization-based avoidance.
- The ego will not stop when the trajectory's footprint is outside the drivable area.
- psim
- scenario test:
- https://evaluation.tier4.jp/evaluation/reports/84c10a27-0536-5f60-b561-596aa1ecc626?project_id=prd_jt
- https://evaluation.tier4.jp/evaluation/reports/2785c233-a59e-5566-b942-8f582b09c91e?project_id=prd_jt
- real JapanTaxi vehicle …

feat: tune parameters for optimization path planning

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

This is change for the [PR](https://github.com/autowarefoundation/autoware.universe/pull/5983)
adding param of `collision_check_margin_from_front_object` for start_planner module

feat(start_planner): keep distance against front objects

---

autoware_launch/config/localization/ekf_localizer.param.yaml

Refers to https://github.com/autowarefoundation/autoware.universe/pull/6004

feat(ekf_localizer): add publish_tf arg

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

Shoten max backward distance when starting for safety.
Tested with read vehicle.
https://github.com/tier4/autoware_launch.xx1/pull/713
The ego will be less likely to start too backward.
The ego will be more likely to stuck when there is a vehicle in front of the ego.

feat(start_planner): shorten max backward distance 

---

autoware_launch/config/localization/ekf_localizer.param.yaml

Simple1DFilter parameters will be added to the parameter file to be able to change these parameters from the parameter file.
This PR related this PR: https://github.com/autowarefoundation/autoware.universe/pull/5707

refactor(ekf_localizer): add Simple1DFilter params to parameter file

---

autoware_launch/rviz/autoware.rviz

Add debug marker config to show bpp internal state.
Psim
Nothing.

feat(rviz): add marker to show bpp internal state

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

Enable shift path lane departure check.
This featured disabled in the [PR](https://github.com/autowarefoundation/autoware.universe/pull/4151)
But this causes ploblem that start planner module generate path which leave lane. So enable this feature in this PR.
After enabling this feature this, path leaves from lane is not generated.
[Screencast from 2024年01月18日 19時05分10秒.webm](https://github.com/autowarefoundation/autoware_launch/assets/32741405/2e18c328-6e97-491a-96f7-df2055eeccbc) …

feat(start_planner): enable shift path lane departure check

---

autoware_launch/launch/pointcloud_container.launch.py

Fix logger configuration of pointcloud_container from "screen" to "both" so that stdout+stderr are both output to log and terminal.
Not applicable
Now the output of the pointcloud_container will be written both in log and terminal

chore(pointcloud_container): fix output log from screen to both

---

autoware_launch/config/perception/object_recognition/prediction/map_based_prediction.param.yaml

Required by https://github.com/autowarefoundation/autoware.universe/pull/6072
https://github.com/autowarefoundation/autoware.universe/pull/6072
See https://github.com/autowarefoundation/autoware.universe/pull/6072

feat(map_based_prediction): use acc for map prediction

---

autoware_launch/launch/pointcloud_container.launch.py

Move glog declaration for `pointcloud_container` in autoware_launch, where the container is launched.
see https://github.com/autowarefoundation/autoware.universe/pull/6114
No effect expected

chore(pointcloud_container): move glog_component to autoware_launch

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/run_out.param.yaml

I reorganized the parameters of the run out module to enhance the clarity.
autoware universe PR:
- https://github.com/autowarefoundation/autoware.universe/pull/6064
Simple planning simulator

refactor(run_out): reorganize the parameter

---

autoware_launch/config/perception/object_recognition/detection/detection_by_tracker/detection_by_tracker.param.yaml

Organize parameter structure based on https://github.com/autowarefoundation/autoware.universe/pull/4989
Confirmed that the node launches without error, with the parameters loaded successfully.
No effect expected

chore(detection_by_tracker): organize parameter structure

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

Update velocity threshold params to filter stopped vehilce.
With real vehilce. Psim. Evaluator.
Nothing.

fix(avoidance): decrease velocity threshold for avoidance target objects

---

autoware_launch/config/localization/ndt_scan_matcher.param.yaml

see https://github.com/autowarefoundation/autoware.universe/pull/6161
see https://github.com/autowarefoundation/autoware.universe/pull/6161
see https://github.com/autowarefoundation/autoware.universe/pull/6161

fix(ndt_scan_matcher): fix type of critical_upper_bound_exe_time_ms

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml

Parameter changes regarding to https://github.com/autowarefoundation/autoware.universe/pull/6150

feat(crosswalk)!: improve stuck prevention on crosswalk

---

autoware_launch/config/perception/object_recognition/tracking/tracking_object_merger/data_association_matrix.param.yaml

This PR fixes wrong association settings for tracking object merger.
- before: unknown class was not associated each other
- after: unknown objects will associated each other
Tested lsim.
Less unknown objects.

fix(tracking_object_merger): fix unknown is not associated problem

---

autoware_launch/config/simulator/fault_injection.param.yaml
autoware_launch/config/system/system_error_monitor/system_error_monitor.awsim.param.yaml
autoware_launch/config/system/system_error_monitor/system_error_monitor.param.yaml
autoware_launch/config/system/system_error_monitor/system_error_monitor.planning_simulation.param.yaml

This is for the issue https://github.com/autowarefoundation/autoware.universe/issues/3065
This must be merged simultaneously with https://github.com/autowarefoundation/autoware.universe/pull/5178 .
Rename "localization_accuracy" to localization_error_ellipse
It was confirmed that Build is OK.
Start to display `localization_error_ellipse` instead of `localization_accuracy`. …

refactor(system_error_monitor): rename localization_accuracy

---

autoware_launch/config/perception/object_recognition/detection/object_range_splitter/object_range_splitter_radar.param.yaml
autoware_launch/config/perception/object_recognition/detection/object_range_splitter/object_range_splitter_radar_fusion.param.yaml
autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/components/tier4_perception_component.launch.xml

See https://github.com/autowarefoundation/autoware.universe/pull/6159
See https://github.com/autowarefoundation/autoware.universe/pull/6159
See https://github.com/autowarefoundation/autoware.universe/pull/6159

chore(object_range_splitter): rework parameters

---

autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/e2e_simulator.launch.xml
autoware_launch/launch/logging_simulator.launch.xml
autoware_launch/launch/planning_simulator.launch.xml

Implements solution 1 of https://github.com/autowarefoundation/autoware_launch/issues/767
This works:
```bash
$ ros2 launch autoware_launch planning_simulator.launch.xml map_path:=../autoware_data/sample-map-planning
```

feat(autoware_launch): set default vehicle/sensor models to sample ones

---

autoware_launch/config/localization/ndt_scan_matcher.param.yaml

see https://github.com/autowarefoundation/autoware.universe/pull/6208
see https://github.com/autowarefoundation/autoware.universe/pull/6208
see https://github.com/autowarefoundation/autoware.universe/pull/6208

refactor(ndt_scan_matcher): hierarchize parameters

---

autoware_launch/config/perception/object_recognition/detection/lidar_model/pointpainting.param.yaml

See https://github.com/autowarefoundation/autoware.universe/pull/6169
See https://github.com/autowarefoundation/autoware.universe/pull/6169
See https://github.com/autowarefoundation/autoware.universe/pull/6169

chore(image_projection_based_fusion): rework parameters

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml

Necessary for this PR: https://github.com/autowarefoundation/autoware.universe/pull/6242

feat(obstacle_cruise_planner): yield function for ocp

---

autoware_launch/config/localization/ekf_localizer.param.yaml

This is the accompanied pull request of [autoware.universe one](https://github.com/autowarefoundation/autoware.universe/pull/6196).
Please see the description of the main pull request.
1. run autoware & replay rosbag that can start localization(Autoware sample rosbag is recommended).
2. command the following
```
ros2 param dump /localization/pose_twist_fusion_filter/ekf_localizer 
```
expected result
```
/localization/pose_twist_fusion_filter/ekf_localizer:
ros__parameters:
diagnostics:
pose_no_update_count_threshold_error: 100
pose_no_update_count_threshold_warn: 50
twist_no_update_count_threshold_error: 100
twist_no_update_count_threshold_warn: 50
misc:
threshold_observable_velocity_mps: 0.0
node:
enable_yaw_bias_estimation: true
extend_state_step: 50
predict_frequency: 50.0
publish_tf: …
```

refactor(ekf_localizer): rework parameters

---

autoware_launch/config/perception/object_recognition/detection/lidar_model/pointpainting.param.yaml

Remove unnecessary parameter from pointpainting.param.yaml, `build_only`, which was mistakenly introduced in https://github.com/autowarefoundation/autoware.universe/pull/6169
Not applicable
Not applicable

fix(pointpainting): update parameter

---

autoware_launch/launch/components/tier4_perception_component.launch.xml

Add TLR related arguments to tier4_perception_component.launch.xml 
No effects

feat(traffic_light_recognition): add tlr args in tier4_perception_component.launch.xml

---

autoware_launch/config/control/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop_planner.param.yaml

In order to ready for JSON scheme, change ROS params to declare in yaml files.
universe: https://github.com/autowarefoundation/autoware.universe/pull/6217
Not yet

chore(planning/control/vehicle): declare ROS params in yaml files

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml

use different expected deceleration for bike/car on amber/red traffic light
https://tier4.atlassian.net/browse/RT1-4773
see https://github.com/autowarefoundation/autoware.universe/pull/6328
none
none

feat(intersection): use different expected deceleration for bike/car

---

autoware_launch/rviz/autoware.rviz

Changing class name of the overlay plugin + turn signals default color
Part of:
- https://github.com/autowarefoundation/autoware/issues/4146
Should be merged with:
- https://github.com/autowarefoundation/autoware.universe/pull/6323
This will correctly load the plugin into the display
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/ …

refactor(rviz): update the class name and turn signal color

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

change for the [PR](https://github.com/autowarefoundation/autoware.universe/pull/6353)

feat(start/goal_planner): remove unused param and update time horizon for goal planner's safety check

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml

set the target vehicle type for
- stuck vehicle detection
- yield stuck vehicle detection
- collision detection
https://github.com/autowarefoundation/autoware.universe/pull/6325

chore(intersection): target type param

---

autoware_launch/launch/autoware.launch.xml

Removing a leftover `use_pointcloud_container` flag in https://github.com/autowarefoundation/autoware_launch/pull/806.
- Launch logging_simulator and works fine
- Searched with `use_pointcloud_container` and confirmed that it is completely removed (except some intended leftovers in individual packages and tier4_perception_launch)
Not applicable …

fix(autoware_launch): remove use_pointcloud_container flag completely

---

autoware_launch/config/perception/object_recognition/prediction/map_based_prediction.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml

corresponding PR to the https://github.com/autowarefoundation/autoware.universe/pull/6338

feat(map based prediction, crosswalk)!: transplantation of pedestrians' behavior prediction against green signal

---

autoware_launch/config/control/trajectory_follower/longitudinal/pid.param.yaml

Because the slope compensation algorithm changes, we need to adjust parameters.
https://github.com/autowarefoundation/autoware.universe/pull/4712

feat(pid_longitudinal_controller): adjust slope compensation parameters

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

Turning avoidance params:
1. increase shift length to judge parked vehicle.
2. decrease tolerance of path deviation from driable bound.
Nothing.

fix(avoidance): tuning shiftable ratio & deviation param

---

autoware_launch/config/control/trajectory_follower/lateral/mpc.param.yaml

The original MPC can cause the unreasonable predicted trajectory.
For example, the following results are witnessed:
[Screencast from 02-09-2024 12:47:41 PM.webm](https://github.com/tier4/autoware_launch.x1/assets/80969277/8aebf3c4-8689-4448-8a89-8f45d68c174d)
[Screencast from 02-08-2024 04_09_53 PM.webm](https://github.com/tier4/autoware_launch.x1/assets/80969277/8b9a65dc-45c1-414d-a748-c3b370733695)
This is because that the original planned path is extended, making the MPC to track the unreasonable trajectory, especially near the end point of the planned path.
Therefore, this pull request disables this function in the path plan, the trajectory extension, in specific.
By doing so, this aggressive and unreasonable result in the MPC is avoided.
https://tier4.atlassian.net/browse/RT1-5172 …

feat(tier4_control_launch): disable the trajectory extension

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

safety_check_time_horizon should be same or larger than 
```
time_horizon_for_front_object: 10.0
time_horizon_for_rear_object: 10.0
```
https://evaluation.tier4.jp/evaluation/reports/8eb512d3-852a-5934-b44a-520c9f67eb79?project_id=prd_jt

fix(start_planner): fix safety_check_time_horizon

---

autoware_launch/config/system/system_error_monitor/system_error_monitor.awsim.param.yaml
autoware_launch/config/system/system_error_monitor/system_error_monitor.param.yaml

Changed settings in system_error_monitor
localization_stability is a feature added below.
* https://github.com/autowarefoundation/autoware.universe/pull/5935
This change was not reflected in `system_error_monitor.param.yaml`, so this pull request added it.
I also fixed `system_error_monitor.awsim.param.yaml` because it did not take into account other added metrics.
AWSIM + Autoware works fine.
localization_stability has almost no effect as it does not output ERROR level diag. …

fix(system_error_monitor): changed settings of /autoware/localization/performance_monitoring

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

https://github.com/autowarefoundation/autoware.universe/pull/6438
https://github.com/autowarefoundation/autoware.universe/pull/6438
https://github.com/autowarefoundation/autoware.universe/pull/6438
none
none

feat(strat_planner): add a prepare time for blinker before taking action for approval

---

autoware_launch/config/perception/object_recognition/detection/lidar_model/pointpainting.param.yaml

Score_threshold parameter is mistakenly modified by  https://github.com/autowarefoundation/autoware.universe/commit/cc0b1081a74a265a3dac05d5830610242aa0ecd3, so I fixed them.
[TIER IV INTERNAL LINK](https://star4.slack.com/archives/C03S84LDJGG/p1708403287430539?thread_ts=1708400772.055019&cid=C03S84LDJGG)
I did not run autoware with this PR …

fix: recovery default parameter

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

Adding hysteresis to lane change cancel.
Previously, once lane change path is approved, if it is unsafe, the module will cancel the path immediately.
If there are chances that the approval chatters due to the path being safe and unsafe often.
This might be caused by the dismal positional differences between ego and target objects at every time instance.
With this new feature, the path will only be cancelled if the number of unsafe count exceed `unsafe_hysteresis_threshold`. …

feat(lane_change): cancel hysteresis

---

autoware_launch/rviz/autoware.rviz

This PR increases the lightness level of the rviz2 config of the background.
This should lower the contrast and make things easier on the eye.
Also lets the top overlay interface pop out more.

feat(rviz): make rviz2 background lighter, lower the contrast

---

autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/components/tier4_planning_component.launch.xml
autoware_launch/launch/planning_simulator.launch.xml

launch PR for https://github.com/autowarefoundation/autoware.universe/pull/6498
See https://github.com/autowarefoundation/autoware.universe/pull/6498
See https://github.com/autowarefoundation/autoware.universe/pull/6498

feat: add is_simulation variable in autoware.launch.xml

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

Add necessary change for https://github.com/autowarefoundation/autoware.universe/pull/6512

feat(start_planner): allow lane departure check override

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml

refactor(behavior_path_planner): remove unused drivable area parameters

---

.github/workflows/update-codeowners-from-packages.yaml

This adds workflow to update code owners automatically from package.xml and codeowners-manual file.
Related PR: https://github.com/autowarefoundation/autoware_launch/pull/892

feat: add workflow for updating codeowners

---

autoware_launch/launch/e2e_simulator.launch.xml

We are developing a package named reaction analyzer (https://github.com/autowarefoundation/autoware.universe/pull/5954), It will be launched with `e2e_simulator.launch.xml`, however, it won't use the simulation time while launching. So, I added a new variable to enable/disable simulation time.
Tested on reaction analyzer. Works well. …

feat(autoware_launch): add argument to enable/disable simulation time

---

autoware_launch/launch/planning_simulator.launch.xml

This reverts commit 2b510453aa2ea950513067b62248f7aedfbf1b41.
cc. @pawellech1
Related PR:
- https://github.com/autowarefoundation/autoware_launch/pull/746
[Reason from](https://github.com/autowarefoundation/autoware_launch/pull/746#issuecomment-1958721559) @maxime-clem :
> This change prevents from using `use_sim_time:=true` outside of using the `scenario_simulation`.
> Previously I would add the argument to my launch command `ros2 launch ... use_sim_time:=true` but this is no longer possible and I had to revert the changes of this PR.
After all …

revert: feat(autoware_launch): set use_sim_time parameter equal to true when (#746)

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

change for the [PR](https://github.com/autowarefoundation/autoware.universe/pull/6370)

feat(start_planner): add object_types_to_check_for_path_generation

---

autoware_launch/launch/components/tier4_localization_component.launch.xml

[Autoware should cover the use cases where the concatenated pointcloud will be applied as an input to the localization, and we expect that the number of vehicles that use multiple LiDARs will increase.](https://github.com/orgs/autowarefoundation/discussions/4172). 
**Therefore, this PR will change the default `input_pointcloud` to `/sensing/lidar/concatenated/pointcloud` instead of `/sensing/lidar/top/pointcloud`, and change the pointcloud container to `/pointcloud_container` due to this change.**
Plus, I also refactored the name of the argument `lidar_container_name` to `localization_pointcloud_container_name` since the candidate pointcloud container may not be specific to such LiDAR (just like this case), and it makes the argument more clear that it is for the localization component.
Of …

feat(tier4_localization_component_launch): change the default input pointcloud of localization into the concatenated pointcloud

---

autoware_launch/config/planning/preset/default_preset.yaml

Based on the action items in https://github.com/orgs/autowarefoundation/discussions/4052, this PR switches from obstacle_stop_planner to obstacle_cruise_planner.
Part of
- https://github.com/autowarefoundation/autoware/issues/4520
- https://github.com/orgs/autowarefoundation/discussions/3964
planning simulator
The cruise planner will be replaced with obstacle_cruise_planner. …

feat: switch to obstacle_cruise_planner

---

autoware_launch/config/planning/scenario_planning/common/common.param.yaml

The parameter's name was changed unexpectedly by the following PR.
https://github.com/autowarefoundation/autoware_launch/pull/763
simple planning simulator
The parameter will be correctly loaded.

fix: the parameter name of max_vel

---

autoware_launch/config/perception/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml

- As the parameter change at https://github.com/autowarefoundation/autoware.universe/pull/6549

chore: change max_z of cropbox filter to vehicle_height

---

autoware_launch/launch/planning_simulator.launch.xml

Try to achieve the same thing as https://github.com/autowarefoundation/autoware_launch/pull/746
> In order to set global use_sim_time parameter value to True by default when the simulation is run the use_sim_time argument in the planning_simulator launch file was declared. Its value is set to be equal to the scenario_simulation parameter value.
The issue with the previous PR is that it was overriding any `use_sim_time` argument passed as launch argument, preventing users from running Autoware with `ros2 launch ... use_sim_time:=true`.
I tested the following with Psim.
| launch argument | `use_sim_time` |
| --- | --- |
| - | `false` |
| `use_sim_time:=true` | `true` |
| `use_sim_time:=false` | `false` |
| `scenario_simulation:=true` | `true` |
| `scenario_simulation:=false` | `false` | …

feat(planning_simulator): default use_sim_time arg to scenario_simulation

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

See https://github.com/autowarefoundation/autoware.universe/pull/6520.
I tuned hard margin params for vehicle type object in public road test.
```yaml
lateral_margin:
soft_margin: 0.3                           # [m]
hard_margin: 0.2                           # [m]
hard_margin_for_parked_vehicle: 0.7        # [m]
...
envelope_buffer_margin: 0.5 
```
- min: 1.2m (if the lateral margin less than this value, avoidance module inserts stop point until RTC is approved.)
- max: 1.5m
- min: 0.7m (if the lateral margin less than this value, avoidance module inserts stop point until RTC is approved.)
- max: 1.0m
Nothing.
The PR author **must** check the …

fix(avoidance): tune lateral margin params

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

Tune safety check parameter to fix too conservative unsafe judge in situation where the target object is in front of ego.

fix(avoidance): tune safety check params

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml

After testing this feature in both, simulations and real life tests, the feature seems stable and useful for use on real life roads. So, it is enabled by default. 
Original implementation of the yield function corresponds to this PR: https://github.com/autowarefoundation/autoware.universe/pull/6242 …

feat(obstacle_cruise_planner): enable obstacle cruise's yield function by default

---

autoware_launch/launch/components/tier4_perception_component.launch.xml

- To disable the default use of `use_low_height_cropbox` filter which implement for environent with tree and branches above the road.
[TIER IV INTERNAL LINK](https://star4.slack.com/archives/C03S84LDJGG/p1710226856744549?thread_ts=1710221627.379819&cid=C03S84LDJGG)
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pul …

chore: change default of low_height_crop filter use

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml

increase minimum occlusion size that causes slowdown to 1m.
This prevents false occlusion detection caused by noise in the occupancy grid.
Evaluator (TIER IV INTERNAL LINK): https://evaluation.tier4.jp/evaluation/reports/9fe632ec-59a6-53ea-84f3-c147be539013?project_id=prd_jt
Slowdown at crosswalk are less likely to be false positives. …

feat(crosswalk): increase minimum occlusion size that causes slowdown to 1m

---

autoware_launch/config/planning/scenario_planning/common/common.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml

Move slow down min acc and min jerk params to the ocp's params file for better clarity.
Needed for https://github.com/autowarefoundation/autoware.universe/pull/6644

refactor(obstacle_cruise_planner): move slow down params to a clear location

---

autoware_launch/config/system/mrm_handler/mrm_handler.param.yaml

This PR adds a mrm handler param file.
However, mrm handler param path is **not** added to tier4_system_component to give an error that there is no configuration file.

feat: add a param file of a mrm handler node

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

See https://github.com/autowarefoundation/autoware.universe/pull/6355.
Nothing.

refactor(avoidance): update parameter namespace

---

autoware_launch/config/control/autonomous_emergency_braking/autonomous_emergency_braking.param.yaml

I want to add new parameters corresponding to https://github.com/autowarefoundation/autoware.universe/pull/6637
I checked params in https://github.com/autowarefoundation/autoware.universe/pull/6637
- When obstacle point clouds appear below the detection_range_min_height, AEB may no longer be able to activate braking. …

feat(AEB): add detection range params

---

autoware_launch/launch/components/tier4_simulator_component.launch.xml
autoware_launch/launch/planning_simulator.launch.xml

Add dummy doors for planning simulator. See https://github.com/autowarefoundation/autoware.universe/pull/5737 for details.
See https://github.com/autowarefoundation/autoware.universe/pull/5737.
Add door simulation.

feat: add dummy doors for planning simulator

---

autoware_launch/launch/components/tier4_system_component.launch.xml

Add option to use mrm handler. This option is disabled by default.
https://github.com/orgs/autowarefoundation/discussions/4176
This is a sample parameter.
```
<arg name="diagnostic_graph_aggregator_param_path" value="$(find-pkg-share diagnostic_graph_aggregator)/config/default.param.yaml"/>
<arg name="diagnostic_graph_aggregator_graph_path" value="$(find-pkg-share diagnostic_graph_aggregator)/example/graph/main.yaml"/>
``` …

feat: add option to launch mrm handler

---

autoware_launch/launch/components/tier4_system_component.launch.xml

This PR adds option to select the graph path file depending on the mode (planning simulator, logging simulator, real vehicle) [like system_error_monitor](https://github.com/tier4/autoware.universe/blob/79280dd3a3c3e4d9256d0049c1fc7369e46341db/launch/tier4_system_launch/launch/system.launch.xml#L66-L68).
PR for universe
- https://github.com/autowarefoundation/autoware.universe/pull/6700
See https://github.com/autowarefoundation/autoware.universe/pull/6700 …

chore: add option to select graph path depending on running mode

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/dynamic_obstacle_stop.param.yaml

Split the duration buffer of the `dynamic_obstacle_stop` into 2 parameters (for add/remove the decision).
Needed for https://github.com/autowarefoundation/autoware.universe/pull/6683
Psim

feat(dynamic_obstacle_stop): split the duration buffer parameter in 2 (add/remove)

---

autoware_launch/config/localization/pose_initializer.param.yaml
autoware_launch/launch/components/tier4_localization_component.launch.xml

see https://github.com/autowarefoundation/autoware.universe/pull/6692
see https://github.com/autowarefoundation/autoware.universe/pull/6692
see https://github.com/autowarefoundation/autoware.universe/pull/6692
see https://github.com/autowarefoundation/autoware.universe/pull/6692
see https://github.com/autowarefoundation/autoware.universe/pull/6692
see https://github.com/autowarefoundation/autoware.universe/pull/6692
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/ …

feat(pose_initilizer): set intial pose directly

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

[universe:feat(lane_change): check prepare phase in turn direction lanes #6726
](https://github.com/autowarefoundation/autoware.universe/pull/6726)
Make lane change check more stricter in when performing lane change after making a turn.
This is done by performing collision check in the prepare phase.
https://github.com/autowarefoundation/autoware.universe/assets/93502286/6155e1f3-7bc7-4da1-886d-919fbcf6c4c2
https://github.com/autowarefoundation/autoware.universe/assets/93502286/6437f693-f734-4c17-8c7e-4e1eae64a61d
After all checkboxes are checked, …

feat(lane_change): check prepare phase in turn direction lanes

---

autoware_launch/config/control/trajectory_follower/lateral/mpc.param.yaml
autoware_launch/config/control/trajectory_follower/longitudinal/pid.param.yaml

Without specific reasons, the parameters of the controllers should correspond to the parameters of the dynamics.
However, the current version of autoware has a mismatch in these parameters. (https://github.com/autowarefoundation/sample_vehicle_launch/blob/main/sample_vehicle_description/config/simulator_model.param.yaml#L13-L15) 
The detail of the relevant comparison is visualized below:
Therefore, this PR corrects these two parameters in the controller.
`vehicle_model_steer_tau` in mpc.param.yaml and `delay_compensation_time` in pid.param.yaml, in specific.
The corrected controllers will match the dynamics of the vehicle in the simulator.
The PR …

fix(trajectory_follower): accommodate the parameters of the controllers to the dynamics in the simulator.

---

autoware_launch/launch/components/tier4_control_component.launch.xml

see https://github.com/autowarefoundation/autoware_launch/issues/728
In `autoware.launch.xml`:
```launch
<arg name="lat_controller_param_path" default="<path_to_arbitrary_lateral_controller_param_file>" description="lateral controller configuration file location"/>
<arg name="lon_controller_param_path" default="<path_to_arbitrary_longitudinal_controller_param_file>" description="longitudinal controller configuration file location"/>
<group if="$(var launch_control)">
<include file="$(find-pkg-share autoware_launch)/launch/components/tier4_control_component.launch.xml"/>
<arg name="lat_controller_param_path" value="$(var lat_controller_param_path)"/>
<arg name="lon_controller_param_path" value="$(var lon_controller_param_path)"/>
</group>
```
After fixing, arbitrary lateral and …

fix(tier4_control_component_launch): fix duplicate declaration of controller parameter paths

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml

change lateral margin for stop planning 
This PR is related to https://github.com/autowarefoundation/autoware.universe/pull/6754

feat(obstacle_cruise): change stop lateral margin

---

autoware_launch/config/planning/preset/default_preset.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/dynamic_avoidance/dynamic_avoidance.param.yaml

change to avoid pedestrians and bicycle with new feature https://github.com/autowarefoundation/autoware.universe/pull/6553
see https://github.com/autowarefoundation/autoware.universe/pull/6553

feat(dynamic_avoidance): avoid pedestrians

---

autoware_launch/launch/autoware.launch.xml

add option for api launch
TIERIV_INTERNAL_LINK: https://star4.slack.com/archives/C4P0NSMB5/p1713483635225589
I confirmed by following steps.
Use command below
```
ros2 launch autoware_launch autoware.launch.xml vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit map_path:=$HOME/map/sample_map rviz:=false launch_vehicle:=false launch_system:=false launch_map:=false launch_sensing:=false launch_sensing_driver:=false launch_localization:=false launch_perception:=false launch_planning:=false launch_control:=false launch_api:=true
```
And I found that only api launches.
Use command below
```
ros2 launch autoware_launch autoware.launch.xml vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit map_path:=$HOME/map/sample_map rviz:=false launch_vehicle:=false launch_system:=false …
```

feat(api): add launch option

---

autoware_launch/config/perception/object_recognition/detection/image_projection_based_fusion/roi_pointcloud_fusion.param.yaml

- To add parameter for `roi_pointcloud_fusion` as changed in https://github.com/autowarefoundation/autoware.universe/pull/6860
- Since Euclidean_Cluster covers the cluster with [`minimum 10 points`](https://github.com/autowarefoundation/autoware_launch/blob/112e7e6b6f4886a87dd64d573b87efdf189eadc5/autoware_launch/config/perception/object_recognition/detection/clustering/voxel_grid_based_euclidean_cluster.param.yaml#L6), so roi_pointcloud_fusion covering until 20 points should be enough. 
After all checkboxes are checked, anyone who has write access can …

fix(roi_pointcloud_fusion): add param

---

autoware_launch/config/perception/occupancy_grid_map/multi_lidar_pointcloud_based_occupancy_grid_map.param.yaml
autoware_launch/config/perception/occupancy_grid_map/pointcloud_based_occupancy_grid_map.param.yaml

Related https://github.com/autowarefoundation/autoware.universe/pull/6865, this feature add option to accelerate occupancy grid map creation process.

feat(probabilistic_occupancy_grid_map): add downsample filter option to ogm creation 

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

See https://github.com/autowarefoundation/autoware.universe/pull/6808.
Nothing.

fix(avoidance): add target filtering threshold for merging/deviating vehicle

---

autoware_launch/config/simulator/fault_injection.param.yaml
autoware_launch/config/system/system_error_monitor/system_error_monitor.awsim.param.yaml
autoware_launch/config/system/system_error_monitor/system_error_monitor.param.yaml
autoware_launch/config/system/system_error_monitor/system_error_monitor.planning_simulation.param.yaml

see https://github.com/autowarefoundation/autoware.universe/pull/6889
see https://github.com/autowarefoundation/autoware.universe/pull/6889
see https://github.com/autowarefoundation/autoware.universe/pull/6889

feat(system diags): rename diag of ndt scan matcher

---

autoware_launch/config/system/component_state_monitor/topics.yaml

Similar to https://github.com/autowarefoundation/autoware.universe/pull/6563, this PR relaxes the timeout of pose_estimator_pose.
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/6916
Suppressed too much diag warning

chore(component_state_monitor): relax pose_estimator_pose timeout

---

autoware_launch/rviz/autoware.rviz

Update the signal display's traffic display topic to : /planning/scenario_planning/lane_driving/behavior_planning/debug/traffic_signal
Listens to the topic publishing the correct traffic signals data

fix: update traffic topic in autoware.rviz 

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml

Parameter update to follow the change of significance by https://github.com/autowarefoundation/autoware.universe/pull/6033
[Screencast from 04-30-2024 09:16:56 AM.webm](https://github.com/autowarefoundation/autoware.universe/assets/141538661/bc04896b-d5b0-4225-8185-3b083d79573f)
PR in universe https://github.com/autowarefoundation/autoware.universe/pull/6904
psim and tier4 internal test …

feat(crosswalk)!: change a hard coding number and set as param

---

autoware_launch/config/control/autonomous_emergency_braking/autonomous_emergency_braking.param.yaml

Required by: https://github.com/autowarefoundation/autoware.universe/pull/6912
Some refactoring is done too

feat(autonomous_emergency_braking): add obstacle velocity estimation for aeb

---

autoware_launch/rviz/autoware.rviz

This PR aims to add a the implementation needed for mission remaining mission distance and estimated time of arrival (ETA) (or estimated time left)
Part of:
- https://github.com/autowarefoundation/autoware/issues/4593
Depends on :
- https://github.com/autowarefoundation/autoware_internal_msgs/pull/10
- https://github.com/autowarefoundation/autoware.universe/pull/6855
Please check the tests performed in [autoware.universe PR](https://github.com/autowarefoundation/autoware.universe/pull/6855)
For successful compilation and testing, please take into consideration the msg definition in [autoware_internal_msgs PR](https://github.com/autowarefoundation/autoware_internal_msgs/pull/10) and the implementation in [autoware.universe PR](https://github.com/autowarefoundation/autoware.universe/pull/685 …

feat(remaining_dist_eta): add MissionDetailsDisplay plugin rviz configuration

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/out_of_lane.param.yaml

Add parameter for https://github.com/autowarefoundation/autoware.universe/pull/6991
Psim and bag replay.
Reduce wrong stops caused by the `out_of_lane` module.

feat(out_of_lane): add option to ignore overlaps in lane changes

---

.github/labeler.yaml
.github/workflows/pr-labeler.yaml

This PR labels PR automatically depending on edited file names.
Following labels should be added:
- component:control
- component:localization
- component:map
- component:perception
- component:planning
- component:sensing
- component:simulation
- component:system
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull …

ci: add automatic PR labeler

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml

Tune avoidance lateral jerk constraints parameter.

fix(avoidance): change lateral jerk param

---

autoware_launch/config/perception/object_recognition/tracking/multi_object_tracker/input_channels.param.yaml
autoware_launch/config/perception/object_recognition/tracking/multi_object_tracker/multi_object_tracker_node.param.yaml
autoware_launch/launch/components/tier4_perception_component.launch.xml
autoware_launch/launch/components/tier4_simulator_component.launch.xml

Add channel configurations for multi-input multi_object_tracker.
AUTOWARE UNIVERSE PR: https://github.com/autowarefoundation/autoware.universe/pull/6820
[TIER IV INTERNAL](https://tier4.atlassian.net/browse/RT1-6021)
Test with and without the universe update is performed in a local recompute environment.
Default value is single input. 
The overall perception pipeline will work as same as before.
[pull …

feat(multi_object_tracker): add multi object input config file

---

autoware_launch/launch/components/tier4_system_component.launch.xml

Add diagnostic graph settings for https://github.com/autowarefoundation/autoware.universe/pull/7043.

feat: add diagnostic graph settings

---

autoware_launch/rviz/autoware.rviz

Compile Autoware, run planning_sim demo.
(with `ros2 launch autoware_launch planning_simulator.launch.xml map_path:=$HOME/autoware_map/sample-map-planning vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit`)
You will get this red rviz error. (But it will still work)
```console
[rviz2-43] [ERROR 1716801553.757691599] [rviz2]: PluginlibFactory: The plugin for class 'rviz_plugins/StringStampedOverlayDisplay' failed to load. Error: According to the loaded plugin descriptions the class rviz_plugins/StringStampedOverlayDisplay with base class type rviz_common::Display does not exist. Declared types are  autoware_auto_perception_rviz_plugin/DetectedObjects autoware_auto_perception_rviz_plugin/PredictedObjects autoware_auto_perception_rviz_plugin/TrackedObjects …
```

fix(rviz): remove StringStampedOverlayDisplay reference

---

autoware_launch/config/system/diagnostic_graph_aggregator/autoware-awsim.yaml
autoware_launch/config/system/diagnostic_graph_aggregator/autoware-main.yaml
autoware_launch/config/system/diagnostic_graph_aggregator/autoware-psim.yaml
autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/components/tier4_system_component.launch.xml
autoware_launch/launch/e2e_simulator.launch.xml
autoware_launch/launch/logging_simulator.launch.xml
autoware_launch/launch/planning_simulator.launch.xml

Since `diagnostic_graph_aggregator_graph_path` depends on the simulator, I made it possible to specify the path from each launch file. This will replace `system_error_monitor_param_path`. See this [discussion](https://github.com/orgs/autowarefoundation/discussions/4176) for details.
This PR be merged with https://github.com/autowarefoundation/autoware.universe/pull/7133 at the same time.
Diagnostics determine the transition to autonomous mode. So I confirmed whether it was possible to transition to autonomous mode in each simulation. (Logging simulation is not applicable as it does not require a mode change.)
- Run planning simulation (check if it can drive in autonomous mode)
- Run logging simulation (check if the rosbag is visualized with rviz)
- Run E2E simulation (check if it can …

feat(autoware_launch): add diagnostic graph config for awsim

---

autoware_launch/config/perception/object_recognition/detection/object_filter/object_lanelet_filter.param.yaml

This PR changes parameter file related to  https://github.com/autowarefoundation/autoware.universe/pull/7107.

feat(object_lanelet_filter): update object_lanelet_filter parameter yaml

---

autoware_launch/config/perception/object_recognition/prediction/map_based_prediction.param.yaml

this PR is not ready
https://github.com/autowarefoundation/autoware_launch/pull/967
this PR is not ready
https://github.com/autowarefoundation/autoware_launch/pull/967
this is revert
none
none

revert(map_based_prediction): use different time horizon (#967)

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml

Required by https://github.com/autowarefoundation/autoware.universe/pull/7160
PSim

feat(behavior_path_planner_common,turn_signal_decider): add turn_signal_remaining_shift_length_threshold

---

autoware_launch/config/perception/object_recognition/prediction/map_based_prediction.param.yaml

https://github.com/autowarefoundation/autoware.universe/pull/7157
https://github.com/autowarefoundation/autoware.universe/pull/7157
none
none

feat(map_based_prediction): use different time horizon

---

autoware_launch/rviz/autoware.rviz

Rename plugin name from autoware_auto_perception_rviz_plugin to autoware_perception_rviz_plugin
This must be merged with https://github.com/autowarefoundation/autoware.universe/pull/7221.
Locally tested with planning_simulator that dummy obstacles are still visible after the update.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/p …

feat: rename autoware_auto_perception_rviz_plugin to autoware_perception_rviz_plugin

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml

see universe PR: https://github.com/autowarefoundation/autoware.universe/pull/7121

feat(obstacle_cruise)!: type specified stop deccel limit and enabling abandon to stop

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

- remove unused param
- deceleration_interval
- arc_path_interval
- th_turn_signal_on_lateral_offset
- intersection_search_length
- length_ratio_for_turn_signal_deactivation_near_intersection
related with the [PR](https://github.com/autowarefoundation/autoware.universe/pull/7430)
run psim
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-reques …

refactor(start_planner): remove unused parameters in start planner module

---

autoware_launch/config/control/autoware_autonomous_emergency_braking/autonomous_emergency_braking.param.yaml

PR required by https://github.com/autowarefoundation/autoware.universe/pull/7493

feat(autonomous_emergency_braking): add param to toggle on or off object speed calc for aeb

---

autoware_launch/config/control/autoware_autonomous_emergency_braking/autonomous_emergency_braking.param.yaml

Required by https://github.com/autowarefoundation/autoware.universe/pull/7548

feat(autonomous_emergency_braking): add params to enable or disable PC and predicted objects

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/static_obstacle_avoidance.param.yaml

See https://github.com/autowarefoundation/autoware.universe/pull/7591.
Nothing.

feat(static_obstacle_avoidance)!: add param to select path generation method

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/static_obstacle_avoidance.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

Required by https://github.com/autowarefoundation/autoware.universe/pull/7657

feat(behavior_path_planner): add yaw threshold param

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/static_obstacle_avoidance.param.yaml

See https://github.com/autowarefoundation/autoware.universe/pull/7715.
Psim
Nothing.

refactor(static_obstacle_avoidance): organize params for drivable lane

---

autoware_launch/launch/components/tier4_system_component.launch.xml

See https://github.com/autowarefoundation/autoware.universe/pull/7728.
**Parent Issue:**
- https://github.com/orgs/autowarefoundation/discussions/4176
- https://github.com/autowarefoundation/autoware.universe/pull/7728
None.
None.
None.

feat(autoware_launch): use mrm handler by default

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/scene_module_manager.param.yaml

The max_module_size param has been removed from the behavior_path_planner scene_module_manager.param.yaml file. This param was unnecessary and has been removed to simplify the configuration.
parameter change for the [PR](https://github.com/autowarefoundation/autoware.universe/pull/7764)
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributi …

feat(behavior_path_planner): remove max_module_size param

---

autoware_launch/config/localization/eagleye_config.param.yaml

From today, Eagleye has been applicable to `septentrio_gnss_driver/PVTGeodetic` type topic messages as a velocity source.
https://github.com/MapIV/eagleye/pull/334
So, I wrote that down to the comment in `eagleye_config.param.yaml` file.
I've tested this against a driving data that uses septentrio GNSS sensors by setting the `velocity_source_type` to 4, and confirmed that the latest Eagleye works well with this. [[INTERNAL_LINK(TIER IV)](https://tier4.atlassian.net/wiki/x/CwFRvg)]
You can use `septentrio_gnss_driver/PVTGeodetic` type messages to give ENU velocity to Eagleye.
After all …

chore(eagleye): add septentrio msg option in eagleye_config

---

.github/workflows/pre-commit-autoupdate.yaml

Add `pre-commit-autoupdate` from:
- https://github.com/autowarefoundation/autoware_common/blob/a7e776a47e309fba1b1ab7c14ecd2d51aa2e39f7/.github/workflows/pre-commit-autoupdate.yaml
We can set up the sync-files job later.

ci(pre-commit-autoupdate): add new workflow

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/static_obstacle_avoidance.param.yaml

- See https://github.com/autowarefoundation/autoware.universe/pull/7954

fix(static_obstacle_avoidance): check stopped time in freespace

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml

Change configuration for obstacle stop behavior to guarantee the stop margin for all objects.
Confirmed it passed ALL TIER IV INTERNAL scenarios.

fix(obstacle_cruise_planner): guarantee the stop margin

---

autoware_launch/config/control/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml

This PR relax the pedal rate limit value when the vehicle velocity is slow enough to achieve stop/go on the slopes.
universe PR: https://github.com/autowarefoundation/autoware.universe/pull/7720
I have tested this change by two type of real vehicles.

feat(vehicle_cmd_gate): change param to relax pedal rate limit when the vehicle velocity is slow enough

---

autoware_launch/config/control/trajectory_follower/longitudinal/pid.param.yaml

launch side PR corresponds to a universe PR https://github.com/autowarefoundation/autoware.universe/pull/7720
see universe PR

feat(pid_longitudinal_controller): re-organize diff limit structure

---

autoware_launch/config/planning/scenario_planning/common/costmap_generator.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
autoware_launch/config/planning/scenario_planning/parking/freespace_planner/freespace_planner.param.yaml

Modified parameters for freespace planner (as well as goal planner and start planner) corresponding to the changes implemented in the following PR's:
- https://github.com/autowarefoundation/autoware.universe/pull/8068
- https://github.com/autowarefoundation/autoware.universe/pull/8089
- https://github.com/autowarefoundation/autoware.universe/pull/8091
(Note: merge with or after above PR's)
Tested on psim.
more configuration options for A star planner:
- can configure search method (backward or forward)
- can tune cost for curvature
- can tune cost for smoothness
- can tune cost for distance to obstacles
- can configure expansion distance value, and set to adaptive
The PR reviewers **must** check the checkboxes below …

feat(freespace_planning_algorithm): update freespace planner params

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml

Tuned the parameter of the crosswalk in the experiment.
Currently, the ego is very aggressive when the ego crosses the crosswalk before the pedestrians.
With this PR, in that case, the ego can keep enough time.
Experiment in the city of Tokyo
scenario test: https://evaluation.tier4.jp/evaluation/reports/c3868fc8-6886-582f-bf09-8f96a24e0478?project_id=prd_jt …

feat(crosswalk): more conservative when the ego pass first

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/dynamic_obstacle_avoidance.param.yaml

Tuned the following parameter in the experiment.
- The horizon time of the pedestrians/bicycles' predicted path to cut the drivable area by the dynamic obstacle avoidance module.
scenario test: https://evaluation.tier4.jp/evaluation/reports/9be5175a-311e-58b9-8f23-7d5a35e99aa3?project_id=prd_jt
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/co …

feat(dynamic_obstacle_avoidance): shorter predicted path for pedestrians

---

autoware_launch/config/planning/scenario_planning/parking/freespace_planner/freespace_planner.param.yaml

Tune freespace planner parameters to improve quality of generated path
see https://github.com/autowarefoundation/autoware.universe/pull/8091

perf(freespace_planning_algorithms): tune freespace planner parameters

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/static_obstacle_avoidance.param.yaml

Add parameter for force deactivation duration time in static obstacle avoidance cancel parameter.
For detailed information refer to [related PR](https://github.com/autowarefoundation/autoware.universe/pull/8288)
None

feat(static_obstacle_avoidance): add force deactivation duration time

---

autoware_launch/config/control/trajectory_follower/lateral/mpc.param.yaml
autoware_launch/rviz/autoware.rviz

Regarding the visualization of the predicted trajectory by MPC, previously the trajectory in the frenet frame was used, but the one in the world coordinate is currently used by the following PR.
https://github.com/autowarefoundation/autoware.universe/pull/5576
However, the predicted trajectory in the world coordinate has a bug as shown in the following video.
- white: predicted trajectory in the world coordinate
- pink: predicted trajectory in the frenet frame
[Screencast from 2024年08月09日 01時15分36秒.webm](https://github.com/user-attachments/assets/423b0c8e-1484-49d9-819e-379a10aed736)
Therefore, as a temporal solution, this PR started to visualize the predicted trajectory in the frenet frame on Rviz again.
psim
The PR author **must** check the checkboxes below when creating …

fix(mpc_lateral_controller): publish predicted trajectory in Frenet coordinate and visualize it on Rviz

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/static_obstacle_avoidance.param.yaml

Change policy for behavior when system can't judge whether it should be avoid or not. After this PR, the avoidance module doesn't avoid vehicle automatically in ambiguous situation and makes cooperate request for operator by default.
:warning: Merge with https://github.com/autowarefoundation/autoware.universe/pull/8433.
- https://evaluation.tier4.jp/evaluation/reports/8285a43d-c029-5bc1-a1e6-c481ac5ac2de/tests/cec7e554-024c-559a-b70d-bd7381c124a0/fdc1641a-78fc-5f23-86bf-9f3bb2790d27?project_id=prd_jt&state=failed
- https://evaluation.tier4.jp/evaluation/reports/8285a43d-c029-5bc1-a1e6-c481ac5ac2de/tests/cec7e554-024c-559a-b70d-bd7381c124a0/5a521255-3f4a-5cdc-9835-090b90d714a9?project_id=prd_jt&state=failed
The PR author **must** check the checkboxes below …

feat(static_obstacle_avoidance): change policy for ambiguous avoidance situation

---

autoware_launch/launch/components/tier4_simulator_component.launch.xml
autoware_launch/launch/planning_simulator.launch.xml

This PR changes a configuration variable from a bool type to a string type to allow more flexibility in configuring the localization module to be activated in psim.
This PR does not change the behavior.
This PR is a part of the following issue, and a new mode will be added in a few weeks.
https://github.com/autowarefoundation/autoware_launch/issues/1100
universe PR: https://github.com/autowarefoundation/autoware.universe/pull/8331
In psim, we verified that the activated nodes are properly switched.
There was also no problem in executing scenario_sim. 
internal link: https://evaluation.tier4.jp/evaluation/reports/bc29eeab-daa3-55e1-8446-400bdb049517?project_id=prd_jt
The PR reviewers **must** check the …

feat(psim)!: change a setting parameter type from bool to string

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

This PR updates the following two parameters:
1. `longitudinal_velocity_delta_time` for all RSS category
2. `use_all_predicted_path`
Currently due to having these parameters set, lane change have become too conservative.
In consequences, it has caused a lot of unintended lane change cancel during experiment.
These changes has been tested in experiment at odaiba and unintended cancel has been reduced and there is no critical issues observed. …

fix(lane_change): parameter update

---

autoware_launch/launch/components/tier4_simulator_component.launch.xml
autoware_launch/launch/planning_simulator.launch.xml

This PR is a part of the following issue:
https://github.com/autowarefoundation/autoware_launch/issues/1100
This PR provides launch settings to launch Localization modules on psim.
By setting `localization_sim_mode` as `pose_twist_estimator`, most of  localization modules without ndt_localizer will be launched.
Note that the frequency of ekf_localizer and vehicle_sim are required to handle carefully. Frequency setting is under analysis and consideration.
universe PR: https://github.com/autowarefoundation/autoware.universe/pull/8212
psim tests and scenario simulator
https://evaluation.tier4.jp/evaluation/reports/16cc961f-f08b-527a-b2fa-120dd899dd5d?project_id=prd_jt (internal link)
Note that the scenario simulator is not supported by this PR.
The PR author **must** check …

feat(psim)!: preapre settings to launch localization modules on psim

---

autoware_launch/config/perception/object_recognition/tracking/multi_object_tracker/input_channels.param.yaml

Fix a typo error of lidar_pointpainting
lidar_pointpainitng -> lidar_pointpainting
This PR need to be merged with https://github.com/autowarefoundation/autoware.universe/pull/8515

chore(autoware_multi_object_tracker): fix typo in input_channels

---

autoware_launch/launch/components/tier4_perception_component.launch.xml

Add `lidar_detection_model` option in `tier4_perception_launch` according to https://github.com/autowarefoundation/autoware.universe/pull/6890.
The default model: centerpoint won't change in this PR. 

feat(tier4_perception_launch): add transfusion option for lidar_detection_model

---

autoware_launch/config/planning/scenario_planning/common/costmap_generator.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml
autoware_launch/config/planning/scenario_planning/parking/freespace_planner/freespace_planner.param.yaml

Add new parameters related to changes in following PR:
- https://github.com/autowarefoundation/autoware.universe/pull/8092

feat(freespace_planning_algorithms): add new parameters for astar planning algorithm

---

autoware_launch/config/control/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml

Delete deprecated parameters in `vehicle_cmd_gate.param.yaml`
The following parameters have been removed as they are no longer used by `vehicle_cmd_gate` node.
- `use_start_request`
- `stopped_state_entry_duration_time`
PR for autoware.universe: https://github.com/autowarefoundation/autoware.universe/pull/8537
PSim test was performed. …

chore(vehicle_cmd_gate): delete deprecated parameters

---

autoware_launch/launch/e2e_simulator.launch.xml

To launch a sensing driver (e.g. Nebula) via argument control, I added `launch_sensing_driver` arg in the launch file.
Added a log message in the autoware.launch.xml, and confirmed the argument control works fine.
I also tested with AWSIM to ensure the sensor driver launched correctly. Since the test was conducted locally, I will omit the details here.
None since the default parameter is not changed.
`launch_sensing_driver` variable can be controlled via CLI like below:
```
ros2 launch autoware_launch e2e_simulator.launch.xml launch_sensing_driver:=true 
```
After all checkboxes are …

chore(e2e_launch): add launch_sensing_driver arg

---

autoware_launch/config/localization/stop_filter.param.yaml
autoware_launch/launch/components/tier4_localization_component.launch.xml

Enable to set the `param_path` of `stop filter.param.yaml`.
Especially expected to get from autoware_launch.
**This PR has to work and be merged with https://github.com/autowarefoundation/autoware.universe/pull/8681 together.**
1. Checked that [rosbag replay tutorial](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/) works.
2. Checked that `ros2 param dump /localization/pose_twist_fusion_filter/stop_filter` return the following. When I changed `vx_threshold` to 1.1.
```
/localization/pose_twist_fusion_filter/stop_filter:
ros__parameters:
qos_overrides:
/clock:
subscription:
depth: 1
durability: volatile
history: keep_last
reliability: best_effort
/parameter_events:
publisher:
depth: 1000
durability: volatile
history: …
```

chore(stop_filter): extract stop_filter.param.yaml to autoware_launch

---

autoware_launch/config/perception/object_recognition/detection/lidar_model/transfusion.param.yaml

PR adds config to `autoware_lidar_transfusion` package.
Linked PRs:
- https://github.com/autowarefoundation/autoware.universe/pull/8205
- https://github.com/autowarefoundation/autoware/pull/5036

feat(autoware_lidar_transfusion): add transfusion config

---

.github/CODEOWNERS-manual

Add Taekjin Lee (myself) to the maintainer of the perception launcher and the perception parameters

chore: add taekjin lee to perception launcher and configuration maintainer

---

autoware_launch/config/control/trajectory_follower/lateral/mpc.param.yaml
autoware_launch/config/perception/object_recognition/tracking/tracking_object_merger/decorative_tracker_merger.param.yaml
autoware_launch/rviz/autoware.rviz

Necessary chenge for the [PR](https://github.com/autowarefoundation/autoware.universe/pull/8436).
run psim and confimed visualization with rviz
| Line Color | Description | Coordinate | Topic Name |
|------------|-------------|------------|------------|
| 🔵 Blue (dotted) | Reference trajectory | World | `/control/trajectory_follower/controller_node_exe/debug/resampled_reference_trajectory` |
| ⚪ White | Predicted trajectory | World | `/control/trajectory_follower/controller_node_exe/debug/predicted_trajectory_with_delay` |
After all checkboxes are checked, anyone who …

feat(autoware_mpc_lateral_controller): add resampled reference trajectory for debug purpose

---

autoware_launch/config/perception/obstacle_segmentation/occupancy_grid_based_outlier_filter/occupancy_grid_map_outlier_filter.param.yaml

This PR will add parameter `publish_processing_time_detail` for time keeper feature to `occupancy_grid_map_outlier_filter`.
Related to https://github.com/autowarefoundation/autoware.universe/pull/8597/
When `publish_processing_time_detail` is
- `true`: enable the [TimeKeeper](https://github.com/autowarefoundation/autoware.universe/tree/d75f87520e6af854ee3cf2a05738afe88254c2f3/common/autoware_universe_utils) for tracking processing time in detail
- `false`: disable the feature, no topic will be sent
After all checkboxes are checked, anyone who has write …

feat(occupancy_grid_map_outlier_filter): add option for time keeper

---

autoware_launch/config/perception/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml

This PR will add parameter `publish_processing_time_detail` for time keeper feature.
Related to https://github.com/autowarefoundation/autoware.universe/pull/8585
When `publish_processing_time_detail` is
- `true`: enable the [TimeKeeper](https://github.com/autowarefoundation/autoware.universe/tree/d75f87520e6af854ee3cf2a05738afe88254c2f3/common/autoware_universe_utils) for tracking processing time in detail
- `false`: disable the feature, no topic will be sent
[contribution …

feat(ground_segmentation): add option for time keeper

---

autoware_launch/config/perception/occupancy_grid_map/laserscan_based_occupancy_grid_map.param.yaml
autoware_launch/config/perception/occupancy_grid_map/multi_lidar_pointcloud_based_occupancy_grid_map.param.yaml
autoware_launch/config/perception/occupancy_grid_map/pointcloud_based_occupancy_grid_map.param.yaml
autoware_launch/config/perception/occupancy_grid_map/synchronized_grid_map_fusion_node.param.yaml

This PR will add parameter `publish_processing_time_detail` for time keeper feature to `occupancy_grid_map`.
Related to https://github.com/autowarefoundation/autoware.universe/pull/8601
When `publish_processing_time_detail` is
- `true`: enable the [TimeKeeper](https://github.com/autowarefoundation/autoware.universe/tree/d75f87520e6af854ee3cf2a05738afe88254c2f3/common/autoware_universe_utils) for tracking processing time in detail
- `false`: disable the feature, no topic will be sent
After all checkboxes are checked, anyone who has write access can merge …

feat(occupancy_grid_map): add option for time keeper

---

autoware_launch/launch/components/tier4_perception_component.launch.xml

- This PR to add image_segmentation_based_filter option param into `tier4_perception_component` and still keeps `default=false`

chore(tier4_pereption_component): add image_segmentation_based_filter option param

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/run_out.param.yaml

This PR changes some default parameters for the run out module to make it more responsive.
Details on changed params: 
**time_threshold** : This parameter makes it so the run_out module does NOT issue a stop wall unless it detects a collision with a pedestrian/bicycle for more than time_threshold seconds, currently this parameter is set to 0.5 seconds, which is too long in my opinion, I would like to reduce this value to 0.15 seconds (I would also like to know how the ego behaves if this feature is disabled by setting the ignore_momentary_detection.enable parameter to false). I believe the reason for increasing the value in the first case was to reduce the occurrence of unwanted run out activation, but I believe the module has improved enough for this parameter to be returned to 0.15 …

feat(run_out): speed up run out response

---

autoware_launch/launch/components/tier4_perception_component.launch.xml

This PR enable to use multi camera(more than 3 cameras) on traffic light recognition
We need to merge[universe PR](https://github.com/autowarefoundation/autoware.universe/pull/8676) at same time.
I have tested this on local DLR and [Evaluator](https://evaluation.ci.tier4.jp/evaluation/reports/de03c639-c8c1-562c-b5d8-6a6d1237a378?project_id=prd_jt) when I use 1 or 2 traffic light cameras. And I checked node is started correctly when I choose 3 or 4 cameras. …

feat(tier4_perception_launch): enable to use multi camera on traffic light recognition

---

autoware_launch/launch/components/tier4_perception_component.launch.xml
autoware_launch/launch/e2e_simulator.launch.xml

This PR enable to adopt awsim camera topic.
link
- https://github.com/autowarefoundation/autoware.universe/pull/8676
- https://github.com/autowarefoundation/autoware_launch/pull/1144
I have checked on AWSIM

fix(perception): adopt awsim (tlr) camera topic

---

autoware_launch/rviz/autoware.rviz

Running with AWSIM Labs,
- https://github.com/autowarefoundation/autoware_launch/pull/1164
This PR reduced the speed of RViz2 from 31 stable fps down to 5 fps.
This is due to 1000 buffer size and the addition of about 1000 or 2000? new sphere markers due to this covariance visualization.
This PR reverts this change and restores RViz2 speed.
Tested with AWSIM Labs.
- https://github.com/autowarefoundation/AWSIM-Labs/releases
- https://autowarefoundation.github.io/AWSIM-Labs/main/
- https://autowarefoundation.github.io/AWSIM-Labs/main/GettingStarted/QuickStartDemo/
After …

revert: feat: change visualization of localization results from PoseHistory to PoseWithCovarianceHistory (#1164)

---

autoware_launch/config/control/autoware_autonomous_emergency_braking/autonomous_emergency_braking.param.yaml

This PR adds the speed_calculation_expansion_margin parameter to the autonomous_emergency_brake parameter file.
Related:
- https://github.com/autowarefoundation/autoware.universe/pull/8591

feat(autonomous_emergency_braking): initiate speed_calculation_expansion_margin parameter

---

autoware_launch/config/localization/pose_initializer.param.yaml

- Add new parameter for check initial pose error with gnss(https://github.com/autowarefoundation/autoware.universe/pull/8947).
- Check 2D(x-y) Error between Initial Pose result and GNSS Pose, if pose error is large, output an message in the /diagnostics topic.
- This feature is off by default, but can be enabled by setting pose_error_check_enabled to true when the GNSS is reliable, such as RTK-GNSS.
https://github.com/autowarefoundation/autoware.universe/pull/8947
- checkout autoware.universe to [feat/initial_pose_check_with_gnss](https://github.com/autowarefoundation/autoware.universe/pull/8947)
- Check that localization works correctly in logging_simulator.
- Set pose_error_check_enabled to True and check that diagnostics (gnss_pose_error_2d, is_gnss_pose_error) are output. If set to …

feat(pose_initializer): add new parameter for check error between initial pose and GNSS pose

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml

Fixes :
- https://github.com/autowarefoundation/autoware.universe/issues/7922
- https://github.com/autowarefoundation/autoware.universe/issues/7877
- https://github.com/autowarefoundation/autoware.universe/issues/8311
Parent Issue :
- https://github.com/autowarefoundation/autoware.universe/issues/7485
https://github.com/user-attachments/assets/9d9f7398-7448-4a2c-a51c-e7591450b416
https://github.com/user-attachments/assets/3b214e68-c53b-4167-910c-fd48fb12c3ef
https://github.com/user-attachments/assets/b7c98cce-caa9-4f1a-9225-06309c248302
https://github.com/user-attachments/assets/32040fb6-512b-4d2c-9dc1-b5ebd47f264d
---
https://github.com/user-attachments/assets/8b8e2c3b-810c-4084-8075-9520944a1f11
https://github.com/user-attachments/assets/640cf170-be59-49ce-8e72-30a5a00fd57e …

fix(obstacle_cruise_planner): tune obstacle_cruise_planner for cruising front NPCs in dense urban ODD scenarios

---

autoware_launch/config/perception/object_recognition/detection/clustering/voxel_grid_based_euclidean_cluster.param.yaml

- To add missing default paramter after https://github.com/autowarefoundation/autoware.universe/pull/8466

chore(crop_box_filter): add missing default parameter

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml

- Required from:
- https://github.com/autowarefoundation/autoware.universe/pull/8072

feat(obstacle_cruise_planner): improve stop and cruise behavior for cut-in & out

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml

Now we can achieve a stop with a margin for interrupts, thanks to the stop with predicted_path by @brkay54 https://github.com/autowarefoundation/autoware.universe/pull/8072. Since the need for sudden stops has been reduced, we will revert this parameter.
This reverts the PR https://github.com/autowarefoundation/autoware_launch/pull/1076
scenario tests …

revert(obstacle_cruisse): revert "fix(obstacle_cruise_planner): guarantee the stop margin (#1076)"

---

.github/workflows/build-and-test-differential.yaml
.github/workflows/build-and-test.yaml
.github/workflows/cancel-previous-workflows.yaml
.github/workflows/check-build-depends.yaml
.github/workflows/pr-labeler.yaml
.github/workflows/pre-commit-autoupdate.yaml
.github/workflows/update-codeowners-from-packages.yaml
.github/workflows/update-sync-param-files.yaml

This PR changes the runs-on value to ubuntu-22.04 instead of ubuntu-latest.
Related PR
- https://github.com/autowarefoundation/autoware/pull/5320
- https://github.com/autowarefoundation/autoware_launch/pull/1188

fix(.github): change runs-on value to to ubuntu-22.04

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml

Set `occluded_object_velocity` to 2.0 to make the crosswalk module more conservative around occlusions.

feat(crosswalk_module): set the velocity of occluded objects to 2.0m/s

---

autoware_launch/launch/components/tier4_simulator_component.launch.xml

follow up https://github.com/autowarefoundation/autoware_launch/pull/1145
https://github.com/autowarefoundation/autoware.universe/pull/9127
psim tests

chore(simple_planning_simulator): add stop_filter_param_path

---

autoware_launch/config/control/control_validator/control_validator.param.yaml

This PR add holding function and LPF for the velocity check.
in additon, velocity check is separated to two diags.
universe PR: https://github.com/autowarefoundation/autoware.universe/pull/9120
tier4 internal tests

feat(control_validator): add hold and lpf

---

autoware_launch/config/system/processing_time_checker/processing_time_checker.param.yaml

To be able to check the values of the modules added in the relationship PR in the scenario.
To be able to measure module processing time periodically by scenario.And leads to the following
-> Prevention of cycle failures.
-> Suggestion to improve module processing speed.
Added 5 module paths to processing_time_checker.yml to read processing_time_pub from the scenario.
[discussion slack link](https://star4.slack.com/archives/C03QW0GU6P7/p1727926601208209?thread_ts=1727851666.022839&cid=C03QW0GU6P7)
(I have not discussed this on github.)
From the red circle in the image, you can see that the value of the module you have just added is retrieved when the scenario is turned on locally. (Sorry for the small text 🙇‍♂)
[Changes on the universe side (already …

feat(processing_time_checker): add five module.

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

Based on https://github.com/autowarefoundation/autoware.universe/pull/4889, this parameter can be set back to 0.0, bringing back some functionality to the start planner.
In the video its shown how with the parameter ignore_distance_from_lane_end: 0.0, the start planner can create a shift pull out path without having to move backwards in an awkward way. 
PSim 
https://github.com/user-attachments/assets/e9df6faf-fb60-41bd-b78a-1c7aeb303d35
Degradation check: [TIER IV PRIVATE LINK](https://evaluation.ci.tier4.jp/evaluation/reports/3c084938-32db-5daf-8e9e-38cbfbc13128?project_id=prd_jt)
The PR author **must** check the checkboxes below …

fix(start_planner): set  ignore_distance_from_lane_end param to 0.0 since it is not needed

---

.prettierignore
autoware_launch/config/system/diagnostic_graph_aggregator/autoware-awsim.yaml
autoware_launch/config/system/diagnostic_graph_aggregator/autoware-main.yaml
autoware_launch/config/system/diagnostic_graph_aggregator/autoware-psim.yaml
autoware_launch/config/system/system_diagnostic_monitor/autoware-main.yaml
autoware_launch/config/system/system_diagnostic_monitor/autoware-psim.yaml
autoware_launch/config/system/system_diagnostic_monitor/control.yaml
autoware_launch/config/system/system_diagnostic_monitor/hardware.yaml
autoware_launch/config/system/system_diagnostic_monitor/localization.yaml
autoware_launch/config/system/system_diagnostic_monitor/map.yaml
autoware_launch/config/system/system_diagnostic_monitor/perception.yaml
autoware_launch/config/system/system_diagnostic_monitor/planning.yaml
autoware_launch/config/system/system_diagnostic_monitor/system.yaml
autoware_launch/config/system/system_diagnostic_monitor/vehicle.yaml

To follow our standard manner, This PR change the config file directories from the universe to the autoware_launch.

chore(diagnostic_graph_aggregator, system_diagnostic_monitor)!: change the config file directories from universe to autoware_launch

---

autoware_launch/config/control/autoware_collision_detector/collision_detector.param.yaml
autoware_launch/launch/components/tier4_control_component.launch.xml

This PR adds the collision detector package in the control component launch.
The default value is set to false. (collision detector node would not start in default)
Look at [Github issue](https://github.com/autowarefoundation/autoware.universe/issues/9145) for detailed information.
PSim
[Screencast from 2024年11月01日 14時27分07秒.webm](https://github.com/user-attachments/assets/3e6a9bea-2a59-4e45-8f7e-c41343e9d52c) …

feat(collision detector): add collision detector to launch/config

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml

better to keep margin to lane bound to avoid collision
https://evaluation.tier4.jp/evaluation/reports/3b62705e-dfd4-525d-b2eb-5c3b1a9865dd?project_id=prd_jt

feat(goal_planner): set lane departure check margin 0.3

---

autoware_launch/launch/components/tier4_localization_component.launch.xml

Currently, Autoware cannot accept the argument `ndt_scan_matcher/ndt_scan_matcher_param_path`.
NG)
```bash
ros2 launch autoware_launch logging_simulator.launch.xml \
map_path:=$MAP \
ndt_scan_matcher/ndt_scan_matcher_param_path:=/your/path
```
This is because the argument is overwritten in `tier4_localization_component.launch.xml`.
https://github.com/autowarefoundation/autoware_launch/blob/642eb3e5a9dbb128e114135d681c2098abdecd9f/autoware_launch/launch/components/tier4_localization_component.launch.xml#L27
The `loc_config_path` is not an argument, as it is declared using `let`.
https://github.com/autowarefoundation/autoware_launch/blob/642eb3e5a9dbb128e114135d681c2098abdecd9f/autoware_launch/launch/components/tier4_localization_component.launch.xml#L3
Also NG)
```bash
ros2 launch …
```

fix: changed `loc_config_path` declaration from let to arg

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

When performing a lane change after an intersection, nearby vehicle might attempt to overtake the ego vehicle. Although simulations may suggest the maneuver is safe, real world testing shows it can feel unsafe. This is particularly true in intersections, where surrounding vehicle often exhibits significant speed variations and unpredictable behavior.
The image below illustrates  such a scenario.
In this situation, rear vehicle may either stop abruptly or accelerate suddenly, making it challenging for the safety check to produce reliable result.
This PR addresses the issue by making the lane change module adopt a more conservative approach near intersection.
If the ego vehicle is within an intersection and currently in a turn lane, the lane change module will output an invalid path. …

feat(lane_change): enable cancel when ego in turn direction lane main (RT0-33893)

---

autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/e2e_simulator.launch.xml
autoware_launch/launch/planning_simulator.launch.xml
autoware_launch/rviz/perception.rviz
autoware_launch/rviz/planning_bev.rviz
autoware_launch/rviz/planning_tpv.rviz

Add new rviz config for debugging. (Move from [TIER IV internal repo](https://github.com/tier4/debug_tools/tree/main/rviz_config).)
- `perception.rviz`: rviz config for perception component.
- `planning_bev.rviz`: rviz config for planning/control component. (bird eye view.)
- `planning_tps.rviz`: rviz config for planning/control component. (third person view.)
Make it possible to select rviz config more easily. User can select rviz config as follow.
```
rviz_config_name:=planning_bev.rviz
```
```
ros2 launch autoware_launch planning_simulator.launch.xml map_path:=<MAP>  vehicle_model:=<VEHICLE_MODEL> sensor_model:=<SENSOR_MODEL> rviz_config_name:=planning_bev.rviz
```
The PR reviewers **must** check …

feat(rviz): add rviz config for debugging

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml

the margin 0.3 is same to avoidance module and the judge is dirrent.
so sometimes avoidance allow the pass but goal planner dones not. this causes stuck.
In this PR, decrease margin in goal planner side.
https://github.com/autowarefoundation/autoware_launch/blob/fb963dec89b73ae78f6e91eaa2556cefd2580c14/autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/static_obstacle_avoidance.param.yaml#L223-L224
https://evaluation.tier4.jp/evaluation/reports/b831b1b8-3369-5628-a394-da4da8a04836?project_id=prd_jt
4048/4048
https://star4.slack.com/archives/C07F96ZTVGC/p1730885499632059?thread_ts=1730882551.439009&cid=C07F96ZTVGC
The PR author **must** check the checkboxes below when …

feat(goal_planner): set lane departure check margin 0.20

---

autoware_launch/config/system/system_monitor/net_monitor.param.yaml

- This PR adds a new config into `net_monitor.param.yaml` corresponding to https://github.com/autowarefoundation/autoware.universe/pull/9069

feat(system_monitor): add on/off config for network traffic monitor

---

autoware_launch/config/control/trajectory_follower/longitudinal/pid.param.yaml

Previously, there was a hysteresis between `drive_state_stop_dist` and `stopping_state_stop_dist` so that the state transition of DRIVE <--> STOPPED will not chatter.
However, the following commit removed the hysteresis by mistake, so this PR revived it.
https://github.com/autowarefoundation/autoware_launch/commit/c6a3df8be00302a72f6fd2c447db7faf0d80475f#diff-a311c12a65b491b5b4c0e9e5ee83bc1488a360826fe46e4204355c9fe009127eL14
unit test
No chattering of the DRIVE/STOPPED state transition in pid_longitudinal_controller
After all checkboxes are checked, anyone who has write access can …

fix(pid_longitudinal_controller): revive hysteresis of state transition

---

autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/components/tier4_control_component.launch.xml

This PR adds a parameter to set AEB's state check to true or false in the launch file, this changes is aimed at facilitating ci/cd evaluation where turning this parameter on and off is sometimes necessary depending on the evaluation tool (DLR, planning simulation, etc).
Example usage: 
`ros2 launch autoware_launch logging_simulator.launch.xml map_path:=$HOME/autoware_map/lane_change_map  vehicle_model:=lexus sensor_model:=aip_xx1  use_aeb_autoware_state_check:=false
`
Note, requires universe changes:  https://github.com/autowarefoundation/autoware.universe/pull/9263
PSim
The PR author **must** check the checkboxes …

feat(aeb): set global param to override autoware state check

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml

disable out side stop feature because the feature is not well designed yet around the intersections.
https://github.com/autowarefoundation/autoware.universe/pull/8072
psim and teir4 internal scenario tests

revert(obstacle_cruise): disable ouside stop feature

---

autoware_launch/config/planning/scenario_planning/common/costmap_generator.param.yaml

Change parameters used to filter the pointcloud to represent height in the vehicle frame instead of in the lidar frame.
See https://github.com/autowarefoundation/autoware.universe/pull/9311

feat(costmap_generator): change lidar height thresholds to vehicle frame

---

autoware_launch/launch/components/tier4_simulator_component.launch.xml
autoware_launch/launch/planning_simulator.launch.xml

Autoware Launch in the main branch currently fails to launch due to lack of argument to `launch_scenario_simulator_v2_adapter`. This is caused by the change of argument name in Autoware.Universe in [this PR](https://github.com/autowarefoundation/autoware.universe/pull/9180).
This resolved this issue by updating the argument name appropriately.
I have tested in my local machine that it works after updating the argument name. …

feat: change the old diagnostic_convertor to scenario_simulator_v2_adapter

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml

The safety check parameter is very conservative, causing unnecessary deceleration and inconvenience to following vehicles.
In this PR, the parameter was tuned based on an actual drving rosbag.
tier4 internal ticket: https://tier4.atlassian.net/browse/RT1-8296
psim + perceptiojn reproducer
before
https://github.com/user-attachments/assets/9bfd1210-dbb7-4d6a-b765-9180fb68ca3b
after
https://github.com/user-attachments/assets/62a981b0-d4a1-45bf-8bdb-1d7568348492
2024/11/14 https://evaluation.tier4.jp/evaluation/reports/f4e6c6bc-5a98-5bb2-985f-64efce6ff0a6/?project_id=prd_jt
The PR author **must** check the checkboxes below before …

feat(goal_planner): loosen safety check to prevent unnecessary stop

---

autoware_launch/config/system/system_diagnostic_monitor/autoware-main.yaml

Sort alphabetically
part of https://github.com/autowarefoundation/autoware_launch/issues/1221

chore(system_diagnostic_monitor): sort paths

---

autoware_launch/config/control/preset/default_preset.yaml
autoware_launch/config/control/preset/dlr_control_validator_preset.yaml
autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/components/tier4_control_component.launch.xml
autoware_launch/launch/e2e_simulator.launch.xml
autoware_launch/launch/logging_simulator.launch.xml
autoware_launch/launch/planning_simulator.launch.xml

Add control/preset.yaml to control which modules to launch for control modules just as how planning modules are launched.
autoware.universe PR: https://github.com/autowarefoundation/autoware.universe/pull/9351
Psim, [Evaluator](https://evaluation.tier4.jp/evaluation/reports/67e201f0-a840-52de-b3d0-e6d64f9d14f8?project_id=prd_jt). …

feat(control): use preset.yaml to control which modules to launch for control modules

---

autoware_launch/config/perception/object_recognition/tracking/multi_object_tracker/multi_object_tracker_node.param.yaml

Add an option to enable/disable the multi object tracker node to consider odometry uncertainty.
This PR will be merged before PR https://github.com/autowarefoundation/autoware.universe/pull/9139

feat: add an option of odometry uncertainty consideration in multi_object_tracker_node

---

autoware_launch/launch/planning_simulator.launch.xml

`control_module_preset` was wrong and the planning simulator cannot be launched.
This PR fixed the issue.
psim launched successfully.

fix: default value for control_module_preset

---

autoware_launch/config/perception/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml

The grid size for ground segmentation has been updated from 0.1 to 0.5. This change improves the performance with the new grid data structure.
PR for the new grid data structure update https://github.com/autowarefoundation/autoware.universe/pull/9297
Please see [the root PR](https://github.com/autowarefoundation/autoware.universe/pull/9297). …

feat(scan_ground_filter): update grid size for ground segmentation

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

Update `lane_change.param.yaml` according to refactoring of LC parameters in the following PR:
https://github.com/autowarefoundation/autoware.universe/pull/9403

refactor(lane_change): refactor lane change parameters

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/static_obstacle_avoidance.param.yaml

Fixes :
- https://github.com/autowarefoundation/autoware.universe/issues/8539
Parent Issue :
- https://github.com/autowarefoundation/autoware.universe/issues/7485
https://github.com/user-attachments/assets/e48399da-0f3b-464f-9493-6da9f7486cd9
https://github.com/user-attachments/assets/a942f56f-b88c-4eac-92c4-411840a170fb
https://github.com/user-attachments/assets/70d617ae-0c4e-4628-b1fa-2a5e60f0019c
https://github.com/user-attachments/assets/6bee694d-37ec-459c-abda-465d46df1c35
https://github.com/user-attachments/assets/0c4ab26a-009a-4c30-baa4-da069bd4d4c9
https://github.com/user-attachments/assets/92127640-4812-497a-a239-f282cb97edb3
https://github.com/user-attachments/assets/f45ea742-b029-45ca-9063-f7e141a8cafb
https://github.com/user-attachments/assets/761f3710-0f9d-495d-b9c0-13b00d064a …

fix(static_obstacle_avoidance): improve avoidance for parked NPCs

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/dynamic_obstacle_avoidance.param.yaml

Fixes :
- https://github.com/autowarefoundation/autoware.universe/issues/8739
Parent Issue :
- https://github.com/autowarefoundation/autoware.universe/issues/7485
https://github.com/user-attachments/assets/9a586851-287f-4523-b4c3-61658f9ca1b5
https://github.com/user-attachments/assets/3880209c-1532-4a5f-ae54-163a9cfa6fe1
| Parameter Name       | Updated Value | Update Description                                  | 
| -------------------- | ------------- | --------------------------------------------------- | 
|lat_offset_from_obstacle      | 0.3 | lower lateral offset to avoid moving NPCs in narrow road                            | 
|margin_distance_around_pedestrian      | 0.8 | lower lateral offset to for pedestrian                          | 
|end_time_to_consider      | 1.0 | lower …

fix(dynamic_obstacle_avoidance): improve avoidance for moving NPCs

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/behavior_velocity_planner.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/behavior_velocity_planner_common.param.yaml
autoware_launch/launch/components/tier4_planning_component.launch.xml

This PR is related to the following PR.
https://github.com/autowarefoundation/autoware.universe/pull/9470
**Parent Issue:**
- Link
Tested on psim.
None.
None.
None.

refactor(autoware_behavior_velocity_planner_common,autoware_behavior_velocity_planner): separate param files

---

autoware_launch/config/control/autoware_autonomous_emergency_braking/autonomous_emergency_braking.param.yaml

add parameter to limit IMU path length and rename longitudinal offset
necessary change for the [PR](https://github.com/autowarefoundation/autoware.universe/pull/9463).

feat(autonomous_emergency_braking): add parameter to limit IMU path length and rename longitudinal offset

---

autoware_launch/rviz/planning_bev.rviz

Fix a bug that `autoware_launch/rviz/planning_bev.rviz` can't properly visualize the ego vehicle model.
It seems that there is another bug, which Wakabayashi san may fix in the future.
QuickTestPro: 

fix(rviz): fix a bug about visualizing ego model

---

autoware_launch/launch/autoware.launch.xml
autoware_launch/package.xml

https://github.com/autowarefoundation/autoware.universe/pull/9303
https://github.com/autowarefoundation/autoware/issues/5077
https://github.com/autowarefoundation/autoware/issues/4569

refactor(global_parameter_loader): prefix package and namespace with autoware

---

autoware_launch/launch/pointcloud_container.launch.py

This pull request fixes an issue where the following error occurs in `~/.ros/log`:
```
1733476966.5042253 [ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'glog_component' of type 'GlogComponent' in container '/pointcloud_container': Failed to find class with the requested plugin name.
```
- https://github.com/autowarefoundation/autoware.universe/pull/9302
Fix an error
[pull …

fix(pointcloud_container.launch.py): autoware_glog_component

---

autoware_launch/config/perception/object_recognition/detection/lidar_model/centerpoint.param.yaml
autoware_launch/config/perception/object_recognition/detection/lidar_model/centerpoint_sigma.param.yaml
autoware_launch/config/perception/object_recognition/detection/lidar_model/centerpoint_tiny.param.yaml
autoware_launch/config/perception/object_recognition/detection/lidar_model/pointpainting.param.yaml
autoware_launch/config/perception/object_recognition/detection/lidar_model/transfusion.param.yaml

parameter `iou_nms_target_class_names` to be removed by PR https://github.com/autowarefoundation/autoware.universe/pull/9595 and https://github.com/autowarefoundation/autoware.universe/pull/9612
None.
None.

fix(detection-lidar-model): remove unused iou_nms_target_class_names parameter

---

autoware_launch/config/system/mrm_emergency_stop_operator/mrm_emergency_stop_operator.param.yaml
autoware_launch/config/system/mrm_handler/mrm_handler.param.yaml

This PR contains the following changes.
1. Revert the mrm_emergency_stop parameter, which was changed by https://github.com/autowarefoundation/autoware_launch/pull/1099 half a year ago. These changes are oriented to AEB; however, these parameters are used for all MRM emergency stops. Therefore, I propose to revert these parameters to maintain any behavior other than AEB.
2. Enabling comfortable_stop. MRM comfortable stop was tested enough by tier4 operations. Now I recommend enabling it as public.
psim test
None.
None.

feat(MRM_handler, MRM_emergency_stop_operator): revert mrm_stop parameter, enable mrm_comfortable_stop

---

autoware_launch/config/control/trajectory_follower/longitudinal/pid.param.yaml

universe PR: https://github.com/autowarefoundation/autoware.universe/pull/9656
psim and tier4 scenario test
None.
None.

feat(pid_longitudinal_controller): change default slope compesation source to trajectory_adaptive

---

autoware_launch/config/perception/traffic_light_arbiter/traffic_light_arbiter.param.yaml

This PR is adding `ros parameter` for [this PR](https://github.com/autowarefoundation/autoware.universe/pull/9747).
I have checked degradation on [Evaluator](https://evaluation.ci.tier4.jp/evaluation/reports/8ffde025-0720-59e9-9300-18d76379227b?project_id=prd_jt).
Need to merge [this PR](https://github.com/autowarefoundation/autoware.universe/pull/9747) at the same time 
None.

feat(autoware_traffic_light_arbiter): add current time validation

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

Add flag parameter `enable_stopped_vehicle_buffer` to enable/disable keeping distance from front stopped object for lane change. [related PR](https://github.com/autowarefoundation/autoware.universe/pull/9785)
- PSIM
None.
None.

feat(lane_change): add feature flag param

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

Parameter for enabling frenet planner as path generation near terminal lane change.
https://github.com/autowarefoundation/autoware.universe/pull/9767
None.
None.

feat(lane_change): using frenet planner to generate lane change path when ego near terminal

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/drivable_area_expansion.param.yaml

Fix typo in param file.
`expended` -> `expanded`
None.
None.
None.

chore: fix typo in drivable_are_expansion.param.yaml

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

Parameterized incoming object yaw threshold.
[Related PR](https://github.com/autowarefoundation/autoware.universe/pull/9928).
| Change type   | Parameter Name | Type     | Default Value | Description       |
|:--------------|:---------------|:---------|:--------------|:------------------|
| Added | `collision_check.th_incoming_object_yaw`   | `double` | `2.3562`         | Objects with a heading difference from the ego exceeding this value are excluded from the safety check. |
| Added | `execution.extended_polygon_policy`   | `string` | `rectangle`         | Policy used to determine polygon's shape for safety check. |
| Added | `cancel.extended_polygon_policy`   | `string` | `rectangle`         | Policy used to determine polygon's shape for safety check. |
| Added | …

refactor(lane_change): add missing safety check parameter 

---

autoware_launch/config/system/system_monitor/net_monitor.param.yaml

This PR adds parameters for https://github.com/autowarefoundation/autoware.universe/pull/9538
The parameters in `net_monitor.param.yaml` is used to check UDP buf errors
I also fixed indent
None.

chore(system_monitor): add parameters for UDP buf errors

---

autoware_launch/launch/components/tier4_system_component.launch.xml

Reverts autowarefoundation/autoware_launch#1311
One of the dependent PR for https://github.com/autowarefoundation/autoware.universe/pull/9961 wasn't approved yet.
I will temporarily revert it to resolve runtime error.

revert: revert "feat: apply autoware prefix for state monitor"

---

autoware_launch/launch/components/tier4_system_component.launch.xml

This will merge the reverted change in https://github.com/autowarefoundation/autoware_launch/pull/1312 again.
Apply package name change.
https://github.com/autowarefoundation/autoware.universe/pull/9961
Launch planning simulation.
None.
None.

feat: apply autoware prefix for state monitor

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml

https://github.com/autowarefoundation/autoware.universe/pull/10005
see https://github.com/autowarefoundation/autoware.universe/pull/10005
None.
None.

feat(goal_planner): introduce bezier based pullover for bus stop area

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner/goal_planner.param.yaml

see https://github.com/autowarefoundation/autoware.universe/pull/10050
see https://github.com/autowarefoundation/autoware.universe/pull/10050
None.
None.

refactor(goal_planner): remove use_object_recognition because it is default

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/traffic_light.param.yaml

To address the issue in the traffic_light module where the vehicle abruptly stops the moment the light changes from amber to green without performing a pass judge when the speed is below 2.0 m/s, we will adjust the speed threshold.
At the same time, the threshold for performing pass judge has been parameterized, considering potential requests to adjust it.
Pull Request for autoware.universe: https://github.com/autowarefoundation/autoware.universe/pull/10064
[TIERIV internal link] https://tier4.atlassian.net/browse/RT0-33895
We confirmed an improvement in the sudden deceleration behavior using the rosbag-based logging_simulator, where sudden deceleration had previously been occurring.
None.
None.
Improvements:
Enables pass judge to be applied even at low speeds (1.0 ~ 2.0 m/s), preventing …

feat(autoware_behavior_velocity_traffic_light_module): adjust velocity threshold for ensure stop at yellow light

---

autoware_launch/config/perception/occupancy_grid_map/pointcloud_based_occupancy_grid_map.param.yaml

Since the introduction of 
https://github.com/autowarefoundation/autoware.universe/pull/9542
The OGM creation is faster, making the subsample filters (which were added to reduce the processing time of the OGM) less relevant.
Run autoware with a few rosbags to evaluate the processing times with and without this PR
The subsample filters presented the following processing times:
- obstacle: 2-5ms
- raw: around 10ms
Processing time of the OGM:
- with subsample filters: 3.7ms
- without subsample filters: 8ms
Note: of the 8ms, 6.4ms are just to copy the data to the device ! If inputs use the blackboard (soon to be introduced), this copy will not be needed.
None.
None.

feat(autoware_probabilistic_occupancy_grid_map): disabled the subsample filters for the ogm

---

autoware_launch/config/perception/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml
autoware_launch/launch/components/tier4_perception_component.launch.xml

move parameters `use_single_frame_filter` and `use_time_series_filter` from ground_segmentation parameter file to launch file
https://github.com/autowarefoundation/autoware.universe/pull/10102
* Parameter change
use_time_series_filter -> use_obstacle_segmentation_time_series_filter
use_single_frame_filter -> use_obstacle_segmentation_single_frame_filter
tested in a local environment with logging-simulator.
option combinations of (use_single_frame_filter=false, use_time_series_filter= false), ( use_single_frame_filter=false, use_time_series_filter=true)
None.
None.

fix(ground_segmentation): bring junction parameter from param file to launch argument

---

autoware_launch/config/perception/traffic_light_multi_camera_fusion/traffic_light_multi_camera_fusion.param.yaml
autoware_launch/launch/components/tier4_perception_component.launch.xml

PR for universe: https://github.com/autowarefoundation/autoware.universe/pull/10144
Currently, the parameters for `traffic_light_multi_camera_fusion` are [hardcoded in the launch file](https://github.com/autowarefoundation/autoware.universe/blob/b4d9155fbe78aaf35f976af808b2ca62d1727d1f/launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light.launch.xml#L61-L62), preventing modifications from the launch file.
To resolve this issue, I modified it to read parameters from a YAML file in `autoware_launch`.
Please see https://github.com/autowarefoundation/autoware.universe/pull/10144
The default values in the parameter file is the same as the one in `autoware.universe`.
https://github.com/TomohitoAndo/autoware.universe/blob/614ac8e762e644aec1b1d2b74b87755c27f1a453/perception …

chore(traffic_light_multi_camera_fusion): read parameters from yaml file

---

autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/components/tier4_perception_component.launch.xml
autoware_launch/launch/e2e_simulator.launch.xml

- To unify the renaming of `enable_fine_detection` parameter at https://github.com/autowarefoundation/autoware.universe/pull/9731
- Note that this PR should mereger together with above PR. 
I checked new tlr and existing perception pipeline on Evaluator.
https://evaluation.ci.tier4.jp/evaluation/reports/e545bfca-9777-5031-9e92-818bd694e2df?project_id=prd_jt
And I checked AWSIM works on my local pc under below conditions.
- `traffic_light_recognition/use_ml_detector` : false
- `traffic_light_recognition/use_ml_detector` : true
- w/ `traffic_light_recognition/ml_detection_model_type` : fine_detector_model
- `traffic_light_recognition/use_ml_detector` : true
- w/ `traffic_light_recognition/ml_detection_model_type` : whole_image_detection_model
[Screencast from 02-18-2025 05:24:59 …

chore(traffic_light): rename enable_fine_detection

---

autoware_launch/config/perception/object_recognition/prediction/map_based_prediction.param.yaml

delete unsed function in autoware_map_based_prediction
https://github.com/autowarefoundation/autoware.universe/pull/10090
I confirmed that Autoware builds successfully and launches properly.
None.
None.
None.

chore(autoware_map_based_prediction): delete unused function and parameter

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/motion_velocity_planner.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/obstacle_slow_down.param.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/obstacle_stop.param.yaml

Adds params for https://github.com/autowarefoundation/autoware.universe/pull/10112
Results in https://github.com/autowarefoundation/autoware.universe/pull/10112
None.
None.

feat(autoware_motion_velocity_obstacle_slow_down_module): params for obstacle stop and slow down modules

---

autoware_launch/config/planning/preset/default_preset.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/path_generator/path_generator.param.yaml
autoware_launch/launch/components/tier4_planning_component.launch.xml

launcher update for https://github.com/autowarefoundation/autoware.universe/pull/10217
same to https://github.com/autowarefoundation/autoware.universe/pull/10217
None.
None.

feat(behavior_planning): add behavior_path_planner_type to launch path_generator

---

autoware_launch/config/planning/preset/default_preset.yaml
autoware_launch/launch/components/tier4_simulator_component.launch.xml

launcher update for https://github.com/autowarefoundation/autoware.universe/pull/10223
- enable virtual traffic light by default
- launch dummy_infrastructure when scenario simulator
same to https://github.com/autowarefoundation/autoware.universe/pull/10223
None.
None.

feat(dummy_infrastructur): auto approval when ego stops at stop line

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/obstacle_stop.param.yaml

Without this PR, the stop position by the obstacle_stop_module moves forward when the ego cannot stop before the stop position due to the control error, etc.
In the simulation test and real experiment, there were some cases where the ego cannot decelerate well, and the ego got very close to the front object. To reduce this risk, this PR disables the flag.
None.
None.

fix(planning): param update for sudden stop

---

.github/labeler.yaml

Fix labeler CI failures that have been occurring since https://github.com/autowarefoundation/autoware_launch/pull/1058 .
labeler.yaml must be updated as the labeler is updated to v5.
ref: https://github.com/actions/labeler/tree/main#pull-request-labeler
None.
None.

chore: update labeler.yaml for v5

---

autoware_launch/config/control/control_validator/control_validator.param.yaml

- https://github.com/autowarefoundation/autoware.universe/pull/10240
Add new nominal latency threshold.
```patch
diff --git a/autoware_launch/config/control/control_validator/control_validator.param.yaml b/autoware_launch/config/control/control_validator/control_validator.param.yaml
index 7485df43..4116f413 100644
--- a/autoware_launch/config/control/control_validator/control_validator.param.yaml
+++ b/autoware_launch/config/control/control_validator/control_validator.param.yaml
@@ -12,6 +12,7 @@
rolling_back_velocity: 0.5
over_velocity_offset: 2.0
over_velocity_ratio: 0.2
+      nominal_latency: 0.01
vel_lpf_gain: 0.9 # Time constant 0.33
hold_velocity_error_until_stop: true
```
Psim
None.
None.

feat(control_validator): add diag to check control component latency

---

autoware_launch/config/planning/scenario_planning/common/planning_validator/planning_validator.param.yaml

- https://github.com/autowarefoundation/autoware.universe/pull/10241
Add new nominal latency threshold.
```patch
diff --git a/autoware_launch/config/planning/scenario_planning/common/planning_validator/planning_validator.param.yaml b/autoware_launch/config/planning/scenario_planning/common/planning_validator/planning_validator.param.yaml
index da337d70..19fd7fec 100644
--- a/autoware_launch/config/planning/scenario_planning/common/planning_validator/planning_validator.param.yaml
+++ b/autoware_launch/config/planning/scenario_planning/common/planning_validator/planning_validator.param.yaml
@@ -27,6 +27,7 @@
velocity_deviation: 100.0
distance_deviation: 100.0
longitudinal_distance_deviation: 1.0
+      nominal_latency: 0.1
parameters:
```
Psim&Evaluator
None.
None.

feat(planning_validator): add diag to check planning component latency

---

autoware_launch/launch/components/tier4_simulator_component.launch.xml
autoware_launch/launch/planning_simulator.launch.xml

This PR disable to use TLR in planning_simulator. So it works well if you do not have cuda environment. (TLR often use cuda)
```
ros2 launch autoware_launch planning_simulator.launch.xml map_path:=$HOME/autoware_map/sample-map-planning vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit
```
None.
None.

feat(planning_simulator): disable tlr in psim

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/obstacle_cruise.param.yaml

* Please see https://github.com/autowarefoundation/autoware.universe/pull/10227
* Please see https://github.com/autowarefoundation/autoware.universe/pull/10227
None.
None.

fix(obstacle_cruise_planner): ignore invalid stopping objects

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/path_generator/path_generator.param.yaml

Adds following two parameters for `autoware_path_generator` package on the `autoware.core` side.
```
refine_goal_search_radius_range: 7.5  # [m]
search_radius_decrement: 1.0
```
This fix is for this `autoware.core` side PR: https://github.com/autowarefoundation/autoware.core/pull/227. Thus, **THIS PR MUST BE MERGED WITH THE `autoware.core` SIDE PR AT THE SAME TIME TOGETHER**.
The tests are performed by using the scenario evaluator. Please see the PR description in the following PR:
https://github.com/autowarefoundation/autoware.core/pull/227
Please do not enable auto merge as we need to be aware of the timing of merge as description above.
The `autoware.core` side will have a feature that makes the path smooth ([link to PR](https://github.com/autowarefoundation/autoware.core/pull/227))

feat(path_generator): add parameters

---

autoware_launch/config/planning/preset/default_preset.yaml

Since intersection_occlusion feature was created to replace the merge_from_private feature and is already enabled, this PR disables the merge_from_private.
None.
None.

feat: disable merge_from_private

---

autoware_launch/config/control/trajectory_follower/longitudinal/pid.param.yaml

The behavior when crossing the stop line is handled by the control_validator as a reference. For this reason, similar functions on the pid_long side are disabled as default.
psim
None.
None.

feat(pid_long): disable overshoot_emergency

---

autoware_launch/config/perception/object_recognition/tracking/multi_object_tracker/input_channels.param.yaml

add configuration channel detection options
-  can_spawn_new_tracker
-  can_trust_existence_probability
-  can_trust_extension
-  can_trust_classification
-  can_trust_orientation
update config file for PR https://github.com/autowarefoundation/autoware.universe/pull/10277
None.
None.

feat(multi_object_tracker): add input channel flags for selective update per channel

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml

Currently, crosswalk stop position calculation uses the same acceleration value with common.param.yaml.
This may cause stop position creep for some velocity_smother params. 
For example, if we set `jerk_weight: 0.1` in JerkFiltered.param.yaml, we may face to the creep problem.
This PR fix this issue by ensure acceleration margin against common.param.yaml.
Before:
[Screencast from 2025年03月24日 11時23分27秒.webm](https://github.com/user-attachments/assets/26dfff6a-7d5f-48a5-aa6a-3e73fc15d7f0)
tier4 scenario tests and psim
None.
None.

feat(crosswalk): fix stop position calclaton params

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml

This PR created to add `consider_obj_on_crosswalk_on_red_light` parameter to consider and do not ignore objects if they are on the crosswalk when the crosswalk pedestrian traffic light is red.
:bookmark_tabs:  It is left as `consider_obj_on_crosswalk_on_red_light`: `false` not to change the current system behavior. 
[Related universe PR link](https://github.com/autowarefoundation/autoware_universe/pull/10332)
None.
None.

feat(crosswalk_module): add param to consider objects on crosswalk when pedestrian traffic light is red

---

.github/CODEOWNERS-manual

Update code owners for perception and sensing.
- remove Minoda-san
- add Gu-san and Saeki-san for perception
- add Lee and Kenzo-san for sensing
None.
None.

fix: update code owners for perception and sensing components

---

autoware_launch/launch/components/tier4_simulator_component.launch.xml

Remove the dependency on autoware_launch from tier4_simulator_launch.
Related to https://github.com/autowarefoundation/autoware_universe/pull/10415.
**Parent Issue:**
- https://github.com/autowarefoundation/autoware_universe/pull/10404#discussion_r2030570800
1. Checkout https://github.com/autowarefoundation/autoware_universe/pull/10415
2. Run planning simulator and drive in autonomous mode.
None.
None.

feat(autoware_launch): remove exec_depend on autoware_launch from tier4_simulator_launch

---

autoware_launch/config/control/lane_departure_checker/lane_departure_checker.param.yaml

The official supported road boundary tags is `road_border` and not `curbstone`. 
However, `road_border` is not the default setting for the `boundary_type_to_detect` in the lane departure checker. In this PR, we replace the default setting to `road_border`, and removed `curbstone` to prevent misleading tags.
Place ego vehicle on top of linestrings with road_border tags. Ensure that tier4_diagnostic is triggered.
None.
None.

fix(lane_departure_checker): replace curbstone to road_border (RT1-9845)

---

autoware_launch/launch/autoware.launch.xml
sensor_kit/awsim_labs_sensor_kit_launch/awsim_labs_sensor_kit_description/config/sensor_kit_calibration.yaml
sensor_kit/awsim_labs_sensor_kit_launch/awsim_labs_sensor_kit_launch/launch/imu.launch.xml
sensor_kit/awsim_sensor_kit_launch/awsim_sensor_kit_launch/launch/imu.launch.xml
sensor_kit/sample_sensor_kit_launch/sample_sensor_kit_description/config/imu_corrector.param.yaml
sensor_kit/sample_sensor_kit_launch/sample_sensor_kit_launch/launch/imu.launch.xml

**Parent Issue:**
- https://github.com/autowarefoundation/autoware/issues/5975
**Old location:**
https://github.com/autowarefoundation/autoware_individual_params/tree/main/individual_params/config/default/sample_sensor_kit
**New Location:**
https://github.com/autowarefoundation/autoware_launch/tree/main/sensor_kit/sample_sensor_kit_launch/sample_sensor_kit_description/config
- This has been repeated for all 4 managed `sensor_kit`s.
- The reference in `autoware.launch.xml` is updated.
- `sample_sensor_kit_launch/launch/imu.launch.xml`'s reference is updated.
- Tested with:
- [AWSIM Labs Demo](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/digital-twin-simulation/awsim-tutorial/) (AWSIM should work the same way, changes are identical)
- …

feat: remove individual_params references

---

autoware_launch/config/system/duplicated_node_checker/duplicated_node_checker.param.yaml

This adds `/simulation/getParameter` to the ignore list for duplicate node checker. 
Otherwise, Autoware won't start for scenario simulation.
Test with these PRs:
- https://github.com/autowarefoundation/autoware/pull/6064
- https://github.com/autowarefoundation/autoware/pull/6063
None.
None.

feat(duplicated_node_checker): ignore duplicate get parameter

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/behavior_velocity_planner.param.yaml

This PR removes the unused parameter for `behavior_velocity_planner`. The PR and https://github.com/autowarefoundation/autoware_core/pull/457 must be merged at the same time.
None.
None.

feat(behavior_velocity_planner)!: remove unused function parameter for extendLine

---

autoware_launch/config/system/diagnostics/control.yaml

Reflect https://github.com/autowarefoundation/autoware_universe/pull/10337.
The diag `lane_departure_checker_node: trajectory_deviation` is no longer used.
Check that the vehicle drives in autonomous mode using planning simulator.
None.
None.

feat(autoware_launch): remove trajectory_deviation from diagnostic graph

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/drivable_area_expansion.param.yaml

Remove the extra offsets used by default in the dynamic drivable area expansion.
Evaluator (TIER IV internal link): https://evaluation.tier4.jp/evaluation/reports/46508015-858e-55b6-b865-d2d974ae8a27?project_id=prd_jt
None.
None.

feat(dynamic_drivable_area_expansion): set extra offsets to 0

---

autoware_launch/config/system/diagnostics/localization.yaml
autoware_launch/config/system/diagnostics/planning.yaml

**This PR should be merged after https://github.com/autowarefoundation/autoware_universe/pull/10539.**
Use diagnostics from adapi node instead of the [component_state_diagnostics](https://github.com/autowarefoundation/autoware_universe/blob/main/system/autoware_system_diagnostic_monitor/script/component_state_diagnostics.py) script.
Check that the vehicle drives in autonomous mode using simple planning simulator.
None.
None.

feat(autoware_launch): use adapi diagnostics

---

autoware_launch/launch/components/tier4_simulator_component.launch.xml

**This PR must be merged before https://github.com/autowarefoundation/autoware_universe/pull/10770**
We are currently trying to run tier4_simulator_component.launch.xml as standalone launch in order to run Autoware in multi-container setup in this issue. However, probabilistic_occupancy_grid_map.launch.xml fails to launch properly because it cannot find pointcloud_container, which is not created in multi-container settings. (Check [my comment](https://github.com/autowarefoundation/autoware/pull/6184#issuecomment-2948129756) for the details)
This PR adds `use_pointcloud_container` to tier4_simulator launch so that users can configure whether to use pointcloud_container from launch argument to resolve the issue. 
It is set to true by default to keep the behavior when we launch this file …

feat: add pointcloud container arg for simulator component

---

autoware_launch/config/perception/object_recognition/detection/lidar_model/centerpoint.param.yaml
autoware_launch/config/perception/object_recognition/detection/lidar_model/centerpoint_sigma.param.yaml
autoware_launch/config/perception/object_recognition/detection/lidar_model/centerpoint_tiny.param.yaml
autoware_launch/config/perception/object_recognition/detection/lidar_model/pointpainting.param.yaml

Update the default launcher configs for CenterPoint and PointPainting to update `score_threshold` to `score_thresholds` to accept class-wise thresholds. 
Please check the [PR](https://github.com/autowarefoundation/autoware_universe/pull/10881).
None.
None.

feat(autoware_lidar_centerpoint): update score_threshold to score_thresholds for class-wise thresholds

---

autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/components/tier4_perception_component.launch.xml
autoware_launch/launch/components/tier4_sensing_component.launch.xml

This is a backport of https://github.com/autowarefoundation/autoware_launch/pull/1523 to humble branch. 
I have tested locally that the issue with PSim is fixed on humble branch.
None.
None.

fix:  `pointcloud_contaner` is launched on `autoware.launch.xml` by default (#1523)

---

autoware_launch/launch/components/tier4_simulator_component.launch.xml

The `use_point_cloud_container` argument was added to the `tier4_simulator_component.launch.xml` to realize isolated component-wise launching. https://github.com/autowarefoundation/autoware_launch/pull/1479
However, the `tier4_simulator_launch/launch/simulator.launch.xml` in autoware_universe uses `use_pointcloud_container` that doesn't separate "point" and "cloud".
https://github.com/autowarefoundation/autoware_universe/blob/60075cdf11ddb43a4b6c0bfa9c8f59ffb4e6ba19/launch/tier4_simulator_launch/launch/simulator.launch.xml#L27
This PR fixes the `tier4_simulator_component.launch.xml` to make them the same.
None.
None.

fix(tier4_simulator_component): fix argument name in tier4_simulator_component.launch.xml

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/obstacle_stop.param.yaml

This PR adds new parameters as part of the feature update for the outside region.
With this update, the reliability of the stop functionality for obstacles in the outside region has been improved. Therefore, this feature is now enabled by default for all object types except for unknown.
The time parameter is set to a very short duration, over which the constant velocity assumption is considered valid.
Furthermore, the deceleration parameter is set to a value that pedestrians can easily achieve.
If you want to learn more about the design philosophy, please see feature PR https://github.com/autowarefoundation/autoware_core/pull/517
psim 
tier4 scenario tests
None.
None.

feat(obstacle_stop_module): add parameters for "outside" region obstacles

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/run_out.param.yaml

Improve the predicted paths filtering used by the `run_out` module (`motion_velocity_planner`).
It is now possible to _strictly_ cut predicted paths based on map geometries (polygons, lanelets, or linestrings). This means that the cutting is always applied without considering the preserved distance or duration.
Required for the universe PR: https://github.com/autowarefoundation/autoware_universe/pull/10887
Psim
More control over the map based predicted paths filtering.

feat(run_out): add option for strict cutting of predicted paths

---

autoware_launch/config/planning/preset/default_preset.yaml
autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/run_out.param.yaml

Enable the new `run_out` module in the `motion_velocity_planner` and disable the one in the `behavior_velocity_planner`.
[TIER IV Evaluator](https://evaluation.tier4.jp/evaluation/reports/cb5e6867-e623-509d-b72d-723c3fdbcaa5?project_id=prd_jt&state=failed)
None.
Less false positives caused by the `run_out` module.

feat(run_out): enable new module and disable the previous one

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/out_of_lane.param.yaml

Add an option to the `out_of_lane` module to validate predicted paths before considering an out of lane collision.
Universe PR: https://github.com/autowarefoundation/autoware_universe/pull/10882
Psim and rosbag.
None.
Less false positives with the `out_of_lane`.

feat(out_of_lane): validate predicted paths on lanelets

---

autoware_launch/config/localization/pose_instability_detector.param.yaml
autoware_launch/launch/components/tier4_localization_component.launch.xml

This PR revises the launch configuration for `pose_instability_detector` so that parameters of `pose_instability_detector`can be defined in autoware_launch, and the node will read parameters from `autoware_launch/config` not the one in the own package by default. 
After I changed the value of `heading_velocity_maximum` from `16.667` to `20.000`, I got the result below by `ros2 param dump /localization/pose_twist_fusion_filter/pose_instability_detector`.
**Merge this PR before** https://github.com/autowarefoundation/autoware_universe/pull/10961
`pose_instability_detector` will read parameters from the one in `autoware_launch/config` when launched from autoware_launch

feat(autoware_pose_instability_detector): make pose_instability_detector configurable in autoware_launch

---

autoware_launch/launch/components/tier4_localization_component.launch.xml

This is a follow up PR from https://github.com/autowarefoundation/autoware_launch/pull/1469.
This adds global parameter loader to localization component launch file so that localization component can be launched independently. 
I have tested that it does not affect the overall behavior of autoware.launch.xml with logging simulator.
None.
None.

feat: add global parameters to tier4_localization_component.launch.xml

---

autoware_launch/launch/components/tier4_localization_component.launch.xml

This is follow up PR for https://github.com/autowarefoundation/autoware_launch/pull/1513. This also adds pointcloud container arguments for localization launch in order to launch localization component in independent container if user wish to do so. By default, it won't launch the pointcloud container and use the one from the top autoware.launch.xml.
I have tested locally that it does not affect the current behavior of autoware with logging simulator.
None.
None.

feat: add launch_pointcloud_container to tier4_localization_component.launch.xml

---

autoware_launch/launch/autoware.launch.xml
autoware_launch/launch/components/tier4_localization_component.launch.xml

This is a backport of the following PRs to humble branch:
* https://github.com/autowarefoundation/autoware_launch/pull/1527
* https://github.com/autowarefoundation/autoware_launch/pull/1528
* https://github.com/autowarefoundation/autoware_launch/pull/1529
I have built locally and confirmed that it works with logging simulator. 
None.
None.

chore: back port 1527, 1528, 1529 to humble

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/boundary_departure_prevention.param.yaml

Currently ego's predicted path is used as is, and all departure points and critical departure points are accepted as is. This has caused a lot of false positive to occur especially when path chatters.
This PR provides two configurable option:
1. Trim ego points and update departure type based on cutoff time.
2. add hysteresis (on_time_buffer and off_time_buffer) as countermeasure to chattering predicted path.
Related PR: https://github.com/autowarefoundation/autoware_universe/pull/11073
None.
None.

feat(boundary_departure): configurable departure points and type based on time

---

autoware_launch/config/perception/object_recognition/tracking/multi_object_tracker/multi_object_tracker_node.param.yaml

tracker configuration `confident_count_threshold` has been deprecated by https://github.com/autowarefoundation/autoware.universe/issues/10378
remove unused parameter
https://github.com/autowarefoundation/autoware_universe/pull/11132
None.
None.

fix(multi_object_tracker): remove confident_count_threshold parameter

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/boundary_departure_prevention.param.yaml

Add `on_time_buffer` for `critical_departure`. 
The parameter works as hysteresis for accepting critical departure point.
https://github.com/autowarefoundation/autoware_universe/pull/11126
| Change type   | Parameter Name | Type     | Default Value | Description       |
|:--------------|:---------------|:---------|:--------------|:------------------|
| Added | `on_time_buffer_s.critical_departure`   | `double` | `0.15`         | Continuous detection time required to accept new critical departure point. [s] |
| Version | Parameter Name   | Type     | Default Value | Description       |
|:--------|:-----------------|:---------|:--------------|:------------------|
| Old     | `on_time_buffer_s` | `double` | `0.15`         | Continuous detection time threshold to insert departure point into …

feat(boundary_departure): on time buffer for critical departure

---

autoware_launch/launch/components/tier4_simulator_component.launch.xml

currently psim with localization can not run.
due to https://github.com/autowarefoundation/autoware_universe/pull/10961 , autoware_launch pose_instability_detector_param_path is necessary to be used.
run psim with 
```
<arg
name="localization_sim_mode"
default="pose_twist_estimator"
description="Select localization mode. Options are 'none', 'api' or 'pose_twist_estimator'. 'pose_twist_estimator' starts most of the localization modules except for the ndt_scan_matcher. 'api' starts an external API for initial position estimation. 'none' does not start any localization-related process."
/>
```
- [[PR check][Lexus][FuncVerificationScenario_Basic] planning test](https://evaluation.tier4.jp/evaluation/reports/023f822e-fe69-5324-83c1-f76a3b9d6b7b?project_id=prd_jt)
- [[PR …

fix(simulator): fix pose_instability_detector_param_path path

---

autoware_launch/config/system/diagnostics/localization.yaml
autoware_launch/config/system/diagnostics/planning.yaml

The short-circuit-and type is deprecated, so use and type instead.
Dependencies will be defined using the dependent field.
Check autonomous driving in planning simulator.
None.
None.

feat(autoware_launch): change short-circuit of diag setting

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/boundary_departure_prevention.param.yaml

The PR modified 2 items:
- reduce logging level for near boundary, as to prevent the module from printing redundant log when the vehicle is operated at narrow areas.
- reduce brake_delay_s to relax the stopping criteria.
[TIER IV Internal Link - ControlDLR Test](https://evaluation.tier4.jp/evaluation/reports/27dc7420-c207-5501-b089-55fc274a9cab?project_id=prd_jt)
[TIER IV Internal Link - FuncVerification Test](https://evaluation.tier4.jp/evaluation/reports/5d695f8b-ca16-5676-b2f4-5a4e5fb01d02?project_id=prd_jt)
[TIER IV Internal Link - CommonScenario_Basic Test](https://evaluation.tier4.jp/evaluation/reports/0476e862-f28f-5306-b41c-090d79994610?project_id=prd_jt)
None.
None.

fix(boundary_departure): reduce brake delay

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/obstacle_stop.param.yaml

The oncoming vehicle stopping function is disabled by default as it is still under development. A threshold has been set to ensure it remains inactive.
tier4 scenario test
engage available in psim
None.
None.

revert(obstacle_stop): disable opposing traffic feature

---

autoware_launch/config/system/system_monitor/cpu_monitor.param.yaml
autoware_launch/config/system/system_monitor/hdd_monitor.param.yaml

Use AF_UNIX domain sockets for IPC between the "autoware_system_monitor" component (hdd_monitor, cpu_monitor) and its helper applications (hdd_reader, msr_reader) instead of TCP/IP sockets to avoid cross-talking among multiple ECUs.
This Pull Request is related to [PR #11199 for autwarefoundation/autoware_universe](https://github.com/autowarefoundation/autoware_universe/pull/11199).
- The "autoware_system_monitor" component built with [PR #11199 for autwarefoundation/autoware_universe](https://github.com/autowarefoundation/autoware_universe/pull/11199) reads values from the yaml files and changes the parameters accordingly.
- The "autoware_system_monitor" and its helper applications (hdd_reader, msr_reader) can communicate through the AF_UNIX domain sockets.
- Version mismatch between the …

fix(hdd_monitor,cpu_monitor): use unix sockets for IPC with helper applications

---

autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/obstacle_slow_down.param.yaml

follow a new feature https://github.com/autowarefoundation/autoware_universe/pull/11343
This new feature could create a gap between the stopping and slowing-down distances for obstacles. This might occur when an obstacle is not close enough to trigger obstacle_stop but is too close for obstacle_slow_down to engage properly, especially for the case of different `wheel_off_track_scale` values are set to each module. To address this, we will effectively disable the feature that ignores objects with a short lateral distance in obstacle_slow_down by setting obstacle_slow_down.obstacle_filtering.min_lat_margin to a sufficiently small negative value.
Known issue: meaningless markers will appear around the obstacle_stop wall.
engage available in psim
tier4 scenario test
None.
None.

feat(obstacle_slow_down): add curve margin

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/start_planner/start_planner.param.yaml

change the priority to set the CLOTHOID planner as the highest priority, with the SHIFT planner as the second priority. 
We have confirmed that path generation with these priorities can handle most of the currently anticipated use cases.
The conventional geometric planner will be disabled due to its instability.
None.
None.

feat(start_planner): update search priority to prioritize CLOTHOID over SHIFT

---

autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml

**Issue**
The safety check is continuously executed for an approved lane change path. [During this process, the lane change module samples acceleration, assuming the ego vehicle can slow down if it is changing lanes behind another object](https://github.com/autowarefoundation/autoware_universe/pull/7943). This assumption relies on other modules to decelerate the ego vehicle to avoid collisions.
However, the same sampling is also applied to rear-moving or overtaking objects. Since no countermeasure currently exists for these cases, this can lead to false positives—allowing a lane change even when there is a potential collision.
**Fix**
The following [PR#11342 in autoware.universe](https://github.com/autowarefoundation/autoware_universe/pull/11342) introduces a fix. However, due to an …

fix(lane_change): reduces sampling number
